### ISSUE TITLE
PowerShell not found

### ISSUE THREAD

**Issue by marsrvr** [ipfs-shipyard/ipfs-desktop#1000]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by hacdias** [comment]
It indicates you don't have powershell installed, which is strange taking in account all the latest versions have it. Which Windows version do you have?

**Comment by marsrvr** [comment]
Microsoft Windows [Version 10.0.18362.239]
(c) 2019 Microsoft Corporation. All rights reserved.

They may have changed the API on you.

Sent from Mail for Windows 10

**Comment by hacdias** [comment]
I just tried on a clean install of Windows 10 and it works flawlessly. Could you check if `powershell.exe` is on your PATH? Open `cmd` and type `powershell.exe`, please.

**Comment by hacdias** [comment]
I'm closing due to the lack of information. You can re-open this if it happens again, with more information.
