### ISSUE TITLE
OSX Catalina Beta failure to launch or install

### ISSUE THREAD

**Issue by fliiteAI** [ipfs-shipyard/ipfs-desktop#1004]
Running Version 10.15 Beta (19A512f) of OSX

Neither the zip version nor the DMG version of IPFS will install or run.   Attempting to run installer ipfs-desktop-0.8.0.dmg and the application from the following zip archive from releases ipfs-desktop-0.8.0-mac.zip .  System complains from DMG version: 

![image](https://user-images.githubusercontent.com/50529112/62318775-67e62f00-b451-11e9-8761-80c4d33ff508.png)

And when just trying to run the Desktop executable from the Zip archive:

![image](https://user-images.githubusercontent.com/50529112/62318843-8ba97500-b451-11e9-9e2e-e5bda6eac792.png)

Normally package run denials invoke a security preferences change regarding developer being an unknown and wants and override authorization given.  No such possibility exists in the System Preferences Security panel which is abnormal.

I understand this is a developer version of the OS but didn't see anything in the tickets referencing Catalina.  Thought I'd give a heads up.

**Comment by hacdias** [comment]
Thanks for reporting this. I wonder if this is caused because we're not using the latest SDK which should be compatible with the latest macOS version. I'll take a look at this.

If you have Node.js installed, could you try running it manually from the command line?

- Clone
- `npm i && npm start`

**Comment by hacdias** [comment]
As per #1053, the latest build seems to launch well on Catalina! Closing this.

**Comment by andrew** [comment]
@hacdias I believe this is a separate issue to #1053, I ran into it this morning when downloading and trying to run 0.10.2: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1211#issuecomment-576683161
