### ISSUE TITLE
Feature request: Publish websites with IPFS

### ISSUE THREAD

**Issue by andrasfuchs** [ipfs-shipyard/ipfs-desktop#1019]
I suppose the node's Public folder is intended to be public by default. It would be logical to make that folder public by publishing it as a node's IPNS folder so that it could be accessed through the <IPFS gateway>/ipns/<peer ID> URL.

If you want to do that now, you need to call `ipfs name publish <new hash of the folder>` every time you change the content of your Public folder manually. It would be great if that was automatic.

Could you add this functionality?

Also, as a nice to have change in the UI would be that if you were trying to share your public folder, the pop-up dialog would show not just the link with the IPFS hash of the folder, but also the more permanent IPNS URL of the node.

**Comment by hacdias** [comment]
@andrasfuchs what do you mean by "Public folder"?

**Comment by andrasfuchs** [comment]
@hacdias Ahh, sorry, I think I made a mistake when I supposed that my "Public" folder was created by the node by default during its installation. I probably forgot that I created that manually a year ago or so when I installed IPFS desktop for the first time.

Anyway, my suggestion changes a little then, but still, it would be nice, if I could select one folder that would be handled by IPFS desktop as the public folder of the node, and the IPNS updates were automated when the contents of that folder changes.

What do you think?

**Comment by hacdias** [comment]
Hey! I know there is a discussion about simplifying the process of publishing websites aka using IPNS. ~I can't find the issue now~ Here it is:

https://github.com/ipfs/ipfs-gui/issues/69

I'll just update the title of this issue!

**Comment by jessicaschilling** [comment]
Closing this issue in favor of the larger "publishing websites" discussion at https://github.com/ipfs/ipfs-gui/issues/77.
