### ISSUE TITLE
Unable to add IPFS command line tools

### ISSUE THREAD

**Issue by TriMoon** [ipfs-shipyard/ipfs-desktop#1039]
When i click the checkbox in the desktop-UI labeled "IPFS command line tools", i get a popup asking for authentication from PolicyKit to run `/usr/bin/env`.
When i enter the correct password, a second popup gets displayed:
![Error IPFS comandline tools](https://user-images.githubusercontent.com/1723378/63222471-0217d800-c1b1-11e9-973c-51f910a0eb39.png)
My account is part of the sudo group, and root has a password set...

```console
OS: Ubuntu 19.04 x86_64 
Model: Manual build Rev:xxx 
Mainboard: X99-PRO/USB 3.1 Rev 1.xx (ASUSTeK COMPUTER INC.) 
Bios: 2017-08-10 AMI Ver:3801 
Kernel: 5.0.0-25-generic 
Uptime: 3 days, 2 hours 
Packages: 2485 (dpkg), 2 (snap) 
Shell: zsh 5.5.1 
Resolution: 1680x1050 @ 59.88Hz 
DE: KDE 
WM: KWin 
Theme: Breeze Dark [KDE] 
Icons: breeze-dark [KDE] 
Terminal: xterm 
Font: [KDE] 
Locale: en_US.UTF-8 
Memory: 4050MiB / 32075MiB [37m[-==============[37m] 
CPU: i7-5820K (12) @ 4.0GHz [46.0°C] 
GPU: GeForce GTX 1080 Ti 
GPU: GeForce 210 
GPU Driver: NVIDIA 418.56 
CPU Usage: 5% 
Disk (/): 12G / 146G (9%) 
Disk (home): 50G / 63G (84%) 
Disk (efi): 7.7M / 511M (2%) 
Local IP: 192.168.0.2 
```

**Comment by hacdias** [comment]
@TriMoon hello! Sorry for that! Could you let me know which version of IPFS Desktop you're using? Please try the newest beta version: https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.9.0-beta.2

**Comment by TriMoon** [comment]
Using: `ipfs-desktop-0.8.0-linux-x86_64.AppImage`
- ipfs-desktop: `0.8.0`
- go-ipfs: `0.4.21`

ill try `ipfs-desktop-0.9.0-beta.2-linux-x86_64.AppImage` soon...

**Comment by hacdias** [comment]
Okay, I now see you're using Ubuntu. Can I ask you something? Try using the `.deb` package and not `.AppImage` to see if it works.

**Comment by hacdias** [comment]
Could you please try with the latest release?

**Comment by hacdias** [comment]
Since I've got no reply, I will close this. Feel free to open a new issue or reopen this one!
