### ISSUE TITLE
Adding files fails if not enough space on primary drive

### ISSUE THREAD

**Issue by andrasfuchs** [ipfs-shipyard/ipfs-desktop#1041]
I use ipfs-desktop 0.8.0.0 (and go-ipfs 0.4.21) on Windows 10. I configured IPFS to use a secondary partition for the blocks (drive N in my case). IPFS is installed on my primary drive, C. I created this configuration by editing the `config.json` of IPFS Desktop and its `ipfsConfig / path` value.

I tried to add a bigger file (3.3 GB). IPFS first tried to create multiple files in the `%APPDATA%/IPFS Desktop/blob_storage`. I didn't expect this, because I set the storage path to the drive N. 
When I didn't have enough space on my drive C for those files, the adding failed with a general error message, but I didn't get an exact error explaining the reason.

It would be good to check the space on both the primary drive (with the blob_storage folder, C in my case) and the drive containing the blocks (N in my case) if they have enough space for the adding _before_ starting the operation, and let the user know if they need to make more space to continue.

**Comment by hacdias** [comment]
Hmm... I believe `blob_storage` might be some kind of temporary cache. I need to investigate this because nowhere in our code, we choose a "temporary cache" to store blobs...

**Comment by andrasfuchs** [comment]
I think you are right, the `blob_storage` looks like a temporary folder.

Today I found a related problem to this: I tried to add the 3.3 GB file while my blocks were just around 30 GB in size. I had 10+ GB free space on both drives. 
The temporary files were created successfully on drive C and I could tell that there were some disk activity in the blocks folder on drive N, but it finally failed without a detailed error message. The temporary files were not deleted afterwards, they are still there on my primary drive.

I suspect that it was because I reached the 30 GB limit on my storage, but I'm not 100% sure, because my ipfs-desktop has a 40GB setting of `StorageMax`. So there might be a bug there too (I read it somewhere that there were problems using this setting before.)

**Comment by hacdias** [comment]
@andrasfuchs could you check the errors log on `%appdata%/IPFS Desktop` for me please?

> I suspect that it was because I reached the 30 GB limit on my storage, but I'm not 100% sure, because my ipfs-desktop has a 40GB setting of StorageMax.

The `StorageMax` is just an indicator for the Garbage Collector to not let the repository exceed that size, but it can.

**Comment by andrasfuchs** [comment]
@hacdias Strange!

I got this `combined.log` (I tried to drag-and-drop the 3.3 GB file I wanted to add):

> 2019-08-21T07:15:25.826Z error: net::ERR_CONNECTION_TIMED_OUT
> 2019-08-21T07:15:26.406Z info: [web ui] window ready
> 2019-08-21T07:15:26.406Z info: [tray] starting
> 2019-08-21T07:15:26.522Z info: [tray] started
> 2019-08-21T07:15:26.523Z info: [ipfsd] starting daemon
> 2019-08-21T07:15:27.693Z info: [daemon] cleanup: started
> 2019-08-21T07:15:27.694Z info: [daemon] cleanup: ipfs repo fsck n:/Blockchains/ipfs/
> 2019-08-21T07:15:27.743Z info: [daemon] cleanup: completed
> 2019-08-21T07:15:32.848Z info: [ipfsd] daemon started
> 2019-08-21T07:15:32.900Z info: [hash download] shortcut disabled
> 2019-08-21T07:15:32.900Z info: [screenshot] shortcut disabled
> 2019-08-21T07:15:32.900Z info: [ipfs on path] no action taken
> 2019-08-21T07:15:32.920Z info: [launch on startup] enabled
> 2019-08-21T07:15:38.435Z info: [web ui] navigate to /files

And then, I used the "+Add" button to try to add it, but the `combined.log` remained the same, no new entries were written.

In both cases my disk and memory usage went up for 90 seconds or so and the temporary files on the `blob_storage` were not removed.

![image](https://user-images.githubusercontent.com/910321/63411695-611a5e80-c3f6-11e9-874f-d7184acff439.png)

The file was not added in the end.

**Comment by andrasfuchs** [comment]
I still couldn't find the solution to this problem, so I still can't add that file. 
Is there a way to have more detailed logs in ipfs-desktop?

**Comment by hacdias** [comment]
The logs we have are the exact errors reported by `go-ipfs` itself. I still don't know why we have this error either...

**Comment by andrasfuchs** [comment]
After I run `ipfs repo gc` my blocks folder were 27.3 GB is size. 

I added a 3.3 GB file with `ipfs add <file>` and the blocks became 30.6 GB, so everything looked good when I used `go-ipfs` directly.

Then I deleted the file using the `ipfs files rm <file>` command.

I run the `ipfs repo gc` once again, but the blocks folder stayed 30.6 GB, I don't know why, I expected it to shrink by 3.3 GB. 

Anyway, after all this I tried to add the file again in `ipfs-desktop` with the "+Add" button. It started to use the disk a lot, and after a while the file appeared in the folder, so it was successful. 

My problem seems to be solved for now, I'm just curious: is there a way to turn on the logging of the exact ipfs commands that `ipfs-desktop` executes on the daemon?

**Comment by hacdias** [comment]
> My problem seems to be solved for now

That's great! Although, I will leave this issue open until I can find a way to make sure this doesn't happen.

> is there a way to turn on the logging of the exact ipfs commands that ipfs-desktop executes on the daemon?

No, unfortunately no. We're using [`js-ipfs-http-client`](https://github.com/ipfs/js-ipfs-http-client) which then makes requests to the IPFS HTTP API. The paths of the API could be easily mapped to strict commands, although that's not a current feature of ours.

**Comment by lidel** [comment]
> I added a 3.3 GB file with `ipfs add <file>` and the blocks became 30.6 GB, so everything looked good when I used `go-ipfs` directly.
> 
> Then I deleted the file using the `ipfs files rm <file>` command.
> 
> I run the `ipfs repo gc` once again, but the blocks folder stayed 30.6 GB, I don't know why, I expected it to shrink by 3.3 GB.

When you use CLI, the `ipfs add` pins added data, so it is protected against GC. 
You can remove pins via `ipfs pin rm $CID`, or disable automatic pinning by executing `ipfs add --pin=false`

ps. adding big files should be MUCH faster in [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)
