### ISSUE TITLE
Cannot start IPFS desktop: The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. 

### ISSUE THREAD

**Issue by Bernd-L** [ipfs-shipyard/ipfs-desktop#1044]
I'm running Manjaro Linux (based on Arch) and tried to install IPFS Desktop from source after the official (`.AppImage`) version didn't work.

But to my surprise, I got the same error.

I ran
- Git clone
- `npm install`
- `npm start`
  - The output of which is displayed below

```
[bernd@bernd-pc ipfs-desktop]$ npm start

> ipfs-desktop@0.9.0-beta.2 start /home/bernd/Build/ipfs-desktop
> cross-env NODE_ENV=development electron -r @babel/register src/index.js

[18816:0820/141831.072284:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/bernd/Build/ipfs-desktop/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
```

Please note that I am also using `nvm`:
```
[bernd@bernd-pc ~]$ nvm ls
->     v11.15.0
        v12.8.0
         system
default -> 11.15.0 (-> v11.15.0)
node -> stable (-> v12.8.0) (default)
stable -> 12.8 (-> v12.8.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.16.2 (-> N/A)
```

Why won't IPFS Desktop start?
And what does the error mean anyways?

**Comment by hacdias** [comment]
I see you're using Manjaro, which is based on Arch, and that might be the issue. Please take a look at https://github.com/electron/electron/issues/17972

**Comment by hacdias** [comment]
Just out of curiosity: are you using any other Electron apps?

**Comment by Bernd-L** [comment]
> Just out of curiosity: are you using any other Electron apps?

I am using VS Code (from the Manjaro repos) and Discord (from the AUR), which both work fine for me.

**Comment by hacdias** [comment]
People have reported me that the .AppImage from 0.9.0-beta.3 is working. I'll close this now. Please feel free to re-open if the issue persists.

**Comment by hacdias** [comment]
Ugh, oh... Using Arch or some Arch-based distro, right?

**Comment by jacklund** [comment]
Nope, Debian buster, actually (I misspoke before when I said it was stretch).

**Comment by jacklund** [comment]
As another data point, when I `sudo chmod 4755 /opt/IPFS\ Desktop/chrome-sandbox` and then run it, I get:

```
% /opt/IPFS\ Desktop/ipfs-desktop  
zsh: trace trap  /opt/IPFS\ Desktop/ipfs-desktop
```

**Comment by ZeroAurora** [comment]
I'm running into this as well in Debian testing

**Comment by cchris-org** [comment]
ipfs-desktop-0.10.2-linux-x86_64.AppImage
Linux Mint LMDE (debian stretch)
Same here ..

**Comment by Mikaela** [comment]
Workaround seems to be [enabling usernamespaces](https://superuser.com/a/1122977) and receiving the security issues from it https://github.com/brave/brave-browser/issues/3420. If I understand the [Arch Wiki security page](https://wiki.archlinux.org/index.php/security#Sandboxing_applications) correctly, the same should work on Arch (and likely deriatives).

Adjusting that a bit:

```
echo 'kernel.unprivileged_userns_clone=1' | sudo tee /etc/sysctl.d/00-local-userns.conf
sudo sysctl -p --system
```

I ran into this on my laptop while not on family PC, both running Debian 10 and the difference is that on the family PC I have ran Brave and thus done that and after copying the config on the laptop that wasn't working, IPFS Desktop started working, but I don't think this is a real solution as you can see from the Brave issue.

**Comment by lidel** [comment]
FYI [v0.10.4](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.10.4) shipfs with updated `ipfs-desktop.desktop` manifest which starts ipfs-desktop with `--no-sandbox` by default, which fixes startup via GUI shortcut on Debian 10 without lowering security system-wide.

Running `ipfs-desktop --no-sandbox` is so far the most robus way of making it work on all distrons that works without root access. In case someone is interested in technical details, I wrote some details in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1362#issuecomment-596857282.
