### ISSUE TITLE
Record Screen Permissions on macOS Catalina

### ISSUE THREAD

**Issue by shedali** [ipfs-shipyard/ipfs-desktop#1053]
Just a heads up that Catalina 10.15 Beta (19A536g) is requesting permissions which many may not feel comfortable in permitting.

![image](https://user-images.githubusercontent.com/64362/63680212-0b292a80-c7eb-11e9-87c1-2789fb9cb5d2.png)

**Comment by hacdias** [comment]
Hello @shedali! Thanks for letting me know that. That's because of the Screenshot feature I believe. Prior to Catalina, macOS wouldn't ask for permission to record the screen. I'll investigate to make sure it that's the reason.
