### ISSUE TITLE
A gaggle of IPFS Desktops in my Login Items on Mac OS X

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ipfs-desktop#1058]
<img width="449" alt="Screen Shot 2019-08-26 at 4 50 05 PM" src="https://user-images.githubusercontent.com/50103/63730815-b3f27c80-c821-11e9-8666-eb63aeabf12a.png">

**Comment by hacdias** [comment]
@autonome that's weird. I only have one. And I believe there should be only one. Is it possible to see more info about each login item you have there?

**Comment by autonome** [comment]
Not from the UI. Haven't dug deeper to check where all these are kept by the OS, like some plist file or something like that.

**Comment by hacdias** [comment]
Will take a look as soon as I can!

**Comment by hacdias** [comment]
@autonome I am looking now at the `auto-launch` code and I think I know what your problem is: have you ever run IPFS Desktop from multiple locations? If so, that might be the issue you have there... generating an entry for each specific location. I can't see other reason, nor reproduce that bug.

**Comment by autonome** [comment]
Not that I know of... maybe running from source at some point? I just
checked, and still had four in the list. I removed them all, will check and
see if they reappear 😂

**Comment by hacdias** [comment]
@autonome I'm closing this for now, but if you start getting more, please let me know. I believe that auto launch was enabled **on development** some time in the past, but I've now prevented that from happening. That might have been it.
