### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [ipfs-shipyard/ipfs-desktop#1060]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by hacdias** [comment]
Hey @traverseda! Thanks for the issue. I believe we depend on some package that depends on `funding`. It seems feross [ended the experiment](https://feross.org/funding-experiment-recap/).

> It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

Right now, I don't mind if any advertisement shows in the build logs. I believe that it's for the good of open source, it's good to go. Perhaps whoever depends on this package, will remove that dependency after feross announcement.

**Comment by bertrandfalguiere** [comment]
Seems that the "standard" library was the culprit.
Funding was removed: https://github.com/ipfs-shipyard/ipfs-desktop/pull/1062 (see changelog)
In this commit: https://github.com/standard/standard/commit/2ad67c0c8fdaad6253500ce078f711aa176a5e5d

**Comment by hacdias** [comment]
Thanks for noticing @bertrandfalguiere! Closing
