### ISSUE TITLE
More precise affordance to drag IPFS webUI window around

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ipfs-desktop#1066]
![image](https://user-images.githubusercontent.com/618519/64048032-69c11200-cb25-11e9-98ea-c7620502b8a2.png)

When I want to move around the webUI window, I usually try to click and hold anywhere in the light teal area at the top of the window to move it - however only the top 1/3 of that teal area is actually able to drag the window, moving my cursor while clicking anywhere else will highlight text in the window. Similarly, if I click in the upper 1/2 of the white text entry box to explore a hash, I don't focus the text entry area but start dragging the window. Can we do a better job highlighting the affordance to drag this window effectively?

I'm on MacOS Mojave 10.14.4

**Comment by hacdias** [comment]
Hey @momack2! Thanks for noticing this. I see two options to fix this:

1. Re-add the Window frame:

<img width="1255" alt="Screenshot 2019-08-31 at 21 10 51" src="https://user-images.githubusercontent.com/5447088/64068724-e510e980-cc33-11e9-8d39-847577c29e54.png">

2. Add some padding to the top.

Although neither of those options is fixing the non-clickable area in the top, which is odd. I'll need to investigate more about that bug.

**Comment by momack2** [comment]
While I agree it looks cool without the window frame - re-adding that would solve my problem since I'd know where to click to drag. 

If you look at the way slack/zoom do it, everything in the header has the drag/drop affordance except explicitly clickable buttons/fields. I'd *prefer* a solution like that.

**Comment by hacdias** [comment]
@momack2 sorry for not having updated this: please see https://github.com/ipfs-shipyard/ipfs-desktop/pull/1071! You'll love it!

**Comment by momack2** [comment]
woohoo! thanks!
