### ISSUE TITLE
An error occurred when trying to connect.

### ISSUE THREAD

**Issue by shaswata56** [ipfs-shipyard/ipfs-desktop#1086]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by hacdias** [comment]
Which version of Windows do you have? How come you don't have powershell on your system?

**Comment by hacdias** [comment]
Anyway and just to make sure: that error does not prevent the execution, right?

**Comment by shaswata56** [comment]
@hacdias , yeah. It didn't prevent execution.

**Comment by hacdias** [comment]
Also, could you see my previous comment, please?

**Comment by shaswata56** [comment]
@hacdias ,os: windows 10, of course I have powershell. CMD is crap, so powershell is the only way to work!!

**Comment by hacdias** [comment]
Is it on the PATH? I haven't been able to reproduce this on any Windows 10 machine I've tried on...

**Comment by shaswata56** [comment]
> Is it on the PATH? I haven't been able to reproduce this on any Windows 10 machine I've tried on...

Currently I'm in Manjaro, I'm replying soon after checking my PATH.

**Comment by hacdias** [comment]
Anyhow, just to let more information here:

1. By default we add `ipfs` to the PATH if it not exists. For that, on Windows, we use PowerShell.
2. I will hide this error when it's caused by an automatic action. If the user decides to check this option on the settings and it fails, they'll get an error message. Otherwise, it will fail silently.

**Comment by shaswata56** [comment]
> > Is it on the PATH? I haven't been able to reproduce this on any Windows 10 machine I've tried on...
> 
> Currently I'm in Manjaro, I'm replying soon after checking my PATH.

Found it! Actually,  C:\Windows\System32 is not in my PATH.



> Anyhow, just to let more information here:
> 
> 1. By default we add `ipfs` to the PATH if it not exists. For that, on Windows, we use PowerShell.
> 2. I will hide this error when it's caused by an automatic action. If the user decides to check this option on the settings and it fails, they'll get an error message. Otherwise, it will fail silently.

Idea(2) is good. It'll not gather useless bug reports.

**Comment by hacdias** [comment]
> Found it! Actually, C:\Windows\System32 is not in my PATH.

It's a bit odd not to have `C:\Windows\System32` though. I don't know why that might have happened. Perhaps a corrupt PATH.

> Idea(2) is good. It'll not gather useless bug reports.

That's what I'll do 😃

**Comment by shaswata56** [comment]
> > Found it! Actually, C:\Windows\System32 is not in my PATH.
> 
> It's a bit odd not to have `C:\Windows\System32` though. I don't know why that might have happened. Perhaps a corrupt PATH.
> 
> > Idea(2) is good. It'll not gather useless bug reports.
> 
> That's what I'll do 😃

Mistakenly I've cleared PATH from my system a week ago. Then rewrote the path. But I didn't notice that system32 was missing from there.
