### ISSUE TITLE
Works for sometime and then can no longer add files from ipfs

### ISSUE THREAD

**Issue by steakknife** [ipfs-shipyard/ipfs-desktop#1097]
- Version: 0.9.0 (desktop), 0.4.22 (go-ipfs)
- OS: macOS 10.14.6 (18G95)

Adding files from ipfs initially works, but after a nondeterministic amount of time and uses, adding files using the Add button appears to do nothing.

Restarted and reinstalled multiple times, including blowing away `~/.ipfs/` and `~/.ipfs-desktop/`  and ` ~/Library/Application Support/IPFS Desktop/`.

Also, the Files section will periodically refresh and hang forever.

**Comment by hacdias** [comment]
Hey @steakknife,

I'm sorry for hearing you're having some troubles with IPFS Desktop!

> Adding files from ipfs initially works, but after a nondeterministic amount of time and uses, adding files using the Add button appears to do nothing.

Hmm... Will try to reproduce.

> Restarted and reinstalled multiple times, including blowing away ~/.ipfs/ and ~/.ipfs-desktop/ and ~/Library/Application Support/IPFS Desktop/.

Generally any problem should go away just by restarting the app. Didn't it work?

> Also, the Files section will periodically refresh and hang forever.

Will try to reproduce too.

**Comment by lidel** [comment]
We revamped the way file import works when HTTP API is used (eg. in IPFS Desktop) adding many files, or adding a big file (4GB+) should work much better now.

Please upgrade to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2).
