### ISSUE TITLE
Adding files over 1GB fails with 'Timeout error'

### ISSUE THREAD

**Issue by enOehTsIsihT** [ipfs-shipyard/ipfs-desktop#1122]
- OS : win7 X64

- ipfs-desktop version : 0.92

If file bigger than 1GB, ipfs-desktop can't add file.

**Comment by lidel** [comment]
Fixed in the latest ipfs-webui, please upgrade ipfs-desktop to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2) :robot:
