### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ipfs-desktop#1129]
Currently it says "Menubar IPFS Application", which is factually correct but not very exciting. Actually, is it factually correct for all OSes? Windows seems like that'd be called something different, by looking at the screenshot. It's been a while since I've used Windows 😅

Maybe something like:

> An unobtrusive and user-friendly desktop application for IPFS on Windows, Mac and Linux. https://ipfs.io"

???

**Comment by hacdias** [comment]
Completely agreed! Just stole your sentence :P
