### ISSUE TITLE
UI: Not apparent that "Download Hash" uses clipboard

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/ipfs-desktop#1135]
I am glad to see a native UI within the Finder and was curious as to the purpose of the "Download Hash" entry. When I select it, I am told the hash in my clipboard is not valid. I was not aware that the clipboard was going to be used when selecting this menu item. I anticipated some UI to appear allowing me to somehow specify the hash as input.

It would be helpful if the underlying function of this menu option were more apparent without having to select the option and being told of invalid input without knowing the source of the input. Something either indicative that the clipboard will be used or providing some other UI for the user to specify a source of the hash.

ipfs-desktop 0.9.2
macOS 10.14.6

**Comment by hacdias** [comment]
Thanks for the heads up @machawk1. We should definitely add some information. Perhaps change to 'Download CID from clipboard' or add a little information below... I'll try that out

**Comment by hacdias** [comment]
I tried adding additional text below but it doesn't look great... Other suggestion could be just changing the copy to something like 'Download from Clipboard'. However, that would make the menu much larger. Wdyt?

![image](https://user-images.githubusercontent.com/5447088/65838719-0bdb4200-e2fe-11e9-8033-492ef414bbe0.png)

**Comment by machawk1** [comment]
I agree, the long string in the menu item would be visually verbose.

Have you considered _not_ using the clipboard for this functionality by default or rather, giving the user an option to specify the hash after selecting this menu item?

For example, the menu item could say "Download..." and when selected, display a modal with a text box (potentially pre-populated with the clipboard contents if applicable) providing the ability for the user to provide input (e.g., the hash).

Otherwise, neither "Download from Clipboard", "Download CID from Clipboard", nor the current "Download Hash" seem to capture the implemented functionality. Isn't ipfs-desktop download the payload _at_ this hash/CID, not the hash itself? For example, if the identifier was a URI instead of a hash, one would not say "Download URI from clipboard", but something more akin to "Download webpage".
