### ISSUE TITLE
No 64 bits binaries

### ISSUE THREAD

**Issue by Lazerbeak12345** [ipfs-shipyard/ipfs-desktop#1150]
Hi, I noticed two packaging issues:

- [ ] The rpm, due to signage issues, doesn't work on Fedora 30, yet. (I can provide console output if asked, but with my experience, the issue is just that my computer doesn't recognize the key you signed the `.rpm` with and needs it imported. A guide for this may be a good idea?)
- [ ] There isn't an x86_64 snap yet. (I may be able to either build or guineapig this, as this is my arch)

**Comment by hacdias** [comment]
Hello @Lazerbeak12345,

About the `.rpm` issue, please try using another package. Right now, Electron Builder does not support signing rpm packages. However, if you would like to help with it, it will certainly be appreciated!!

There is a 64 bit snap: [ipfs-desktop-0.9.3-linux-amd64.snap](https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.9.3/ipfs-desktop-0.9.3-linux-amd64.snap). What we don't have is 32 bit binaries.

**Comment by Lazerbeak12345** [comment]
When I run the command `snap install ipfs-desktop-0.9.3-linux-amd64.snap` it outputs this:

```
error: cannot find signatures with metadata for snap "ipfs-desktop-0.9.3-linux-amd64.snap"
```

I take this to mean that electron builder doesn't support signing snaps either?

**Comment by hacdias** [comment]
It does. You should install it with `--dangerous` flag. I'm thinking about publishing to the store on the next release so you won't have that issue.

**Comment by Lazerbeak12345** [comment]
It shouldn't be too hard to sign the rpm after the build.

**Comment by Lazerbeak12345** [comment]
http://ftp.rpm.org/max-rpm/s1-rpm-pgp-signing-packages.html#:~:targetText=%2D%2Dsign%20%E2%80%94%20Sign%20a%20Package,not%2C%20the%20build%20stops%20immediately.
