### ISSUE TITLE
Windows 10 v0.9.4 installs but doesn't launch

### ISSUE THREAD

**Issue by cadayton** [ipfs-shipyard/ipfs-desktop#1174]
IPFS command line is installed in a non-standard location.  The IPFS daemon executes successfully along with the Web UI.

Not seeing any events or log file entries to reference to provide more details on why the IPFS Desktop isn't launching.

**Comment by hacdias** [comment]
Hello @cadayton! Thanks for your report!

I just installed 0.9.4 on a fresh Windows 10 install and it works with no issues:

![image](https://user-images.githubusercontent.com/5447088/66274996-4acc4300-e87c-11e9-8f60-acb3c820cdf0.png)

What do you mean? What is not working?

> IPFS command line is installed in a non-standard location.

We add the CLI tools to the PATH as most applications on Windows do. There is no standard location for Windows to put binary files (as opposed to Unix where `/usr/local/bin` is the default).

**Comment by cadayton** [comment]
When I double click on the desktop icon the application doesn't start.  Also tried running the .exe file directly too.

Craig Dayton
cadayton@protonmail.com
360-466-8778
paypal.me/CraigDayton

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cadayton** [comment]
My bad.  I didn't notice IPFS desktop was running in the system tray.

**Comment by hacdias** [comment]
No problem at all. It's good you figured out what was wrong. We are actually thinking about starting to open the window the first time we double-click the icon: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1153#issuecomment-536587390
