### ISSUE TITLE
Monochrome menubar item on macOS

### ISSUE THREAD

**Issue by rex4539** [ipfs-shipyard/ipfs-desktop#1192]
The menubar item on macOS is colored, which is highly unpopular for Mac users.

The default for menubar items for macOS is monochrome.

Some apps have the option in Preferences to choose between monochrome and color but the default is always monochrome.

**Comment by hacdias** [comment]
Hey @rex4539! That is actually something that we’ve discussed before and I’d really like to see some icons made for macOS. I’m just closing this in favor of #956. 

If you’re willing to help, I will gladly accept suggestions for which icons we should use. Please take a look at the issue above to know what the current status is and the issues we’ve found when trying out some icons.
