### ISSUE TITLE
High CPU/GPU usage when ipfs daemon is running

### ISSUE THREAD

**Issue by rex4539** [ipfs-shipyard/ipfs-desktop#1196]
ipfs-desktop 0.9.5

Steps:
Keep IPFS-desktop running in the background (menu item not open) with ipfs daemon running.

What happened:
High CPU/GPU usage. This forces laptop fans to work and eats battery like crazy.

<img width="1184" alt="Screenshot 2019-10-16 at 14 16 00" src="https://user-images.githubusercontent.com/227442/66914902-72f83680-f020-11e9-93d2-af7721d5a0d1.png">

Expected result:
Low CPU/GPU usage when the app is in the background (menu item not open).

Notes:
When ipfs daemon is stopped then the CPU/GPU usage is low (as it should). Is there a particular reason the app consumes so much CPU/GPU when the daemon is running (since the app window is NOT open)?

**Comment by lidel** [comment]
Most likely (high GPU) suggests it is either Peers screen (world map) or Status (the canvas with `Bandwidth over time`) being rendered in the background:

@hacdias try creating an empty route in webui, and switch to it every time IPFS Desktop is minimized. This should remove the overhead of updating canvas when not visible.
