### ISSUE TITLE
Desktop crash this morning

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ipfs-desktop#1209]
Please describe what you were doing when this error happened. --> Nothing, it was running in the background

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.9.0
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139

**Error**

```
Error: net::ERR_NETWORK_IO_SUSPENDED
```

**Comment by hacdias** [comment]
Thanks for reporting that @momack2. Unfortunately, I'm not aware of this network issues with the current release, but I'll further investigate.

By the way, can you update to [0.9.7](https://github.com/ipfs-shipyard/ipfs-desktop/releases)? Haven't you been receiving update notifications?

Also, are you behind any proxy and/or VPN when this occurred?

**Comment by momack2** [comment]
Updated! Not behind any proxy/VPN.

**Comment by hacdias** [comment]
Close in favor of #1267
