### ISSUE TITLE
Suggestion: Display information about new features when update is available

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-desktop#1210]
I'd love the "update available" notification to also display a list of new features and a button saying "Install now" or "Install later".

Just an idea!

**Comment by hacdias** [comment]
I like it too! I will see what can be done (I know it is possible to get the release notes easily with the current system). However, I mostly wonder what would happen with internationalization... And the release notes can be too long for notifications. Anyways, I'll try it out and see how it looks.

**Comment by jessicaschilling** [comment]
This also ties in with #1378, in which available updates aren't always visible to users who have notifications disabled. It's lower-priority work than fixing that, but could likely be easily rolled in as related effort.

**Comment by andrew** [comment]
I think this one can be closed now that #1414 is merged
