### ISSUE TITLE
Display progress status while adding files (Desktop)

### ISSUE THREAD

**Issue by Kuurusch** [ipfs-shipyard/ipfs-desktop#1217]
Would be cool to have a progress-bare somehow when adding new file over ipfs-desktop to ipfs! I've just tried it with a 20GB file and it seemed, that it didn't worked but with now progress-bar or any message I couldn't be sure, that it realy terminated.

**Comment by jessicaschilling** [comment]
Note: This is a duplicate, functionally, of https://github.com/ipfs-shipyard/ipfs-webui/issues/1206 for webUI. Work on these should happen in tandem.

**Comment by jessicaschilling** [comment]
Closing this issue while we start work on this in Web UI - please see https://github.com/ipfs-shipyard/ipfs-webui/issues/1206. (Any work in Web UI will reflect itself in Desktop, since the source is the same.) @Kuurusch -- please feel free to follow along there!
