### ISSUE TITLE
drag-n-drop doesn't auto c&p the ipfs cid to my clipboard

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-desktop#1218]
It would be nice if when I drag and drop something into the IPFS icon, it would put the ipfs url (ipfs.io/ipfs/CID) to my clipboard so that I can paste it right away.

Note: This was a feature of a earlier version of ipfs desktop that I guess it got lost in the big refactor.

**Comment by daviddias** [comment]
Thank you @hacdias! You are a machine! :D

**Comment by hacdias** [comment]
Soon, a new patch release will be there!
