### ISSUE TITLE
Change default install location for Win

### ISSUE THREAD

**Issue by papagunit** [ipfs-shipyard/ipfs-desktop#1229]
Hi there,

It's not apparent, but is it possible to change the default installation location? I don't have anymore space on C and need it on a different drive.

**Comment by hacdias** [comment]
@papagunit right now, it is not possible. It was in times, when our installer was a bit more complex.

Basically, we could revert to the "old style" installer which is not click once to install. You'd need to go through a few 'Next's but then you could choose the path.

Maybe useful: IPFS Desktop's installer is a NSIS installer. If there's any flag you could pass to a NSIS installer to change the installation path, then you might be able to do so with our installer. I'm not aware of any.

---

The biggest question here for the installer is: simplicity vs customization?

**Comment by hacdias** [comment]
Possible now!

**Comment by papagunit** [comment]
Christmas came early!
