### ISSUE TITLE
IPFS failing to start on linux

### ISSUE THREAD

**Issue by Lazerbeak12345** [ipfs-shipyard/ipfs-desktop#1249]
When I compile from source on the master branch, the app opens to a blank screen. I just tested commit ba2c88b57184d1bc6a45f8edfabba096c805d64c but I recall ones as far back as around v0.9 ish had this issue as well.

I'm aware of issue #1244, but upon further inspection, I don't believe that this is the cause for the issue I have found.

Here's a screenshot containing all error messages in the debugger tool:

![Screenshot_20191115_132946](https://user-images.githubusercontent.com/22641188/68973959-c048fe80-07ac-11ea-943c-204beeef52cd.png)

My build environment is Fedora 31, npm 6.12.1 (removed `node_modules` dir before `npm i` and it still failed). Runtime is the same, running KDE Plasma 5.16.5.

Please tell me if you need any more info, and great work so far on the project!

**Comment by Lazerbeak12345** [comment]
Oh, I would like to note that it does, in fact still start the ipfs daemon

**Comment by Lazerbeak12345** [comment]
Oops. Closed it. Still broken.

**Comment by hacdias** [comment]
Hey @Lazerbeak12345! Could you try running:

```
npm run clean:webui && npm run build:webui
```

please?

It seems to be something related to the Web UI. If that does not solve the problem, I will try on a VM as soon as I can!

**Comment by Lazerbeak12345** [comment]
Simply running that and then clicking "status" on the menu didn't work. I'll update you after a re-build.

**Comment by Lazerbeak12345** [comment]
Oh, and it was the exact same error, just so you are aware. (And I didn't do a git pull either)

**Comment by Lazerbeak12345** [comment]
Great news! After running that command earlier, followed by running `rm -r node_modules && npm install && npm run build && npm run start` it worked!

**Comment by Lazerbeak12345** [comment]
I personally feel like this issue is resolved, but I'll leave it up to you to close it @hacdias

**Comment by hacdias** [comment]
Thanks!
