### ISSUE TITLE
Booted computer with IPFS set to start at boot

### ISSUE THREAD

**Issue by PowerMellow** [ipfs-shipyard/ipfs-desktop#1269]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by hacdias** [comment]
Thanks for this @PowerMellow. I'm just closing in favour of #1267.
