### ISSUE TITLE
Window items not clickable on first click

### ISSUE THREAD

**Issue by rex4539** [ipfs-shipyard/ipfs-desktop#1272]
ipfs-desktop 0.10.2
macOS 10.15.2

Reproducibility: always

Steps:
1. Launch ipfs-desktop
2. Click on the menu item icon -> Status
3. Click on the Files tab.

What happened:
The tab is highlighted but the view doesn't change.

Expected result:
The tab is highlighted and the view changes.

Note:
Works on second click.

**Comment by hacdias** [comment]
@rex4539 thanks for this. It is actually a known bug (#762). I'm closing this as a duplicate. Unfortunately, I haven't been able to find why is it happening! And it seems to be windows only...
