### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by hill-ming** [ipfs-shipyard/ipfs-desktop#1275]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.10.1
- **Electron Version**: 7.1.2
- **Chrome Version**: 78.0.3904.113

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by hacdias** [comment]
Could you try upgrading to 0.10.2? I think we fixed that error on that version :)
