### ISSUE TITLE
Unable to add folders via Files screen

### ISSUE THREAD

**Issue by thimper** [ipfs-shipyard/ipfs-desktop#1287]
macos : 10.13.6  

Adding folders has no effect。

Using the command line ipfs add-r folders is fine

**Comment by autonome** [comment]
Thanks for reporting!

Confirmed on Mac OS X 10.14.6 with IPFS Desktop 0.10.2

STR:

* Open web UI to files page
* Click [+Add]
* Select "Folder"
* Choose a folder

Expected: Folder is added and is visible in UI

Actual: Nothing happens

@hacdias or @lidel any ideas what caused regression?

**Comment by hacdias** [comment]
Unfortunately, I have no idea and there are no errors reported in the console. In the meanwhile, you can just drag'n'drop directories to the menubar icon! That should work

**Comment by lidel** [comment]
Just for the record, this does not not seem to be limited to Electron.
IIUC the same problem was confirmed on Google Chrome Canary.
Tracked in https://github.com/ipfs-shipyard/ipfs-webui/issues/1367#issuecomment-567924016

**Comment by lidel** [comment]
Ok I think there are two bugs at play here. Dumping my notes for future reference.

I tested on Linux with Electron and Firefox and:

- if webui is opened in **Electron** (ipfs-desktop)
  - :anger: adding folder does not work via button (no error in Console)
  - :anger: adding folder does not work via drag&drop  ([error](https://user-images.githubusercontent.com/157609/73474405-bb98ed00-438e-11ea-9b65-b20c7fc7a7e3.png))
- if webui is opened in **Firefox**
  - :angel: adding folder WORKS via button
  - :anger: adding folder does not work via drag&drop ([error](https://user-images.githubusercontent.com/157609/73474621-0e72a480-438f-11ea-8ea0-5b8cabcf0b51.png))

- if webui is opened in **Brave(Chromium)**
  - :angel: adding folder WORKS via button
  - :anger: adding folder does not work via drag&drop ([error](https://user-images.githubusercontent.com/157609/73474846-6f01e180-438f-11ea-8d27-951cd7bd6b01.png))

**Comment by lidel** [comment]
I believe https://github.com/ipfs-shipyard/ipfs-webui/pull/1468 fixes all/most of drag&drop issues described in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1287#issuecomment-580368657, thank you @rafaelramalho19   :-) 

When we release new webui and switch ipfs-desktop to the new version we can check if this issue can be closed (or comment  what remains to be fixed).

**Comment by lidel** [comment]
@rafaelramalho19 FYSA I retested with webui v2.8.0 (PR #1457) on Linux with Electron/Firefox/Chromium, and:

- if webui is opened in **Electron** (ipfs-desktop)
  - :anger: adding folder does not work via button (no error in Console)
  - :angel: adding folder WORKS via drag&drop 
  - :angel: adding single file WORKS via drag&drop 
- if webui is opened in **Firefox**
  - :angel: adding folder WORKS via button
  - :angel: adding folder WORKS via drag&drop 
- if webui is opened in **Brave (Chromium)**
  - :angel: adding folder WORKS via button
  - :angel: adding folder WORKS via drag&drop

So after we merge #1457 the only thing that needs to be fixed is adding folder via button in Electron.

**Comment by rafaelramalho19** [comment]
Thanks for testing that out @lidel. 

I'll see what's wrong with the button

**Comment by hacdias** [comment]
> 💢 adding folder does not work via button (no error in Console)

@lidel it does now thanks to @rafaelramalho19's work :smiley: Thank youu

**Comment by lidel** [comment]
Remaining issue with adding Folders via WebUI button should be fixed in [v0.11.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.11.2)
Upgrade ASAP :-)
