### ISSUE TITLE
"Launch on startup" is grayed out in v0.10.2

### ISSUE THREAD

**Issue by alexhenrie** [ipfs-shipyard/ipfs-desktop#1290]
In the IPFS Desktop settings page, the "Launch on startup" checkbox is grayed out and can no longer be checked. A regression test said:

```
5dc624e3eba71d8097606aeded5af3bdaee3252c is the first bad commit
commit 5dc624e3eba71d8097606aeded5af3bdaee3252c
Author: Henrique Dias <hacdias@gmail.com>
Date:   Wed Oct 30 17:52:29 2019 +0000

    feat: web ui 2.6.0 (#1226)
    
    See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.6.0.

 package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by hacdias** [comment]
Which OS are you running?

**Comment by alexhenrie** [comment]
Arch Linux, fully updated, IPFS Desktop built from source.

**Comment by hacdias** [comment]
That is so weird... it says `5dc624e3eba71d8097606aeded5af3bdaee3252c` is the first bad commit, but even looking at it, we are just updating Web UI:

https://github.com/ipfs-shipyard/ipfs-desktop/commit/5dc624e3eba71d8097606aeded5af3bdaee3252c

Does the previous commit work?

**Comment by sixcorners** [comment]
It's grayed out for the person in this ticket: #1321
It's grayed out for me too.
The built in chrome dev tools says my os.platform() is "browser"

**Comment by sixcorners** [comment]
Also it looks like this stuff doesn't actually make anything happen on startup..
It writes a file to ~/.config/autostart/ or something on linux and mac and windows get this business: `app.setLoginItemSettings({ openAtLogin: true })`.
Startup and login are very different things...

**Comment by hacdias** [comment]
@sixcorners `setLoginItemSettings` is only supported on Windows and macOS [per the docs](https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows).

> Could the option be changed to "Launch on login" or something?

Personally, I don't mind.

> The built in chrome dev tools says my os.platform() is "browser"

Yes, and this seems to be where the bug is.

**Comment by sixcorners** [comment]
@hacdias That's a bummer. How can it be fixed? Could the node side of the app be asked for that information or is there a better way to do it?
