### ISSUE TITLE
ipfs error out every a few days

### ISSUE THREAD

**Issue by hoogw** [ipfs-shipyard/ipfs-desktop#1306]
I have latest ipfs runing, v0.4.22 with ipfs desktop 
but every a few days, the status is error.

I have to restart ipfs.

Is there way it can automatically restart ipfs when error or failure?

**Comment by hoogw** [comment]
`siriuss-mini:~ sirius$ ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.22-
Repo version: 7
System version: amd64/darwin
Golang version: go1.12.7
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.86.207/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.86.207/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: concurrent write to websocket connection

goroutine 17657899 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc001b66150, 0x5d4b701, 0x0, 0x0, 0x0, 0x10173af, 0x6779ff8)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:591 +0x77a
github.com/gorilla/websocket.(*messageWriter).Close(0xc001b66150, 0x0, 0x889605d4b700)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:709 +0x56
github.com/gorilla/websocket.(*Conn).prepWrite(0xc002853b80, 0x2, 0x203002, 0x6779ff8)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:459 +0x20d
github.com/gorilla/websocket.(*Conn).NextWriter(0xc002853b80, 0x2, 0x100bbd9, 0xc00758fd80, 0x10, 0xc0075f1501)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:494 +0x39
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc002853b80, 0x2, 0xc00a29b000, 0x23, 0x1000, 0x10, 0xc000387800)
	pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:755 +0x73
github.com/libp2p/go-ws-transport.(*Conn).Write(0xc006f6a120, 0xc00a29b000, 0x23, 0x1000, 0xc00ab25cc0, 0x100c468, 0x1)
	pkg/mod/github.com/libp2p/go-ws-transport@v0.0.4/conn.go:74 +0x59
bufio.(*Writer).Flush(0xc0096979c0, 0xc0096979c0, 0xc00a6659b0)
	/usr/lib/go/src/bufio/bufio.go:590 +0x7b
github.com/multiformats/go-multistream.delimWriteBuffered(0x5b79250, 0xc006f6b800, 0xc00a6659b0, 0x21, 0x21, 0x0, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/multistream.go:72 +0xdd
github.com/multiformats/go-multistream.ReadNextTokenBytes(0x5d4b770, 0xc006f6b800, 0xc009b69620, 0x103689f, 0xc009b695f0, 0xc009b69620, 0x1009c35)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/multistream.go:393 +0x17f
github.com/multiformats/go-multistream.ReadNextToken(...)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/multistream.go:377
github.com/multiformats/go-multistream.readMultistreamHeader(0x5d4b770, 0xc006f6b800, 0xc006f6b800, 0x5d4b770)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/client.go:90 +0x3a
github.com/multiformats/go-multistream.SelectProtoOrFail(0x1e28f36, 0xc, 0x5d4b740, 0xc006f6b800, 0x5d4b740, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/client.go:31 +0xd7
github.com/multiformats/go-multistream.SelectOneOf(0xc00038aa00, 0x2, 0x2, 0x5d4b740, 0xc006f6b800, 0x2000200, 0x2000000, 0x0, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.0.4/client.go:57 +0x6c
github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto.func1(0xc003c7cf60, 0x0, 0xc000140af0, 0x5d4b6e8, 0xc006f6b800, 0xc00b435030, 0xc00b435110)
	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.0.2/ssms.go:68 +0x192
created by github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto
	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.0.2/ssms.go:63 +0xe5
siriuss-mini:~ sirius$

**Comment by hoogw** [comment]
Mac

**Comment by lidel** [comment]
This was upstream issue with go-ipfs (https://github.com/ipfs/go-ipfs/issues/6197), please upgrade to the latest ipfs-desktop [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)
