### ISSUE TITLE
Error on enabling IPFS command line tools

### ISSUE THREAD

**Issue by marathone** [ipfs-shipyard/ipfs-desktop#1315]
Please describe what you were doing when this error happened.
tried to enable file tools, resulting in this error. I have the server already running and documentation says that the desktop app can be used to manage the server already running on a system.
**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.10.2
- **Electron Version**: 7.1.2
- **Chrome Version**: 78.0.3904.113

**Error**

```
Error: Unable to find pkexec or kdesudo.
    at test (/snap/ipfs-desktop/7/resources/app.asar/node_modules/sudo-prompt/index.js:205:18)
    at /snap/ipfs-desktop/7/resources/app.asar/node_modules/sudo-prompt/index.js:212:47
    at FSReqCallback.oncomplete (fs.js:165:21)
```

**Comment by lidel** [comment]
@marathone whats the Linux distribution?

**Comment by lidel** [comment]
Try installing policykit (it provides `pkexec` command) and trying again:

```bash
apt update
apt install policykit-1
reboot
```

**Comment by marathone** [comment]
On Wed, Jan 15, 2020 at 03:50:32AM -0800, Marcin Rataj wrote:
> Try installing policykit (it provides `pkexec` command) and trying again:
> 
> ```bash
> apt update
> apt install policykit-1
> reboot

It was installed - FWIW this is a snap package. I guess you're not the snap 
maintainer. I should have checked that out first. Sorry for the noise.

I should install your package.

**Comment by lidel** [comment]
@marathone ah, was the issue was with https://github.com/elopio/ipfs-snap, or something else?
Is it ok to close this as fixed then?

**Comment by marathone** [comment]
On Tue, Jan 21, 2020 at 10:05:45AM -0800, Marcin Rataj wrote:
> @marathone ah, was the issue was with https://github.com/elopio/ipfs-snap, or something else?
> Is it ok to close this as fixed then?

Yes it was with that snap and it's ok to close the issue as 'fixed'. Thanks!
