### ISSUE TITLE
Can't start on Windows 7 SP1

### ISSUE THREAD

**Issue by shahoob** [ipfs-shipyard/ipfs-desktop#1316]
Welp, idk what happened.

### Specs
- OS: Windows 7 (With SP1)
- IPFS Desktop Version: 0.10.2
- go-ipfs Version: 0.4.22

### Error
```
2020-01-09T19:30:43.724Z error: [ipfsd] start daemon Error: multiaddr "                       " must start with a "/"
```

**Comment by hacdias** [comment]
Windows 7 is no longer supported by Microsoft so it's not weird for me that some errors start to pop up on older Windows versions. So, as a part-time Windows user, this has never happened to me.

Is there any more context on when the error happened? Or anything else of the logs?

**Comment by shahoob** [comment]
I actually started using Windows 10.

**Comment by tkeriduN** [comment]
This just happened to me on Windows 10. Well, actually it didn't _just start_ happening now, I see in the error logs that it's been happening for three months. 

[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/5682257/error.log)

**Comment by shahoob** [comment]
Update: Delete the folder `.ipfs`
This will lose access to your original files stored on your peer
In fact, Your peer will be reset.
