### ISSUE TITLE
Release 0.10.4

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1343]
# Release Notes

This is a bugfix release that solves includes notarization for macOS Catalina (https://github.com/ipfs-shipyard/ipfs-desktop/issues/1211)

- Web UI: [`v2.7.2`](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.2)
- IPFS: [`go-ipfs v0.4.23`](https://github.com/ipfs/go-ipfs/releases/tag/v0.4.23)

### 🛠 Fixes and Maintenance

- [x] remove security warning on macOS (add notarization) (https://github.com/ipfs-shipyard/ipfs-desktop/issues/1211)
- [x] debian 10: ipfs-desktop > Trace/breakpoint trap (https://github.com/ipfs-shipyard/ipfs-desktop/issues/1362)
  - fix: chrome-sandbox and Debian 10 (#1370)

# Before Release

- [x] Make sure there are no regressions in file upload
  - no change: known issue with adding folders remains https://github.com/ipfs-shipyard/ipfs-desktop/issues/1287#issuecomment-580368657
- [x] Make sure i18n is updated (`tx pull -a`)
- [x] Make sure we're using the latest released version of Web UI
- [x] Make sure we're using the latest released version of `go-ipfs`
- [x] Update Release Notes accordingly

# Release

- [x] 📝 Create draft and copy the release notes above
- [x] 💻 Bump version in `package.json`
- [x] 💻 `git tag $version`
- [x] 💻 `git push && git push --tags`
- [x] ⏰ Wait for CI to attach artifacts to release draft...
- [x] 📃 Copy the final release notes to the GitHub release
  - [x] Linux smoke test (`.tar.xz`)
    - [x] confirm `.deb` works in Debian 10
  - [x] Mac smoke test (`.dmg`)
    - [x] ❗ perform `.dmg` notarization with `pkgs/macos/notarize-cli.js`
  - [x] Window smoke tests (`.exe`)
- [x] 🚢 Ship! (publish draft as a real GithHub release)
- [x] 📑 Update README.md versions
- [x] 📦 Update Homebrew ([instructions](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask))
- [ ] 📦 Update Chocolatey

**Comment by lidel** [comment]
@Luflosi would you have a spare moment to bump homebrew-cask to 0.10.4? :pray:

**Comment by Luflosi** [comment]
Done.
