### ISSUE TITLE
File (IPFS-Desktop-Setup-0.10.3.exe) Download timeout 

### ISSUE THREAD

**Issue by vpeicn** [ipfs-shipyard/ipfs-desktop#1345]
Could you provide cid when you publish a new file?

**Comment by lidel** [comment]
Switching away from GithHub  for publishing is tracked in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1263#issuecomment-558416578

For now, try http://ipfs.io/ipfs/bafybeidrkdozovc5zcwk7u5murva4wdug4oi42pi3kof6svgzwdbjmcdra/IPFS-Desktop-Setup-0.10.4.exe

**Comment by vpeicn** [comment]
This URL can be downloaded.Thanks.
________________________________
发件人: Marcin Rataj <notifications@github.com>
发送时间: 2020年3月12日 11:31
收件人: ipfs-shipyard/ipfs-desktop <ipfs-desktop@noreply.github.com>
抄送: www <vpei@live.com>; Author <author@noreply.github.com>
主题: Re: [ipfs-shipyard/ipfs-desktop] File (IPFS-Desktop-Setup-0.10.3.exe) Download timeout (#1345)


Switching away from GithHub for publishing is tracked in #1263 (comment)<https://github.com/ipfs-shipyard/ipfs-desktop/issues/1263#issuecomment-558416578>

For now, try http://ipfs.io/ipfs/bafybeidrkdozovc5zcwk7u5murva4wdug4oi42pi3kof6svgzwdbjmcdra/IPFS-Desktop-Setup-0.10.4.exe

―

**Comment by lidel** [comment]
@vpeicn are you in China by any chance? Are those timeouts a common problem?

**Comment by vpei** [comment]
> 
> 
> @vpeicn are you in China by any chance? Are those timeouts a common problem?

yes
