### ISSUE TITLE
Signed releases

### ISSUE THREAD

**Issue by Mikaela** [ipfs-shipyard/ipfs-desktop#1349]
Do you have plans to sign the releases on GitHub? I was only able to find https://github.com/ipfs/go-ipfs/issues/957 which seemed to be stuck on some Go issue/release, but there are already packages provided by IPFS Desktop and I am wondering how can I verify their authenticity?

I understand that the appimage/electron has something to verify authenticity of an update, but can that be used to verify the authenticity of the initial download?

**Comment by lidel** [comment]
Great question!

iirc we already do vendor-specific signing:

- Windows `.exe` are signed
- macOS `.dmg` is signed too, what remains to be done is "notarization", which can be tracked in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1211

As for vendor-agnostic signing, see already existing  https://github.com/ipfs-shipyard/ipfs-desktop/issues/789 and https://github.com/ipfs-shipyard/ipfs-desktop/issues/1189 (we want to switch from github releases to self0hosted autoupdate solution + leverage content-addressing).

**Comment by hardcore-sushi** [comment]
For Linux releases, it would be great to sign binaries with a PGP key. You could still use github or amazon but authenticity will be guaranteed. The PGP key could be retrieved from ipfs.io, keyservers, or directly on IPFS (available via a gateway).
