### ISSUE TITLE
how to enable pubsub?

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-desktop#1352]
when i use `ipfs-http-client`

> Error: experimental pubsub feature not enabled

ipfs-desktop config keys not same as js-ipfs

i can't add `ipnsPubsub: true,` into config for make work

**Comment by rigwild** [comment]
Got a similar issue, could not find the proper configuration to set in the app.

I'm doing the following instead:

Stop the IPFS node running in `ipfs-desktop` (right click on the notification bar icon -> stop)

Open a terminal and run:

```sh
ipfs daemon --enable-pubsub-experiment
```

**Comment by bluelovers** [comment]
i already remove desktop app and use my own script for start it
https://github.com/bluelovers/ws-ipfs/tree/master/packages

**Comment by rigwild** [comment]
For any future readers (and orbit-db users), I just found out you can add the flag `--enable-pubsub-experiment` by doing so:

1. Right click on the notification bar icon -> `Advanced` -> `Configuration file`
2. Add the flag
```json
		"flags": [
			"--migrate=true",
			"--routing=dhtclient",
			"--enable-gc=true",
			"--enable-pubsub-experiment"
		],
```
3. Restart the IPFS node

**Comment by bluelovers** [comment]
@rigwild flags need put inside which field?

**Comment by rigwild** [comment]
@bluelovers Here is config file example.

```js
{
	"ipfsConfig": {
		"type": "go",
		"path": "C:\\Users\\example\\.ipfs",
		"flags": [
			"--migrate=true",
			"--routing=dhtclient",
			"--enable-gc=true",
			"--enable-pubsub-experiment"
		],
		"keysize": 2048
	},
	"version": 5,
	"language": "en",
	"experiments": {
		"npmOnIpfs": false
	},
	"ipfsOnPath": true,
	"checkedCorsConfig": true,
	"screenshotShortcut": false
}
```

**Comment by bluelovers** [comment]
@rigwild  thx

oh I thought it is same as config in webui, that is why when i set it , but didn't save

**Comment by hacdias** [comment]
Thanks @rigwild for your help here. I'm closing this since it seems @bluelovers question is solved!
