### ISSUE TITLE
Add manual garbage collector button

### ISSUE THREAD

**Issue by rigwild** [ipfs-shipyard/ipfs-desktop#1355]
Hi!

I was looking to manually start the garbage collector but did not find any button to do it. I think it would be useful to have an option to do so.

This issue shows that it has been implemented in the past: https://github.com/ipfs-shipyard/ipfs-desktop/issues/635 (closed by https://github.com/ipfs-shipyard/ipfs-desktop/pull/636)

I can't find when it was scrapped, though.

Have a nice day!

**Comment by jessicaschilling** [comment]
@hacdias, do you have the background on this?

**Comment by RubenKelevra** [comment]
I would really like to have this ability on the desktop client, too. :)

**Comment by hacdias** [comment]
Hey! This would be quite easy to add - no promises, but it seems there's an API function just for this: [`ipfs.repo.gc`](https://github.com/ipfs/js-ipfs/blob/10e8682e44ed06fdcad849b7cb7e6a38dbd9ba49/docs/core-api/REPO.md#ipfsrepogcoptions). I think that, if implemented, this could go under Advanced:

![image](https://user-images.githubusercontent.com/5447088/79504438-ce849a80-802a-11ea-9cee-837ba4b4141a.png)

Some command like 'Run Garbage Collector'.

It seems we had this feature before and it was me that implemented it: #636. It seems it got lost when we transformed the app in a menubar-only application.

@jessicaschilling I can try to pull this out tomorrow.

**Comment by jessicaschilling** [comment]
@hacdias Thanks for digging around! Much appreciated 😊

**Comment by rigwild** [comment]
Nice! :)
