### ISSUE TITLE
Update readme to clarify how links can be opened

### ISSUE THREAD

**Issue by davidmoseler** [ipfs-shipyard/ipfs-desktop#1366]
The readme mentions

"Handle ipfs://, ipns:// and dweb: links

If you come across a link to any of the protocols above, IPFS Desktop will be able to open them and redirect them to your default browser."

but it is missing, both from here as from ipfs guides (https://docs.ipfs.io/guides), how should one proceed to open an ipfs link that is provided as text. This is a very basic feature and I fear that if I'm having this much trouble, this could scare a lot of users from further digging into ipfs. If I have an ipfs link, say, /ipns/torrent-paradise.ml, how should I proceed to open it using the ipfs-desktop application or the background daemon?

Edit: with the frontend, I'm of course able to visualize the files from a web application, but how can I open the link directly in the browser as a website? I know I could do it through cloudfare or https://ipfs.io/LINK, but these are just centralized proxy services to the actual descentralized network, so it is important to be able to open the links in the browser with some 127.0.0.1/ipfs/obj syntax. This is missing from documentation though.

Edit2: I kept randomly messing with the port numbers until I found the correct one: 8080. So, in the example given, `http://127.0.0.1:8080/ipns/<something>` typed into the browser will show the website. Although I figured it out by sheer luck, I still think it is very important to have this info in the readme. 8080 is a common port providing a "localhost" alternative for the 80 http default, but in no way should be taken as a given.

**Comment by lidel** [comment]
>  If I have an ipfs link, say, /ipns/torrent-paradise.ml, how should I proceed to open it using the ipfs-desktop application or the background daemon?

You can just prefix any content path with some gateway, eg. `https://ipfs.io/` and it should load. 

If you install [ipfs-companion](https://github.com/ipfs-shipyard/ipfs-companion#ipfs-companion) browser extension it will redirect such requests to local gateway at `http://127.0.0.1:8080` 

> Although I figured it out by sheer luck, I still think it is very important to have this info in the readme. 8080 is a common port providing a "localhost" alternative for the 80 http default, but in no way should be taken as a given.

Agree. Do you want to open a PR that updates README and adds expected info?

**Comment by hacdias** [comment]
When we say "handle ipfs://, ipns:// and dweb: links" it means exactly that: links with those protocols can be handled by IPFS Desktop, i.e., they can be opened by IPFS Desktop.

For example, if you come across to a link that points to 'ipns://ipfs.io', it will be opened by IPFS Desktop. Internally, IPFS Desktop will translate that into a Gateway URL (https://ipfs.io/ipns/ipfs.io in this case) and open your browser.
