### ISSUE TITLE
Need to change the port on IPFS Desktop to get it running.

### ISSUE THREAD

**Issue by Jay20Games** [ipfs-shipyard/ipfs-desktop#1372]
This is from error.log:
`
2020-03-11T01:32:31.359Z error: [ipfsd] start daemon Error: Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
`
This is my config.json:
```
{
	"ipfsConfig": {
		"type": "go",
		"path": "",
		"flags": [
			"--migrate=true",
			"--routing=dhtclient",
			"--enable-gc=true"
		],
		"keysize": 2048
	},
	"version": 5,
	"language": "en-US",
	"experiments": {
		"npmOnIpfs": false
	},
	"ipfsOnPath": true,
	"checkedCorsConfig": true,
	"window": {
		"width": 1440,
		"height": 784
	}
}
```
I'm using Windows 10 and I have another software package that's using port 8080. How can I get IPFS Desktop to use another port?

Thanks,
Jay

**Comment by hacdias** [comment]
Hey Jay! When starting IPFS Desktop, it doesn't ask you to change the ports automatically?

**Comment by Jay20Games** [comment]
Hi Henrique. I tried out the new version 0.10.4 and had the same initial troubles. Closing the program and relaunching didn't give me a prompt to change ports, but I did receive the prompt after choosing "Restart" from the context menu. It is working now. Thanks!
