### ISSUE TITLE
"Check for Updates.."  menu item gives no feedback

### ISSUE THREAD

**Issue by andrew** [ipfs-shipyard/ipfs-desktop#1378]
![Screenshot 2020-03-18 at 15 50 16](https://user-images.githubusercontent.com/1060/76980354-fcde5f80-6930-11ea-9078-b0b4d134a801.png)

When I click on the "check for updates" menu item in MacOS (Catalina), I get no visual feedback on what is happening, if there is a new release or if I'm on the latest one.

One thing to note is that I didn't allow notifications for IPFS desktop, so if it's trying to communicate only via native notifications then I wouldn't see it, but that's also very non-standard for Mac os apps. 

Expected behavior: I would expect there to be a pop up window that either gave details of a new release that's available to download (related issue https://github.com/ipfs-shipyard/ipfs-desktop/issues/1210) or a message that says I'm on the latest version, like Zoom does:

![Screenshot 2020-03-18 at 15 59 36](https://user-images.githubusercontent.com/1060/76980888-ad4c6380-6931-11ea-85c0-af1f7f4d85c1.png)

**Comment by lidel** [comment]
Thank you, that is very good feedback and I am pretty sure blocked notification is the case: 

https://github.com/ipfs-shipyard/ipfs-desktop/blob/ace72b21cb670f29fedad852e10c803010bf9ab5/src/auto-updater/index.js#L12-L17

Potential fix here would be to display pop up when `userRequested` is `true`

**Comment by hacdias** [comment]
On my computer, I get a notification:

<img width="362" alt="Screenshot 2020-03-26 at 15 41 41" src="https://user-images.githubusercontent.com/5447088/77666031-57eb0480-6f78-11ea-86bb-c582184199e2.png">

I know that if there's a version available, it will take a lot more time to get a notification though.

**Comment by hacdias** [comment]
@lidel 

> Potential fix here would be to display pop up when userRequested is true

That's what's happening

**Comment by andrew** [comment]
@hacdias part of the problem is that if you don't enable notifications for the ipfs desktop app when you first install it on mac os (because not everyone likes apps to be able to randomly interrupt you with pings), then you don't see anything happen.

**Comment by hacdias** [comment]
Ooooh, I understand what you mean then. We actually rely __a lot__ on notifications. Personally, I wouldn't mind to use dialogs for some actions such as this.

Wdyt?

/cc @lidel

**Comment by andrew** [comment]
+1 for dialogs that are direct responses to UI actions

**Comment by jessicaschilling** [comment]
+1 for @andrew's notes on this being a much more prevalent interaction pattern for a dialog, not a notification. I'd like to try to queue this up for as soon as we have developer resources; happy to provide language for the dialog text.
