### ISSUE TITLE
File cannot upload to desktop app

### ISSUE THREAD

**Issue by DougAnderson444** [ipfs-shipyard/ipfs-desktop#1432]
Window 8
ipfs-desktop 0.10.4

Observed behaviour:
1. Repo shows 11MB in size, but there are no files here? (Might be from an old CLI install?)
2. There's no ```"Add to IPFS button"``` as indicated
3. Drag and drop files shows yellow error snackbar
4. ```"...More"``` is greyed out (not sure if it's supposed to be grey?)

Here's a screenshot:

![image](https://user-images.githubusercontent.com/6699901/79782130-902dfa80-830c-11ea-858d-e9531c963d94.png)

**Comment by lidel** [comment]
@DougAnderson444 please uninstall the old version, and try again with [v0.11.1](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.11.1)

**Comment by lidel** [comment]
Assuming it was fixed long time ago. If not, please upgrade to the latest version ([v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2))
