### ISSUE TITLE
Disable WebUI links in "IPFS is Not Running" state

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1436]
When node is stopped/offline, menu items that open WebUI are still active:

> ![off-when-off-2020-04-23--00-49-45](https://user-images.githubusercontent.com/157609/80041359-8ff45180-84fc-11ea-9a71-7d73399fca11.png)

Opening them shows webui in "unable to connect to node" state, which is bit confusing for less technical users.

I believe we should make them inactive when "IPFS is Not Running"

**Comment by jessicaschilling** [comment]
+1.

**Comment by hacdias** [comment]
Yes, I will make a PR asap. I think we had that available before because the settings were in the web ui and still accessible.
