### ISSUE TITLE
"Open Web UI at Launch" stays at  `/blank` instead of `/` 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1451]
WebUI seems to have some leftovers related to settings, which produce an error:

> ![2020-04-27-135139_1330x435_scrot](https://user-images.githubusercontent.com/157609/80369317-5c178400-888e-11ea-9696-02007ae58161.png)

**Comment by lidel** [comment]
I believe ipfs-desktop is not using a release version of webui, but omne from https://github.com/ipfs-shipyard/ipfs-webui/pull/1445

**Comment by hacdias** [comment]
@lidel yes, it stays at `/blank`. Will fix in a minute.

And yes, we're using the master branch of Web UI. You're still using an older version and that's why you're getting that error. Try rebuilding the Web UI part.

We'll need a new release of Web UI before releasing this.
