### ISSUE TITLE
The app doesn't close nor it remains in the system tray

### ISSUE THREAD

**Issue by nlko** [ipfs-shipyard/ipfs-desktop#1485]
- OS: Ubuntu 16.04
 - Version: 1b58b62

**Describe the bug**
With the previous version it was possible to reduce the app to the system tray and from there : quit, start, stop, restart the daemon. The latest version of the app doesn't have any icon in the system tray. When I close the app, the app disappears but remains in the background. I have to kill it manually. 

**Expected behavior**
Provide a real way to exit the app or consider restoring the system tray like before.

**Screenshots**
![image](https://user-images.githubusercontent.com/5183366/80921857-5384e900-8d79-11ea-8ace-ea8a8b998e91.png)

**Comment by rafaelramalho19** [comment]
Hi @nlko, have you taken a look at this section of the troubleshooting?

https://github.com/ipfs-shipyard/ipfs-desktop#no-tray-icon-on-linux

See if it's related to your problem, please.

**Comment by nlko** [comment]
Thanks @rafaelramalho19, It looks like the problem. I'm not an electron developer but I was unable to create a app with tray icon (using the latest electron). You might be right since i'm using the old unity desktop environment.

**Comment by rafaelramalho19** [comment]
Will close this issue since it seems to be unrelated with ipfs-desktop.
If there's anything related with this again please open a new issue 🙇
