### ISSUE TITLE
Enable to start IPFS command line tool

### ISSUE THREAD

**Issue by VishwaMishra** [ipfs-shipyard/ipfs-desktop#1490]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by rafaelramalho19** [comment]
@VishwaMishra thank you for opening the issue. Can you please detail the steps you had to perform for this issue to occur?

**Comment by VishwaMishra** [comment]
I was installed updated version of ipfs-desktop. 
Specifications

OS: win64
IPFS Desktop Version: 0.11.2
Electron Version: 8.2.4
Chrome Version: 79.0.3945.130

ipfs-deamon>Advanced>Run using CLI tool
