### ISSUE TITLE
Switch to go-ipfs 0.5.1

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1500]
We should release ipfs-desktop v0.11.3 with go-ipfs v0.5.1
Ref. https://github.com/ipfs/go-ipfs/releases/tag/v0.5.1

Note: this depends on https://www.npmjs.com/package/go-ipfs-dep being updated to 0.5.1 first, which should happen automatically within 1-2h after https://dist.ipfs.io is updated. If its not at 0.5.1 tomorrow, we need to look into why automatic publishing failed.

**Comment by bertrandfalguiere** [comment]
If you son't mind updating the translations at the same time... :)

https://github.com/ipfs-shipyard/ipfs-desktop/issues/1415#issuecomment-621108408
