### ISSUE TITLE
Update all translations upon release

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs-shipyard/ipfs-desktop#1528]
- OS: All
 - Version of IPFS Desktop: At least 0.11.x

**Describe the bug**
Translations are missing or incomplete in several languages even though they are translated and review on [Transifex](transifex.com/ipfs/). 

**To Reproduce**
1) Select French or Italian language (that are fully translated).
2) See English texts in most places.

**Expected behavior**
The selected language is displayed onscreen.

I think updating translations from [ipld-explorer-components](https://github.com/ipfs-shipyard/ipld-explorer-components) and [webUI](https://github.com/ipfs-shipyard/ipfs-webui) should be in the check list for releases of IPFS Desktop.

See https://github.com/ipfs-shipyard/ipld-explorer-components/issues/242 and https://github.com/ipfs-shipyard/ipfs-webui/issues/1370

**Comment by jessicaschilling** [comment]
@rafaelramalho19 @lidel just a bump on this as we prepare to release Desktop.

**Comment by lidel** [comment]
We decoubled Desktop from webyui (#1389) and I believe with webui v0.12.2 and https://github.com/ipfs-shipyard/ipfs-desktop/commit/60df053eb678a62decd391257ccce85526c32c96 we should be in a better place.  If explorer is still outdated, it will get bubbled up to ipfs-desktop with new version of ipfs-webui eventually.

**Comment by lidel** [comment]
..continued in https://github.com/ipfs-shipyard/ipld-explorer-components/pull/281 :rocket:
