### ISSUE TITLE
error

### ISSUE THREAD

**Issue by larry19881007** [ipfs-shipyard/ipfs-desktop#1532]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: net::ERR_NETWORK_IO_SUSPENDED
```

**Comment by lidel** [comment]
Please upgrade to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2), feel free to reopen if the problem still occurs.
