### ISSUE TITLE
IPFS desktop app does not launch

### ISSUE THREAD

**Issue by anaelleltd** [ipfs-shipyard/ipfs-desktop#1534]
I clicked on the IPFS desktop icon to connect but got an error message.
The application does not launch at all.
See image attached.
![ipfs error](https://user-images.githubusercontent.com/44770354/83401006-841e7800-a436-11ea-9b3b-064d8cb56d91.JPG)

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.4
- **Electron Version**: 7.1.14
- **Chrome Version**: 78.0.3904.130

**Error**

```
Error: EPERM: operation not permitted, open 'C:\Users\atale\.ipfs-desktop\IPFS_PATH'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1206:35)
    at Object.outputFileSync (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\output\index.js:31:15)
    at writeIpfsPath (C:\Program Files\IPFS Desktop\resources\app.asar\out\daemon\index.js:374:23)
    at _callee3$ (C:\Program Files\IPFS Desktop\resources\app.asar\out\daemon\index.js:163:27)
    at tryCatch (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
```

**Comment by TMladenic** [comment]
Can you try the newer version. I've had that error with older ones.

**Comment by anaelleltd** [comment]
Hi,

Thanks for the suggestion.
I already tried connecting with the newer version aftee unstalling
everything. I still got the same message.

Any other options?

Cheers.
Ana.

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by olizilla** [comment]
@hacdias this looks like a file permissions issue on windows, can you take a look?

**Comment by hacdias** [comment]
Just made a fresh install of Windows 10, installed IPFS Desktop and no errors popped up. There's definitely something different with this user's permissions.

Out of curiosity: did you do a user install or system wide install?

**Comment by anaelleltd** [comment]
Hi hacdias,

Thanks you for this.

I did a system-wide (all users) install. I have checked that the ipfs app is allowed through my windows firewall, and it is.
I have just tried again now, but I still get the same error.
My windows 10 is up-to-date and I have not done any OS "customisation" at all.

Cheers,
Ana.

**Comment by hacdias** [comment]
Hmmm... that's odd anyway. I tried with a system-wide installation and it still worked. Can you try manually removing `C:\Users\atale\.ipfs-desktop` and starting IPFS Desktop again?

**Comment by anaelleltd** [comment]
Hi,

Icopied and followed the filepath (C:\\atale\.ipfs-desktop\FILEPATH), but
it only launches the app which gives.the same error message.

When I looked into the actual C:\\atale\ folder, the ".ipfs-desktop" folder
does not appear. I set up my files explorer to display hidden folders, but
the ".ipfs-desktop" folder still doesn't show up.

My guess is that this is temp folder that links to the actual installation
folder on the main drive (C:\\ProgramFiles\ipfs desktop\).  When i looked
into the "ipfs desktop" folder, i see the usual application components and
IPFS Desktop.exe

Could it be that the app is bouncing around users and admin permissions and
failing to launch the scripts as a result? Is there a "manifest/mapping"
file that can be included in the installation folder to help with this
process?

Thanks in advance,
Ana.

Le jeu. 2 juil. 2020 à 18:21, Henrique Dias <notifications@github.com> a
écrit :

**Comment by rafaelramalho19** [comment]
Hi Ana,

Can you try and delete `C:\Users\User\AppData\Local\Programs\IPFS Desktop\`, `C:\Users\User\AppData\Roaming\IPFS Dekstop` and `C:\Users\User\.ipfs-desktop\` and reinstalling?

**Comment by anaelleltd** [comment]
Something strange happened. 
I couldn't find the folders that you said I should delete. I then used the cmd/Powershell to install ipfs desktop through chocolatey. The app launched (with a port error!) and the folders suddenly appeared.

I have unistalled everything from the choco version, and re-installed the latest v0.11.4. Now I am able to see these folders again.
But there is another issue: IPFS has errored (see image attached).
![ipfs error3](https://user-images.githubusercontent.com/44770354/86357686-cbe82780-bca0-11ea-8d79-60f374a95d0a.JPG)

I'm glad to see we are making some progress though! :)

**Comment by anaelleltd** [comment]
Error log file in C:\Users\User\AppData\Roaming\IPFS Dekstop\

2020-07-02T12:19:13.241Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.5.1
Repo version: 9
System version: amd64/windows
Golang version: go1.13.10
Found outdated fs-repo, migrations need to be run.
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Running: C:\Users\atale\AppData\Local\Temp\go-ipfs-migrate784642735\fs-repo-migrations.exe -to 9 -y
Found fs-repo version 7 at C:\Users\atale\.ipfs
===> Running migration 7 to 8...
applying 7-to-8 repo migration
locking repo at "C:\\Users\\atale\\.ipfs"
  - verifying version is '7'
> Upgrading config to new format
ERROR: failed to update version file to 8
ipfs migration:  migration 7 to 8 failed: open C:\Users\atale\.ipfs/version: Access is denied.
  => Failed: C:\Users\atale\AppData\Local\Temp\go-ipfs-migrate784642735\fs-repo-migrations.exe -to 9 -y
The migrations of fs-repo failed:
  migration failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

**Comment by rafaelramalho19** [comment]
@anaelleltd sorry for the late response, but looking that the logs, the path `C:\Users\atale.ipfs/version` appears to be invalid, I think it should be `C:\Users\atale\ipfs\version` 🤔 

Just to be clear, this only happens when you install via chocolatey? Have you tried the `.exe` in releases? (https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.12.1/IPFS-Desktop-Setup-0.12.1.exe)

**Comment by anaelleltd** [comment]
Hi Rafael,

You are correct in saying the path to \ipfs\ wasn't valid (hence why I couldn't find it!), and I spent the past few days going through individual hidden folders on my drive to find it. 

I was able to remove all files from my drive and I have just re-run the Powershell command for chocolatey ipfs desktop (v.0.10.4) and... the installation works! :)

All my files have been erased in the meantime though, and none of my peers seem to have a copy of them available. Is this normal?

Cheers,
Ana.

**Comment by anaelleltd** [comment]
Please ignore my last question: I am operating with a different Qmhash. 👍

**Comment by rafaelramalho19** [comment]
Happy that it's fixed now 😄 

I'll check in the near future why chocolatey only has up to version 0.10.4, you should use our latest (0.12.1) for increase go-ipfs performance and webui features 😄

**Comment by anaelleltd** [comment]
I'm getting it now.
Thanks!

**Comment by hacdias** [comment]
@rafaelramalho19 I'mn pretty sure Chocolatey needs to be manually updated after each release, just like brew.

**Comment by rafaelramalho19** [comment]
@hacdias I saw that, that's why I'm going to (try) automate the build process to also publish to Chocolatey and Brew 👍
