### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by muronglaowang** [ipfs-shipyard/ipfs-desktop#1537]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by lidel** [comment]
Please upgrade to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2), feel free to reopen if the problem still occurs.
