### ISSUE TITLE
Program crashed after waking the laptop from sleep

### ISSUE THREAD

**Issue by prashant-anand** [ipfs-shipyard/ipfs-desktop#1542]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by rafaelramalho19** [comment]
Thank you for reporting. 

@lidel you think we should approach this with a "try to connect again before throwing errors" approach?

**Comment by lidel** [comment]
I believe Electron has powerMonitor API - perhaps we could stop running node on 'suspend' and 'shutdown' events and start it on 'resume' if it was stopped due to 'suspend'? 

a nice side effect of this will be automatic refresh of IP when someone is moving laptop between buildings

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by lidel** [comment]
This should be fixed in [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2), or at least you should be able to attach logs to your error report if similar issue happens again. Please update to the latest version.
