### ISSUE TITLE
Program crashed when WIFI network is switched.

### ISSUE THREAD

**Issue by prashant-anand** [ipfs-shipyard/ipfs-desktop#1543]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by olizilla** [comment]
Thanks for the report @prashant-anand. IPFS Desktop tries to restart the ipfs daemon process when it detects that the network has changed, but it should not crash, that's a bug, i'll take a look, but it may be difficult to recreate. Did the crash happen just one time, or does it crash for you every time you change network?

**Comment by lidel** [comment]
See https://github.com/ipfs-shipyard/ipfs-desktop/issues/1542#issuecomment-707266266
