### ISSUE TITLE
go-ipfs binary not found, it may not be installed or an error may have occured during installation

### ISSUE THREAD

**Issue by chenguoliangclub** [ipfs-shipyard/ipfs-desktop#1550]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by olizilla** [comment]
@chenguoliangclub it looks like your hitting a problem trying to install ipfs-desktop. Could you add more information about what happned? What OS are you using? Did you installl the app manually, or via a package manager like homebrew? Do you have any screenshots? The more you can walk us through what happened, the more likely it is we can help you.

**Comment by lidel** [comment]
Sadly not enough details. 
Please update to the latest version ([v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)).
