### ISSUE TITLE
Restore snap publishing on snapcraft

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs-shipyard/ipfs-desktop#1551]
This is a placeholder for me to tackle this. 
Snap publishing was removed because of https://github.com/ipfs-shipyard/ipfs-desktop/pull/1547 : it was at the wrong place and it unpolitely interrupted testing.

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by jessicaschilling** [comment]
@bertrandfalguiere - do you mind adding the appropriate labels to this issue when you get a chance? You can see details of the labeling system here: https://github.com/ipfs/community/blob/master/ISSUE_LABELS.md
Thanks!

**Comment by bertrandfalguiere** [comment]
I don't mind, but I think I don't have the right for it? 

I think this could be 
priority/P2
kind/enhancement or king/maintenance
need/community-input
dif/easy
effort/hours
status/in-progress
topic/package-manager

I can be assigned too, but I don't think I have the rights either.

**Comment by jessicaschilling** [comment]
@bertrandfalguiere, I'm sorry about the permissions! Thanks for that list. I added the labels and assigned you. 😊

**Comment by olizilla** [comment]
The lowest friction route here seems to be adopting a snapcraft.yml file into this repo, and letting the snapstore build infra build out the snap files for us, and then promote new releases to the stable channel via the snapstore ui. I love full automation, but the periodic build failure from stale credentials will get annoying.

**Comment by lidel** [comment]
We are already publishing generic `.tar.xz` at well-known URLs:
- https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.12.1/ipfs-desktop-0.12.1-linux-x64.tar.xz

I believe we could go https://snapcraft.io/docs/pre-built-apps route and reuse prebuilt `.tar.xz`
That way Snap would be just thin wrapping on top of original artifact built by us.

**Comment by bertrandfalguiere** [comment]
@olizilla slayed the snap dragon for go-ipfs in https://github.com/ipfs/go-ipfs/issues/7250#issuecomment-658791975
 🛡🗡🐉!

Now it's a matter of time to install ipfs-desktop from the default app store of Ubuntu, right?

**Comment by lidel** [comment]
@bertrandfalguiere yes, but it's a low priority for the team (limited bandwidth).

If anyone has time to create a PR to try approach from https://github.com/ipfs-shipyard/ipfs-desktop/issues/1551#issuecomment-658828753 I'd be happy to test and review.
