### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by delgyd** [ipfs-shipyard/ipfs-desktop#1553]
When adding files, it is best to add a simple authentication parameter

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by olizilla** [comment]
@delgyd could you give some more information on the problem you are seeing, or feature you are proposing?

**Comment by delgyd** [comment]
ipfs add -auth password file.txt   ( file.txt:123456)
hash：xxxxxxxxxxxxxx
ipfs cat xxxxxxxxxxxxxx    -> (asgjewrjwfslf)
ipfs cat -auth password xxxxxxxxxxxxxx    --->(123456)

**Comment by olizilla** [comment]
That looks like a proposal for encrypting files as you add them to IPFS. It's a good idea. The discussion for that is over here https://github.com/ipfs/notes/issues/270

This issues on this repo (https://github.com/ipfs-shipyard/ipfs-desktop) are for discussing bugs and features with the desktop app. Encrypting files / password protecting would need to be supported by the core implementations (go-ipfs, js-ipfs).

To set expectations, we want to support encrypting files, but currently no one is working on it.
