### ISSUE TITLE
Which version of windows

### ISSUE THREAD

**Issue by TekBear** [ipfs-shipyard/ipfs-desktop#1565]
Reading main page and I cannot determine what OS versions you support - perhaps you could fix that if not already covered.
Which versions of Windows OS will run IPFS -desktop and is the answer the same for the command line ?

**Comment by jessicaschilling** [comment]
Hi @TekBear -- apologies for any runaround, but this is a great question for the forums: https://discuss.ipfs.io/
Mind asking there? Thanks!

**Comment by TekBear** [comment]
@jessicaschilling ok I have just posted question. This is my first look at your project and I think you should be precise about which windows version are supported on your main page -  https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/README.md the majority of projects do this. This is a documentation issue that needs fixing.
