### ISSUE TITLE
ipfs-desktop 0.12.0 uses go-ipfs 0.5.1

### ISSUE THREAD

**Issue by Evanito** [ipfs-shipyard/ipfs-desktop#1569]
- OS: Windows 10, 64-bit
 - Version of IPFS Desktop 0.12.0

**Describe the bug**
UI states that despite upgrading my IPFS Desktop today using the autoupdater, I am still using go-ipfs 0.5.1

**To Reproduce**
1. Update from ipfs-desktop 0.11.4 to 0.12.0 on Windows 10
2. Go to Status page on webui
3. See go-ipfs version, observe out of date

**Expected behavior**
I expect the current version to state 0.6.0

**Screenshots**
![image](https://user-images.githubusercontent.com/5620666/86639072-3218c700-bf8d-11ea-950a-44adff7ed369.png)
![image](https://user-images.githubusercontent.com/5620666/86639097-39d86b80-bf8d-11ea-9e8f-94423ff74f10.png)

**Additional context**
~~I assume a clean reinstall would solve this problem but that is not an ideal solution for me.~~
Running the installer again did not solve issue.

[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4881106/combined.log)

**Comment by jessicaschilling** [comment]
@olizilla, might you be able to triage this? Thanks!

**Comment by lzsaver** [comment]
> I assume a clean reinstall would solve this problem but that is not an ideal solution for me.
No, all ipfs-desktop 0.12.0 releases for all platforms contain the ipfs 0.5.1 binary.

I also want to note that the release for freebsd contains the binary for linux instead of freebsd one.

**Comment by lzsaver** [comment]
> I assume a clean reinstall would solve this problem but that is not an ideal solution for me.

No, all ipfs-desktop 0.12.0 releases for all platforms contain the ipfs 0.5.1 binary.

------

Also I want to note that the release for freebsd contains a binary for linux instead of freebsd one.
But the package contains the word "_linux_" in its name, so not sure how this is designed to work.
If you know that this was done by mistake - feel free to create a separate PR for this problem.

**Comment by lidel** [comment]
This happened before, but we assumed human error. 
Seems there is a bug in our CI flow, build for v0.12.0 indeed included go-ipfs 0.5.1:

* https://travis-ci.com/github/ipfs-shipyard/ipfs-desktop/jobs/358080971#L226

**Comment by Evanito** [comment]
No longer experiencing in 0.12.1
