### ISSUE TITLE
Failed to download fs-repo-migrations

### ISSUE THREAD

**Issue by zhyuzh3d** [ipfs-shipyard/ipfs-desktop#1576]
## Cant Start...

```
2020-07-11T03:26:35.249Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.6.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Found outdated fs-repo, migrations need to be run.
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Failed to download fs-repo-migrations.
The migrations of fs-repo failed:
  failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions": dial tcp 78.16.49.15:443: i/o timeout
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
 

 Error: failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions": dial tcp 78.16.49.15:443: i/o timeout 

 Command failed with exit code 1: /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon --migrate --enable-gc --routing dhtclient
Error: failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions": dial tcp 78.16.49.15:443: i/o timeout
Initializing daemon...
go-ipfs version: 0.6.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Found outdated fs-repo, migrations need to be run.
  => Looking for suitable fs-repo-migrations binary.
  => None found, downloading.
  => Failed to download fs-repo-migrations.
The migrations of fs-repo failed:
  failed to find latest fs-repo-migrations: http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions": dial tcp 78.16.49.15:443: i/o timeout
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
 


    at makeError (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/ipfsd-ctl/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/ipfsd-ctl/node_modules/execa/index.js:114:26)
```

**Comment by jessicaschilling** [comment]
@olizilla, can you kindly triage?

**Comment by olizilla** [comment]
@zhyuzh3d are you able to open https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions in a browser? it should show a list of version numbers.

The error was go-ipfs tried to automatically update an existing ipfs repo, but failed to fetch the update tool. This is an error that could happen due to local network issues, or if the gateway is down, so we should follow up with an enhancement to improve the error handling here. There isn't much we can do to side step it, an old repo must be upgraded... the user could be offered the option of deleting the old repo and starting from scratch, or manually fetching the update tool, or diagnosing the network issue.

**Comment by dwebfan** [comment]
same here, seems like ipfs can not start after upgrading to the latest version at MAC OS

**Comment by lidel** [comment]
@dwebfan this new error looks exactly the same as #1773.
Are you running any firewall/antivirus software than could be responsible for intercepting web traffic?
Or behind something like The Great Firewall of China?

**Comment by exaos** [comment]
The same error here. I' behind the GFW of China. :-(

**Comment by lidel** [comment]
@exaos please try workaround described in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1773#issuecomment-789294333
(I'm closing this issue as duplicate, lets continue in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1773)

**Comment by dwebfan** [comment]
> @dwebfan this new error looks exactly the same as #1773.
> Are you running any firewall/antivirus software than could be responsible for intercepting web traffic?
> Or behind something like The Great Firewall of China?

Neither any firewalls/antivirus software nor GFW

**Comment by cybertriton** [comment]
Same here. Behind GFW but has a VPN running.
-----------
Initializing daemon...
go-ipfs version: 0.10.0
Repo version: 11
System version: amd64/darwin
Golang version: go1.16.8
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] y
Looking for suitable migration binaries.
Need 5 migrations, downloading.
Downloading migration: fs-repo-6-to-7...
Downloading migration: fs-repo-7-to-8...
Downloading migration: fs-repo-8-to-9...
Downloading migration: fs-repo-9-to-10...
Downloading migration: fs-repo-10-to-11...
Fetching with HTTP: "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-10-to-11/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-8-to-9/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-9-to-10/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-7-to-8/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-6-to-7/versions"
Fetching with IPFS: "fs-repo-9-to-10/versions"
Fetching with IPFS: "fs-repo-8-to-9/versions"
Fetching with IPFS: "fs-repo-7-to-8/versions"
Fetching with IPFS: "fs-repo-6-to-7/versions"
Fetching with IPFS: "fs-repo-10-to-11/versions"
could not get latest version of migration fs-repo-6-to-7: 2 errors occurred:
	* http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-6-to-7/versions": dial tcp 67.15.129.210:443: i/o timeout
	* context deadline exceeded

could not get latest version of migration fs-repo-9-to-10: 2 errors occurred:
	* http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-9-to-10/versions": dial tcp 67.15.129.210:443: i/o timeout
	* context deadline exceeded

could not get latest version of migration fs-repo-7-to-8: 2 errors occurred:
	* http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-7-to-8/versions": dial tcp 67.15.129.210:443: i/o timeout
	* context deadline exceeded

could not get latest version of migration fs-repo-10-to-11: 2 errors occurred:
	* http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-10-to-11/versions": dial tcp 67.15.129.210:443: i/o timeout
	* context deadline exceeded

could not get latest version of migration fs-repo-8-to-9: 2 errors occurred:
	* http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmP7tLxzhLU1KauTRX3jkVkF93pCv4skcceyUYMhf4AKJR/fs-repo-8-to-9/versions": dial tcp 67.15.129.210:443: i/o timeout
	* context deadline exceeded

Failed to download migrations.
The migrations of fs-repo failed:
  failed to download migrations: fs-repo-6-to-7 fs-repo-7-to-8 fs-repo-8-to-9 fs-repo-9-to-10 fs-repo-10-to-11
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
migration peer 12D3KooWB73YV5BCLhz7scT2mgL7W3WQ7cVo1yfRnRYQNUwL9PfZ shutdown

Error: failed to download migrations: fs-repo-6-to-7 fs-repo-7-to-8 fs-repo-8-to-9 fs-repo-9-to-10 fs-repo-10-to-11

**Comment by jbenet** [comment]
Same here
```
> ipfs-update install latest
ERROR: error resolving 'latest':  http.DefaultClient.Do error: Get https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: x509: certificate has expired or is not yet valid
```

Maybe there's something wrong w/ SSL cert somewhere?

**Comment by jbenet** [comment]
I got something similar downloading `go-ipfs` w/ `ipfs-update`
```
> ipfs-update install latest
ERROR: error resolving 'latest':  http.DefaultClient.Do error: Get https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: x509: certificate has expired or is not yet valid
```

Maybe there's something wrong w/ SSL cert somewhere?

**Comment by lidel** [comment]
@jbenet  this  `x509: certificate has expired` error  could be: 
-  an old cert on ipfs.io deployed by mistake  (seems to be fixed now), 
- or your local clock being set to a date in past (happens sometimes when laptop is losing charge + there is no backup battery on mainboard).



@cybertriton this looks odd, go-ipfs 0.9 and later should try fetching migrations over IPFS when HTTPS fails: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#migration
