### ISSUE TITLE
IPFS Desktop Applet "remote mode"

### ISSUE THREAD

**Issue by kallisti5** [ipfs-shipyard/ipfs-desktop#1586]
**Is your feature request related to a problem? Please describe.**

Is it possible to configure a remote ipfs node in the desktop application?  I'm running IPFS on my NAS, and exposing all the correct ports from there.

Running the local desktop client, and adjusting the ipfs config to point at it doesn't seem to cover this. Adding files to IPFS locally puts them into ~/.ipfs and doesn't seem to leverage my NAS?

**Describe the solution you'd like**

Ability for the desktop app to function in a "headless" mode controlling a remote ipfs gatway.

**Config**

Here's the config i tried.  192.168.1.10 is my remote ipfs node. The ports are correct for each service

```json
{
	"API": {
		"HTTPHeaders": {}
	},
	"Addresses": {
		"API": "/ip4/192.168.1.10/tcp/5001",
		"Announce": [],
		"Gateway": "/ip4/192.168.1.10/tcp/48080",
		"NoAnnounce": [],
		"Swarm": [
			"/ip4/0.0.0.0/tcp/4001",
			"/ip6/::/tcp/4001"
		]
	},
	"AutoNAT": {},
.
.
```

**Comment by jessicaschilling** [comment]
@olizilla, would you be able to triage? Thanks!

**Comment by olizilla** [comment]
No. IPFS Desktop is designed to control the local ipfs daemon that it installs.

You may be able to get the remote control behaviour you want by using the webui... if you update your ipfs config on your `192.168.1.10` node with the changes you show above, and include a CORS allow-origin header for the api like

```
	"API": {
		"HTTPHeaders": {
			"Access-Control-Allow-Origin": [
				"http://192.168.1.10:5001"
                        ]
```

then you could load the webui on your local network via http://192.168.1.10:5001/webui

I'm gonna close this out as this is not a feature that is supported on the Desktop app

For more info see: 
- https://github.com/ipfs-shipyard/ipfs-webui#configure-ipfs-api-cors-headers
- https://github.com/ipfs-shipyard/ipfs-webui/issues/836
