### ISSUE TITLE
Can I delete blocks in order to save disk storage space?

### ISSUE THREAD

**Issue by penismonsters** [ipfs-shipyard/ipfs-desktop#1589]
Hi, I'm new to using IPFS, I currently IPFS Desktop 0.12.2 on Windows 10. i was attracted to IPFS because I heard that you could store large datasets on it. So I started using it and I uploaded a 1GB file. I then went to my .ipfs file and saw the blocks folder I took a look and it appears that there is data stored in individual 257KB file. Now obviously if I am to add more data these will accumulate. So is it possible that I could delete them or maybe some of them in order to save storage space in the future?

**Comment by jessicaschilling** [comment]
Hi there -- we're actually using the IPFS forums at https://discuss.ipfs.io/ for questions of this nature. Can you please post your question there? Thank you!
