### ISSUE TITLE
The desktop app asked to update to a new version. From there everything went wrong.

### ISSUE THREAD

**Issue by dickvangelder** [ipfs-shipyard/ipfs-desktop#1592]
- OS: Windows 10
 - Version of IPFS Desktop latest

After installing the update to the latest version, it could not connect anymore and asked to modify lines in the config file?

So I uninstalled the application and reinstalled the latest version. 
I attached the error Log 

[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4977392/error.log)

**Comment by jessicaschilling** [comment]
@rafaelramalho19, can you please triage? Thank you!

**Comment by dickvangelder** [comment]
I made a second attempt this morning.
the IPFS-desktop version is 0.12.2
the go-ipfs version is 0.6.0
![image](https://user-images.githubusercontent.com/2052313/88526236-f907cb80-cffb-11ea-9568-b0092c92c357.png)

new error.log
[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4981131/error.log)

**Comment by rafaelramalho19** [comment]
Hi @dickvangelder, seems like you closed the issue. Were you able to fix this?

**Comment by dickvangelder** [comment]
> Hi @dickvangelder, seems like you closed the issue. Were you able to fix this?

If I gave the impression that the issue is closed, i’m sorry.

No I still face the problem that although it the app seems to load, the icon is greyed out and tells me that it has errored.

**Comment by rafaelramalho19** [comment]
I'm sorry this is happening to you.

Can you try what I described here? https://github.com/ipfs-shipyard/ipfs-desktop/issues/1585#issuecomment-660503103

**Comment by rafaelramalho19** [comment]
@dickvangelder it's really weird that you're still having errors...

Can you access https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions in your machine?

**Comment by dickvangelder** [comment]
> @dickvangelder it's really weird that you're still having errors...
> 
> Can you access https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions in your machine?

Can you guide me in which folder i should look for this?

**Comment by lidel** [comment]
@dickvangelder Just try to open [this](https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions) link in your web browser – does it work (you should see list of versions)?
Is your machine or network running firewall that could block traffic to https://ipfs.io?

**Comment by dickvangelder** [comment]
> @dickvangelder Just try to open [the link](https://ipfs.io/ipfs/Qmdo5m6bpQXCayzfGghyvgXJdVHSsXsCKDUo9vWktDKq3K/fs-repo-migrations/versions) in your web browser – does it work (you should see list of versions)?
> Is your machine or network running firewall that could block traffic to https://ipfs.io?

v1.0.0
v1.1.0
v1.1.1
v1.2.0
v1.2.1
v1.2.2
v1.3.0
v1.4.0
v1.5.1
v1.6.1
v1.6.2
v1.6.3

**Comment by lidel** [comment]
Autoupdate issues on Windows 10 were fixed in [v0.13.1](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.1), you can use it for testing upgrade to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2).
