### ISSUE TITLE
localhost:8080/ipfs/<CID> redirects to <CID>.ipfs.localhost:8080 which fails on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [ipfs-shipyard/ipfs-desktop#1595]
- OS: Windows
 - Version of IPFS Desktop: 0.12.2

**Describe the bug**
Navigating to `localhost:8080/ipfs/<CID>` redirects me to `<CID>.ipfs.localhost:8080` (this is a very good thing for security!), but that address doesn't actually work in my browser.

**To Reproduce**
1. Install IPFS Desktop on Windows 10.
2. Navigate to http://localhost:8080/ipfs/QmQy6xmJhrcC5QLboAcGFcAE1tC8CrwDVkrHdEYJkLscrQ
3. Notice that you were redirected to http://bafybeibhbx3y6tnn7q4gpsous6apnobft5jybvroiepdsmvps2lmycjjxu.ipfs.localhost:8080/
4. Be sad that you are getting a DNS error in your browser.

**Expected behavior**
The redirect is expected and desired as it greatly improves the security of running a web application via IPFS.  However, I expected that the domain would resolve correctly.

**Additional context**
I am aware that I can browser via `http://127.0.0.1:8080/ipfs/<CID>`, but that is not secure for running web apps that have important data saved in cookies/local storage.  I very much *want* to use the subdomains, and the automatic redirect is great.  However, it currently redirects me to a site that doesn't resolve.

**Comment by jessicaschilling** [comment]
@lidel and/or @rafaelramalho19 -- are you able to triage? Thank you!

**Comment by MicahZoltu** [comment]
It appears this works correctly in Chrome, but not in Firefox.

**Comment by lidel** [comment]
Closing this, as we already have upstream issue (more details there): https://github.com/ipfs/go-ipfs/issues/7527

Workaround for Firefox users is to install IPFS Companion: https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/ → @MicahZoltu give it a try!
