### ISSUE TITLE
stop daemon using UI or Linux tray icon

### ISSUE THREAD

**Issue by SvenMeyer** [ipfs-shipyard/ipfs-desktop#1611]
On linux , I have the option to "close" ipfs-desktop, but that only closes the UI, the daemon is still running in the background (what is causing problems in my case). There should be an option to stop the daemon as well , and also stop the service from automatically re-starting after a reboot

**Comment by jessicaschilling** [comment]
Thanks, @SvenMeyer -- as you've seen, we're discussing this in #1522. Closing this issue in favor of that already-open one.
