### ISSUE TITLE
"add" should say "import"

### ISSUE THREAD

**Issue by thibaultmol** [ipfs-shipyard/ipfs-desktop#1617]
It's a silly small thing. But in the desktop client it refers to 'add', but the button is called Import
![image](https://user-images.githubusercontent.com/1010226/91232565-9f480d80-e72f-11ea-9c67-d3a3edd20acc.png)

**Comment by jessicaschilling** [comment]
Hi @thibaultmol -- thanks for noticing this! It's actually been fixed upstream in [this PR](https://github.com/ipfs-shipyard/ipfs-webui/pull/1571#issue-459655075), but we're waiting for a few other changes before cutting a new release of Web UI (which in turn feeds IPFS Desktop). Watch this space!
