### ISSUE TITLE
Erroneous error message when pinning files

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/ipfs-desktop#1623]
- OS: MacOS 10.15.3
 - Version of IPFS Desktop: 0.12.2

**Describe the bug**
When I pin a file in the Files tab, an error message appears: "Failed to process your request. Please try again." The file still gets a pin icon next to it, and appears when I run `ipfs pin ls`. If I unpin the file in the Desktop UI, I get the same error message, and the pin icon next to the file name disappears. This happens to all files I upload.

**To Reproduce**
1. Go to the Files tab
2. Import a file
3. Click the '...' by the file and select "Pin."

**Expected behavior**
No error message if the pin is successful. If it's not successful, no pin icon to appear by the file name.

**Screenshots**
![image](https://user-images.githubusercontent.com/11778450/91884733-70ec9580-ec3b-11ea-90c3-98b52ee3fd01.png)

**Additional context**

**Comment by jessicaschilling** [comment]
Thanks, @dchoi27 -- we will get this into our next triage session!

**Comment by lidel** [comment]
This should be addressed by https://github.com/ipfs-shipyard/ipfs-webui/pull/1599 and ipfs-webui v2.11 (when released)

**Comment by jessicaschilling** [comment]
@dchoi27 - can you please try this with 2.11 at your leisure and see if issue is resolved?
