### ISSUE TITLE
error

### ISSUE THREAD

**Issue by humm0** [ipfs-shipyard/ipfs-desktop#1625]
Please describe what you were doing when this error happened.
Searching the web
**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.0
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by jessicaschilling** [comment]
Thanks, @humm0 - we'll queue this up in our next weekly triage session.

**Comment by lidel** [comment]
@humm0 thank you  for reporting the issue.
We noticed you are running very old version (0.9.0), please upgrade to the latest version ([0.12.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.12.2)) and  reopen if this is still the case.
