### ISSUE TITLE
IPFS Desktop - Folders not uploading

### ISSUE THREAD

**Issue by gohub12** [ipfs-shipyard/ipfs-desktop#1627]
- OS: macOS, Catalina 10.15.6
 - Version of IPFS Desktop 0.12.2

**Describe the bug**
The desktop downloads and installs. Importing individual files one at a time seems to work fine. I was also able to upload a couple of folders but then I continually get the message "Failed to add files to IPFS. Please try Again. 

<img width="647" alt="Screen Shot 2020-09-02 at 7 34 21 AM" src="https://user-images.githubusercontent.com/69581936/92112560-f8611280-edbb-11ea-8181-302578890723.png">

I have tried dragging and dropping folders. When I drag my folders I get the green "+" sign and it looks like I am good but then it fails. I use the upload button with the same effect.

Also, I have tried with small folders and large folders. Same result.

**To Reproduce**
1. In the Files tab click the Import button 
2. Select Folder
3. Select the desired folder and click Open
4. Depending on the folder size there is a wait time and then the error message "Failed to add files to IPFS. Please try again." 

**Additional context**
I use a VPN, could that be affecting anything? Also, I have tried this with locally saved folders on my hard drive as well as folders saved in the cloud. Same result.

<img width="1280" alt="Screen Shot 2020-09-03 at 7 57 57 AM" src="https://user-images.githubusercontent.com/69581936/92112622-1595e100-edbc-11ea-8ef4-b20451052b2d.png">

<!-- 
ATTACH LOGS

**Comment by jessicaschilling** [comment]
Hi @gohub12 - thanks for flagging this. A few quick questions:
- Are you able to add files/directories successfully [via the command line](https://docs.ipfs.io/reference/cli/#ipfs-add)?
- Are you trying to add particularly large files/directories? There's a known issue in Desktop with items over 2GB, but a fix is very near.

**Comment by gohub12** [comment]
Hi Jessica,

The size of the folders I have been trying to move are 750 MB and 2.2 GB. I just tried a small folder (750 KB) and it copied no problem. 

I have not tried the command line but I will and let you know if that works for larger folders. 

Thanks. 

Rob Harper (gohub12)
Tel: (416)451-3509
Email: rob.harper550@gmail.com

On Sep 3, 2020, at 12:00, Jessica Schilling <notifications@github.com> wrote:

﻿
Hi @gohub12 - thanks for flagging this. A few quick questions:

Are you able to add files/directories successfully via the command line?
Are you trying to add particularly large files/directories? There's a known issue in Desktop with items over 2GB, but a fix is very near.

**Comment by jessicaschilling** [comment]
@gohub12 -- thanks for the info. I'm ccing @lidel and @rafaelramalho19 for more context, but we may be running into the large-file issue here. Let us know how you get by with the command line, and apologies for the inconvenience; it'll be temporary!

**Comment by lidel** [comment]
This was fixed in https://github.com/ipfs-shipyard/ipfs-webui/pull/1534 and  is scheduled to be fixed in v2.11
