### ISSUE TITLE
Typo in IPFS config property Discovery.MDNS.Enabled

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#1631]
`Enabled` should start with a capital `E` in `Discovery.MDNS.Enabled`, as per https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#discoverymdnsenabled

Currently ipfs-desktop sets the property name to be `enabled`
https://github.com/ipfs-shipyard/ipfs-desktop/blob/c387c4f4b2acd2cdc616cc326a9bbfb092d1c3da/src/daemon/config.js#L55

as discovered by @daviddias 

![image(3)](https://user-images.githubusercontent.com/58871/92505457-053a9780-f1fc-11ea-952a-5499c878b4be.png)

**Comment by jessicaschilling** [comment]
@rafaelramalho19 and/or @lidel, please have a look if we want to prioritize this above the weekly triage. Thanks!

**Comment by rafaelramalho19** [comment]
Thanks for opening the issue @olizilla, will address this now
