### ISSUE TITLE
Downloading a file results in a corrupted archive

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#1639]
- OS: Windows 10 Pro x86_64
 - Version of IPFS Desktop: 0.12.2

**Describe the bug**

Downloading a file results in a corrupted archive.

**To Reproduce**

1. Download something
2. Open it

**Expected behavior**

1. The downloaded file shouldn't be compressed
2. The downloaded file should be usable
3. It would be nice to have progress reporting via https://github.com/ipfs/go-ipfs/issues/7672 🤗

**Screenshots**

![image](https://user-images.githubusercontent.com/10495562/92944759-63e15a80-f422-11ea-8463-27b125c89595.png)

![image](https://user-images.githubusercontent.com/10495562/92944825-7b204800-f422-11ea-9114-cf36fa8ff250.png)

**Additional context**

When I download via BitTorrent, the download files aren't compressed. This makes BitTorrent infinitely easier to download with than IPFS Desktop at the moment.

1. Not everyone is able to open `.tar.gz`
2. I don't have the time to download+compress+decompress 10 GB. Let's just skip the useless compress+decompress part, please!

**Comment by jessicaschilling** [comment]
Thanks @NatoBoram - we will bring this up in our next weekly triage.

**Comment by rafaelramalho19** [comment]
@NatoBoram I had issues in the past with 7-zip and tar.gz files, maybe try decompressing it with winrar or similar software?

Anyway, we discussed the possibility of creating a setting that disables/enables compression on downloaded files, so it can be a possible fix for your issue in future versions of webui.

**Comment by NatoBoram** [comment]
Issues with 7-zip can be reported [here](https://sourceforge.net/p/sevenzip/bugs/). 

I also found the downloaded archive to all have the same size despite representing different files, so I'm not sure if any program could open it.

**Comment by jessicaschilling** [comment]
Hi @NatoBoram -- we just added https://github.com/ipfs-shipyard/ipfs-webui/issues/1629 for discussion/implementation of improving Web UI handles download of multiple files/folders.

Closing this issue with that in mind -- however, if you're able to try @rafaelramalho19's suggestion above and confirm that using another decompression tool results in usable files, that would be helpful. If you are indeed getting corrupted files (and it's not just a 7-zip problem), please re-open. Thank you!

**Comment by NatoBoram** [comment]
Tested with `tar`.

```log
$ tar -xvzf Test.tar.gz
tar (child): \302\226Test.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Tested with `7z`.

```log
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 25 bytes (1 KiB)

Extracting archive: .\Test.tar.gz
ERROR: .\Test.tar.gz
.\Test.tar.gz
Open ERROR: Can not open the file as [gzip] archive


ERRORS:
Is not archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```

* ipfs://bafybeieo32rknzpc76mubirgsh6benjjthrzgq2wctvcgrego3ae4ewjlu
* [Test.tar.gz](https://github.com/ipfs-shipyard/ipfs-desktop/files/5225463/Test.tar.gz)

**Comment by lidel** [comment]
Ok, the problem here is that your browser (Electron renderer) does not handle `405 - Method Not Allowed` error properly, and instead downloads the error under the name `Test.tar.gz` - I think that is an undesired behavior of Electron. 

Good news is that this bug will be fixed in next release when https://github.com/ipfs-shipyard/ipfs-desktop/pull/1638 is merged, so all you need to do is wait for new release.
