### ISSUE TITLE
Menu items for enabling pubsub and automatic GC

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1647]
I was looking into starting go-ipfs with additional flags: [`--enable-pubsub-experiment`](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-pubsub) (pubsub) and  [`--enable-namesys-pubsub`](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipns-pubsub) (IPNS over pubsub) and the main concern I've found was use of resources:

> In order to enable pubsub by default in go-ipfs, we need to find some way for pubsub to not take up a bunch of resources when not in-use.
> – https://github.com/libp2p/go-libp2p-pubsub/issues/332

So if we want pubsub and fast IPNS enabled, we need to pay the cost of higher resource utilization.
We could measure it and decide if its worth the added value, or prioritize a fix.

**Updated:** or at the very least, we could give user UI for enabling that with one click

**Updated again:** See mockup for placement of menu items for pubsub and automatic GC (note this also includes not-yet-implemented "Ask when opening" menu item, likely to land first in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1646)
![image](https://user-images.githubusercontent.com/1507828/93796230-c5aa7d00-fbf7-11ea-98ac-de36c3018e4b.png)

@aschmahmann are there any other concerns that I don't see?

@autonome FYSA this also impacts go-ipfs in Brave, especially the speed of `ipns://`

**Comment by shaikh-shahid** [comment]
I think if we have a UI based switch to turn on/off the flags such as Pubsub and GC etc then that would be better for end users as well. I am currently working on a framework that does require IPFS in the backend and needs the PUBSUB to be enabled. Since the framework also consists of demos for general public as well, it's difficult for users to find the configuration and update the flags.

**Comment by lidel** [comment]
@shaikh-shahid that is very useful feedback, thank you.

I think we could avoid enabling pubsub by default by adding  on/off checkbox settings for pubsub (and automatic GC) to the Desktop app menu. Toggling would automatically restart the deamon with the new setting.

**Comment by jessicaschilling** [comment]
Note: Added mockup of menu item placement in [original comment](https://github.com/ipfs-shipyard/ipfs-desktop/issues/1647#issue-702650415). 

Unless @aschmahmann or @autonome have objections, I believe this is ready to work.

**Comment by andrew** [comment]
Here to eco @shaikh-shahid's comment, I'm working on a project that needs pubsub to be enabled and if they are using ipfs desktop, it's is not a friendly user experience.

**Comment by lidel** [comment]
@andrew I don't think we can enable it by default when its marked as experiment in go-ipfs, but we could prioritize adding the opt-in via menu visible in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1647#issue-702650415. 
Would that work for you?

**Comment by andrew** [comment]
Yeah not asking for it on by default but for a user to be able to set the option via desktop

**Comment by andrew** [comment]
Opened a pull request to add the pubsub option: https://github.com/ipfs-shipyard/ipfs-desktop/pull/1735 

If that goes well then I'll open another with the automatic GC option.

**Comment by lidel** [comment]
Two thoughts:
- We should keep pubsub items under Experiments section (its still listed as an experiment in go-ipfs docs)
- There is a separate experiment called  "IPNS over PubSub" ([docs](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipns-pubsub)),  but I think it should this be a separate flag, as it comes with additional overhead (afaik subscriptions are not purged)

**Comment by andrew** [comment]
PRs for the other to menu items mentioned here: https://github.com/ipfs-shipyard/ipfs-desktop/pull/1739 and https://github.com/ipfs-shipyard/ipfs-desktop/pull/1740
