### ISSUE TITLE
implement cluster-follow

### ISSUE THREAD

**Issue by strelok899** [ipfs-shipyard/ipfs-desktop#1648]
it much more user friendly and conviniet to have the ability to join cluster and help to redistribute IPFS from windows PC's
and it can be easily implemented by community.

**Comment by jessicaschilling** [comment]
Thanks, @strelok899! We'll discuss in our next weekly triage.

**Comment by jessicaschilling** [comment]
Issue https://github.com/ipfs/ipfs-gui/issues/59 already exists - closing this one for the sake of consolidation.
