### ISSUE TITLE
Smoke-testing IPFS Desktop v0.13.0 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1661]
> We now have new a brand CI/CD pipeline responsible for building IPFS Desktop (#1657, #1659).
> Before we ship v0.13, let's have more eyes on platform-specific packages.

## Help us by doing a quick test of IPFS Desktop v0.13.0 

If you have spare time between now and Monday (~5min):

1. Install IPFS Desktop using package listed below
2. Go to _Files_ and _Import_ a folder with some cat pictures
3. You should be able to see successfully imported files in your _Files_ screen
4. Comment on this issue with package name and if it went smoothly or  if you had any issues.

## RC2 build @ f2f34bfde7e46998ff915de5630da2914e7225e2

https://bafybeiamxdw3qlecv2mryeojfn46kv32t3nt2a6zajm6wotjadznrtvutm.ipfs.dweb.link/ipfs-desktop-0.13.0-rc2

## RC1 build @ 2cfd2f4f7a417fa371e543416a79e5a40971d137

<details>
  <summary>Click to expand</summary>

### macOS

- [x] [IPFS-Desktop-0.13.0.dmg](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/IPFS-Desktop-0.13.0.dmg) @jessicaschilling  @olizilla 

### Windows 

- [x] [IPFS-Desktop-Setup-0.13.0.exe](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/IPFS-Desktop-Setup-0.13.0.exe) @johnnymatthews @lidel 

### Linux

If you happen to run Linux, make sure to include the name of distro and Desktop Environment you are running.

- [x] [ipfs-desktop-0.13.0-linux-x64.tar.xz](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/ipfs-desktop-0.13.0-linux-x64.tar.xz) (@lidel: unpacked standalone version runs as expected)
- [x] [ipfs-desktop-0.13.0-linux-amd64.deb](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/ipfs-desktop-0.13.0-linux-amd64.deb) @bertrandfalguiere
- [ ] [ipfs-desktop-0.13.0-linux-x86_64.rpm](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/ipfs-desktop-0.13.0-linux-x86_64.rpm)
- [x] [ipfs-desktop-0.13.0-linux-x86_64.AppImage](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/ipfs-desktop-0.13.0-linux-x86_64.AppImage) @bertrandfalguiere 
- [x]  [ipfs-desktop-0.13.0-linux-amd64.snap](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/ipfs-desktop-0.13.0-linux-amd64.snap) @bertrandfalguiere
- [ ] [ipfs-desktop-0.13.0-linux-x64.freebsd](https://bafybeianbwepwyb5jglfbtxy74spitvhku5vjgwclemb4rolasw256hfda.ipfs.dweb.link/ipfs-desktop-0.13.0-rc1/ipfs-desktop-0.13.0-linux-x64.freebsd)

</details>

----

![office-bat](https://user-images.githubusercontent.com/157609/94970356-ccdd5f00-0504-11eb-8ca1-33d60416071f.png)
_Our team will be back on Monday, 
ready to squash any bugs blocking the release_

closes #1153

**Comment by jessicaschilling** [comment]
Mac here. All worked as expected for importing both via `Import > Folder` and just drag/drop, except the drawer gave me an "NaN" while uploading:

![image](https://user-images.githubusercontent.com/1507828/94972025-887e9e80-04c5-11eb-9cea-99e078603e8d.png)

**Comment by bertrandfalguiere** [comment]
Tested .deb on Ubuntu 20.04 stock version.

Import button and dragging on Files screen both work as expected, except I got cheese NaNed like @jessicaschilling .
![image](https://user-images.githubusercontent.com/8818223/94987824-7d7d4a00-0569-11eb-9378-1c221ca8062d.png)

(Fur your infurmation, it wasn't a cat picture pur say, so your mileage meow vary.)

**Comment by bertrandfalguiere** [comment]
Snap: same story
![image](https://user-images.githubusercontent.com/8818223/94988864-ad7c1b80-0570-11eb-969c-8f5a0491d570.png)


Worth noting: My previously addded files and folders are not available.
I think it's because snap sets up its own repository, isolated from other apps...

**Comment by olizilla** [comment]
`IPFS-Desktop-0.13.0.dmg` - it went smoothly. 

- Importing a directory worked but showed `Imported NaN Items` as mentioned above, for both import via menu option and import via file drop.

<img width="805" alt="Screenshot 2020-10-03 at 15 31 01" src="https://user-images.githubusercontent.com/58871/94994163-d5c64300-058d-11eb-80ca-cb0be54102b8.png">

**Comment by lidel** [comment]
I managed to get hold on Windows 10 laptop  and both  installing for single user and globally on the OS seems to work as expected. Binary is signed.

**Comment by johnnymatthews** [comment]
Worked fine on Windows 10 (1809). Got a message saying **Imported NaN items** after adding a file, but apart from that everything was fine.

**Comment by lidel** [comment]
Thank you all! :pray: 

I've filled https://github.com/ipfs-shipyard/ipfs-webui/issues/1659 for the `NaN` thing. It is not related to Electron, but  a ux bug in webui (confirmed it in Firefox).

While `NaN` looks bit awkward, it is shown only when more than one file was imported.
I don't think this small UX nit should block the release that ships go-ipfs 0.7.0. 

@jessicaschilling Let's discuss this later today during triage

**Comment by bertrandfalguiere** [comment]
Just tested .AppImage on Ubuntu 20.04

It worked once perfectly with import. Even without the NaN problem:
![image](https://user-images.githubusercontent.com/8818223/95098368-e5c95880-072e-11eb-8e79-b66ae90a1fde.png)

But most of the time there is the NaN/ 0/ 1 problem:
One dragged file:
![image](https://user-images.githubusercontent.com/8818223/95098504-0abdcb80-072f-11eb-8a3e-5651097560a1.png)

Sometime it displays this :
![image](https://user-images.githubusercontent.com/8818223/95098842-77d16100-072f-11eb-82e7-d93dd92b267a.png)
... then this after a few seconds :
![image](https://user-images.githubusercontent.com/8818223/95098881-861f7d00-072f-11eb-8bf8-bdb3f7ffcb12.png)

Other than that it works.

**Comment by jessicaschilling** [comment]
Update: @Gozala is troubleshooting - ideally we'd patch this before releasing a new Desktop, as it's a highly visible UX flaw even if it's not breaking functionality.

**Comment by lidel** [comment]
@Gozala  fixed the`NaN` bug (https://github.com/ipfs-shipyard/ipfs-webui/pull/1660), and we switched to webui v2.11.3 (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1666).


@jessicaschilling @johnnymatthews @bertrandfalguiere @olizilla 
please repeat the test using RC2 version from [ipfs-desktop-0.13.0-rc2/](https://bafybeiamxdw3qlecv2mryeojfn46kv32t3nt2a6zajm6wotjadznrtvutm.ipfs.dweb.link/ipfs-desktop-0.13.0-rc2) :pray:

**Comment by jessicaschilling** [comment]
`IPFS Desktop-0.13.0.dmg`: `NaN` issue is gone.

Note that I've filed https://github.com/ipfs-shipyard/ipfs-desktop/issues/1668 for less-than-ideal placement of Mac window controls vis-a-vis IPFS cube.

**Comment by bertrandfalguiere** [comment]
AppImage: OK
.deb: OK
.snap: must be installed with the `--dangerous` flag (I guess it won't be needed once on the snapstore?). Files are in a different place than with other installs, and the peer ID is different. Otherwise, OK

**Comment by lidel** [comment]
@bertrandfalguiere thank you! Yes, `--dangerous` won't be needed when it lands on snapstore. Snap has its own philosophy regarding paths, so those discrepancies are expected. 


@jessicaschilling  I've switched to webui [v2.11.4](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.11.4) with fix for https://github.com/ipfs-shipyard/ipfs-desktop/issues/1668. Electron had a bunch of security fixes, so I've also updated us to 9.3.2 and created RC3: 

## _Once more, with feeling.._


1. Install IPFS Desktop using package  from [`ipfs-desktop-0.13.0-rc3/`](https://bafybeieujzkl46w4nl2cungp2x56smonif3qylrienzaa7lbizs4q2wany.ipfs.dweb.link/ipfs-desktop-0.13.0-rc3/)
2. Go to _Files_ and _Import_ a folder with some cat pictures
3. You should be able to see successfully imported files in your _Files_ screen
4. Comment on this issue with package name and if it went smoothly or  if you had any issues.


## Release checklist

- [ ] Windows
- [x] Linux @lidel 
- [ ] macOS

**Comment by rafaelramalho19** [comment]
@lidel tested on MacOS and looks good 👍

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 Confirmed OK on MacOS here as well.

**Comment by lidel** [comment]
Thank you all for help! Shipping it to autoupdate channel.

**Comment by lidel** [comment]
[v0.13.0](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.0) :ship: :dash:
