### ISSUE TITLE
Make room for window controls in left nav

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-desktop#1668]
It's fine in Web UI, but in Desktop's standalone Electron window, the IPFS cube is too close to the window control buttons on a Mac. Margins were tightened to accommodate small screens in Web UI, so look into whether it's possible to restyle just for Electron standalone or if we need to add some additional margin universally.

![image](https://user-images.githubusercontent.com/1507828/95252165-d6ebb000-07d9-11eb-9c28-36e7d8d68099.png)

**Comment by lidel** [comment]
@rafaelramalho19 just removed Electron-specific code in https://github.com/ipfs-shipyard/ipfs-webui/pull/1628, so I'd vote for adding margin everywhere. 

Perhaps narrow margin around logo could be maintained for small screens with something like  `@media only screen and (max-height: SOMEpx)`?

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-webui/pull/1663 should take care of this (cc @lidel)
