### ISSUE TITLE
Automate Chocolatey updates

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1674]
@hacdias I tried to update the [Chocolatey package](https://chocolatey.org/packages/ipfs-desktop) manually via https://www.onitato.com/post/running-chocolatey-on-linux/ but it fails with

```
Attempting to build package from 'ipfs-desktop.nuspec'.
Cannot create a package that has no dependencies nor content.
```

Do you have a working setup around? What am I missing?
I'd like to automate this, perhaps via [manual Github Action trigger with `workflow_dispatch`](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) or something that happens after new release is published, but first step is to successfully do this by hand.

**Comment by hacdias** [comment]
I don't recall the full procedure, but I remember I only needed two commands:

- `choco pack` to build the .nuspec file
- and `choco push` to upload it to the server

I never had that error in my life. Maybe try using GitHub Actions with Windows for that?

**Comment by lidel** [comment]
Thanks. Yes, I think we should do something similar to https://github.com/ipfs-shipyard/ipfs-desktop/pull/1678
