### ISSUE TITLE
Auto-generated report: errors occurred upon startup

### ISSUE THREAD

**Issue by NeoGe-IPFSMain** [ipfs-shipyard/ipfs-desktop#1677]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: shell.openItem is not a function
    at click (C:\Users\Neo\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\tray.js:141:32)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by jessicaschilling** [comment]
Thanks, @NeoGe-IPFSMain. Are you able to successfully run Desktop despite this error?

**Comment by NeoGe-IPFSMain** [comment]
Hi, @jessicaschilling. No, I am not able to run it with this error.

**Comment by jessicaschilling** [comment]
@NeoGe-IPFSMain Thanks for the context -- please accept apology for having to run an earlier version in the meantime. @lidel and @rafaelramalho19 -- can you please have a look? Related to https://github.com/ipfs-shipyard/ipfs-desktop/issues/1570 perhaps?

**Comment by lidel** [comment]
@NeoGe-IPFSMain which menu item are you clicking before this error occurs?

**Comment by NeoGe-IPFSMain** [comment]
@jessicaschilling No worries! 

@lidel This is happening without any interactions. I double-clicked the IPFS Desktop shortcut on my desktop, but it refused to open. Right-click the icon on my taskbar, it shows "IPFS has Errored". 

It's been a while since the last time I used IPFS Desktop. I tried the restart and reinstall (not clean), this error remains.

**Comment by jessicaschilling** [comment]
@NeoGe-IPFSMain We're actively triaging this right now - are you OK in the meantime using the CLI, or the CLI as daemon plus webui.ipfs.io?

**Comment by NeoGe-IPFSMain** [comment]
@jessicaschilling CLI works fine. IPFS Desktop would be up running without an issue if I manually use any shell to run the IPFS daemon. But once I close the shell, IPFS Desktop will stop running and reporting the error.

**Comment by jessicaschilling** [comment]
@NeoGe-IPFSMain Thanks for the details - just wanted to make sure you weren't completely blocked while we worked on a fix.

**Comment by NeoGe-IPFSMain** [comment]
@jessicaschilling No worries, thanks!
