### ISSUE TITLE
Update faild so resintalled from here, added file clicked on noticiation

### ISSUE THREAD

**Issue by gyuri-lajos** [ipfs-shipyard/ipfs-desktop#1680]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: shell.openItem is not a function
    at Notification.<anonymous> (C:\Users\Zazie\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\common\notify.js:19:11)
    at Notification.emit (events.js:223:5)
```

**Comment by jessicaschilling** [comment]
Thanks, @gyuri-lajos - we're working on this in master issue https://github.com/ipfs-shipyard/ipfs-desktop/issues/1570 so will reference your report there, and close this issue.
