### ISSUE TITLE
Error while adding file

### ISSUE THREAD

**Issue by EmbALL** [ipfs-shipyard/ipfs-desktop#1685]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: shell.openItem is not a function
    at Notification.<anonymous> (C:\Program Files\IPFS Desktop\resources\app.asar\src\common\notify.js:19:11)
    at Notification.emit (events.js:223:5)
```

**Comment by jessicaschilling** [comment]
Hi - this is a known issue and is being worked in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1687.
