### ISSUE TITLE
Crash when click to "advanced -> open repository folder" 

### ISSUE THREAD

**Issue by EmbALL** [ipfs-shipyard/ipfs-desktop#1686]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: shell.openItem is not a function
    at click (C:\Program Files\IPFS Desktop\resources\app.asar\src\tray.js:145:32)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by EmbALL** [comment]
Maybe link to the folder is wrong:  
_C:\Program Files\IPFS Desktop\resources\app.asar\src_ - **doesn't exist**
_C:\Program Files\IPFS Desktop\resources\app.asar.unpacked\src_ - **this path exist**

**Comment by jessicaschilling** [comment]
Hi - this is a known issue and is being worked in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1687.
