### ISSUE TITLE
Null PID error might be caused by sleep mode?

### ISSUE THREAD

**Issue by Madeindreams** [ipfs-shipyard/ipfs-desktop#1702]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:242:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by jessicaschilling** [comment]
Thank you, @Madeindreams ! We'll look into this in our next weekly triage.

**Comment by jessicaschilling** [comment]
Note: duplicate here https://github.com/ipfs-shipyard/ipfs-webui/issues/1670

**Comment by jessicaschilling** [comment]
Note: another duplicate here https://github.com/ipfs-shipyard/ipfs-desktop/issues/1706

OS: darwin
IPFS Desktop Version: 0.13.2
Electron Version: 9.3.2
Chrome Version: 83.0.4103.122

**Comment by jessicaschilling** [comment]
Closing due to moving this into larger issue investigating `Cannot read property 'pid' of null` errors: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1713
