### ISSUE TITLE
ipfs is always starting?

### ISSUE THREAD

**Issue by huwentao1** [ipfs-shipyard/ipfs-desktop#1707]
![image](https://user-images.githubusercontent.com/43719888/97775622-191bcd80-1b9d-11eb-94b7-ae4ccf15e254.png)

I can’t access the software, I can only see that it has been starting up, I don’t know what went wrong！

Below is the ipfs node information I manually installed and started。
```
mac ~ % ipfs version
ipfs version 0.7.0
mac ~ % ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.4
Swarm listening on /ip4/127.0.0.1/tcp/4001
......
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use
mac ~ % 
```

I think it may be that the ipfs node information I manually installed conflicts with the ipfs desktop version, but even if I uninstall and reinstall it, it still not works.
The following is the information of the file I uploaded through the ipfs node, but it can’t be synchronized

```
mac ~/hwt/constact_test/1031 % cat file.txt 
hwt:123
mac ~/hwt/constact_test/1031 % ipfs add file.txt 
added QmbNfmksxJPfRv6x3TD3bsLuWnMuzo4bsTxH3AYtF3SQaQ file.txt
 8 B / 8 B [==============================================================================================================================================================] 100.00%mac 
mac ~/hwt/constact_test/1031 % ipfs cat QmbNfmksxJPfRv6x3TD3bsLuWnMuzo4bsTxH3AYtF3SQaQ
hwt:123
```

**Comment by jessicaschilling** [comment]
Hi @huwentao1 - sorry you are having issues! Can you please ask in the forums instead? They are at discuss.ipfs.io - thank you!
