### ISSUE TITLE
Failure loading XKCD example 

### ISSUE THREAD

**Issue by james2mid** [ipfs-shipyard/ipfs-desktop#1711]
I attempted to view the XKCD example directory and it crashed.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:242:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by jessicaschilling** [comment]
Thanks, @james2mid -- we will look into this in our next weekly triage!

**Comment by jessicaschilling** [comment]
Closing due to moving this into larger issue investigating `Cannot read property 'pid' of null` errors: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1713
