### ISSUE TITLE
Crashed on restart.

### ISSUE THREAD

**Issue by Madeindreams** [ipfs-shipyard/ipfs-desktop#1714]
Please describe what you were doing when this error happened.

I was trying to connect to my ipfs node using node js.  Changed the API ip adress to 0.0.0.0 and back to 127.0.0.1. When i selected restart from the tray icon menu IPFS Desktop crashed.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:242:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by jessicaschilling** [comment]
Thanks, @madeindreams - we're investigating this particular error already in #1713, so closing this issue and mentioning your report there!
