### ISSUE TITLE
IPFS adoption by non-techie people is hard

### ISSUE THREAD

**Issue by notramo** [ipfs-shipyard/ipfs-desktop#1720]
When I say to anyone to download IPFS Desktop, I can't expect them to read all the webpage, then find the download link on Microsoft Github.
**They aren't interested in what features the protocol has to showcase. They aren't interested in how it works. They simply want to download the app to be able to get my files I put on IPFS for them.**

#### Currently:
- user lands on ipfs.io
- finds no download link
- has to read nearly whole homepage (they won't, so they have to scroll through)
- has to select IPFS Desktop from many choices
- is redirected to Microsoft Github
- has to find the "Releases" page in the developer-oriented interface of Microsoft Github (they don't even know what version-control or even source code means, or not familiar with software development flow, so they won't find it)
- has to find the package for their architecture (some doesn't even know that Microsoft Windows use .exe, Apple macOS use .dmg, and GNU/Linux use .AppImage)
- download and install

#### What would be ideal:
- lands on ipfs.io
- see a highlighted Download link, so they can click it
- Options: Linux, macOS, Windows, mobile app store links (less highlighted text: command line, source code, other platforms)
- download and install

**Comment by jessicaschilling** [comment]
Hi @notramo - we are actually currently working on an improved download flow for the main ipfs.io site, for implementation in Q1. As you noted, it'll include a direct download pathway, including OS and/or browser (in the case of IPFS Companion) detection to help new users download the best option for them. 

The work isn't in GitHub issues just yet, but when implementation starts you can follow along in the ipfs/website repo. Closing this issue with all that in mind, but please be assured we are working on it. Thank you!
