### ISSUE TITLE
Bulk copy/paste hashes of files in ipfs-desktop

### ISSUE THREAD

**Issue by yeehi** [ipfs-shipyard/ipfs-desktop#1721]
**Is your feature request related to a problem? Please describe.**
If we use ipfs-desktop to look at a folder of files we are pinning, how can we easily copy all the hashes of the files in that folder, so that we can later on paste or share them elsewhere?

At the moment, if you use the tick box to “select all”, a pop-up appears with a “Share” option, and it provides a hash for all the selected files. You can also select individual files from the folder, and the “Share option” will provide a hash for those you selected. But you might not want to share all the files (as there are too many to up/download) or know which hashes would be needed. It might be good to be able to share the hashes anyway.

**Describe the solution you'd like**
How can we copy/paste all the filenames and hashes?

**Describe alternatives you've considered**
Laboriously, repeatedly, manually, individually copy/pasting the filenames and their hashes one by one.

**Additional context**
This seems to be an issue with the electron interface.

**Comment by jessicaschilling** [comment]
Thanks - we will discuss in our next triage session.

**Comment by jessicaschilling** [comment]
Issue moved to [ipfs-shipyard/ipfs-webui #1703](https://github.com/ipfs-shipyard/ipfs-webui/issues/1703) via [**ZenHub**](https://www.zenhub.com/)
