### ISSUE TITLE
IPFS shared links to .MP4 files and not playing correctly in a new browser window...

### ISSUE THREAD

**Issue by moemurdock** [ipfs-shipyard/ipfs-desktop#1724]
- OS:  Mac OS10.14.6
- Version of IPFS Desktop [e.g. 0.11.1]: IPFS Desktop 0.13.2

**Describe the bug**
-Please note that I am new to using IPFS so this might not actually be a bug- please see the following for what I am experiencing
1. When I upload an mp4 file for sharing and delivery of a video project to another user, the shared link retrieved from the IPFS desktop portal does not play in any browser window
(So far I have tested this in Google chrome, Opera, Firefox and Safari) - Is this supposed to be the case?

**Please note that I am able to successfully download the file from the IPFS desktop window and the file plays successfully.

**To Reproduce**
1. Go to '...' - I went to the IPFS Desktop window portal and clicked on “+Import”
-I selected the .mp4 file that I wanted to share on my desktop
-The file successfully loads in the IPFS Desktop window manager - hooray!...but then...

-I click on the three dots to the right of the file name in the IPFS Desktop window portal and then click on “Share link”
![Screen Shot 2020-12-29 at 12 34 30 PM](https://user-images.githubusercontent.com/76744888/103302704-3c62cd80-49d2-11eb-9779-9d1b1fdbab2b.png)

-The share link window  pops up with a link to the file that I want to share
-I copy and paste the link into a new browser window as a test to preview the file
-I can hear the audio in the .mp4 file but I can’t see the the actual .mp4 video play
![Screen Shot 2020-12-29 at 12 14 52 PM](https://user-images.githubusercontent.com/76744888/103302711-44bb0880-49d2-11eb-87a6-1ae63df99bc4.png)

3. Scroll down to '....' - scroll down to screen captures below to see the errors that I am getting

**Expected behavior**
-When sharing the link from the IPFS desktop window I expect that the file that I am sharing (.mp4 file in this case) will play in any open browser window to verify/preview the asset(it currently does not)
![Screen Shot 2020-12-29 at 12 14 52 PM](https://user-images.githubusercontent.com/76744888/103302433-a9299800-49d1-11eb-8716-f0b6b238c747.png)

-Please note that when I download the IPFS file via the browser window the file downloads and plays successfully
![Screen Shot 2020-12-29 at 12 25 47 PM](https://user-images.githubusercontent.com/76744888/103302469-bfcfef00-49d1-11eb-8fd0-74560b067117.png)

**Screenshots**
(See attached) Thank you so much!

**Comment by jessicaschilling** [comment]
Hi @moemurdock - wondering if this is more of an issue involving browser support for mp4 in general - see https://developer.mozilla.org/zh-TW/docs/Web/HTML/Supported_media_formats for a few details. I'd suggest asking the recipient to download the file from the share link (as you've done) and open in their machine's video player app(s) as appropriate. 

The core team can look into this a bit more but we are currently a bit sparse due to the holidays and will ramp up again in early Jan!

Additionally, the folks in discuss.ipfs.io are a great source of community support 😊

**Comment by moemurdock** [comment]
Hi Jessica, - first off thanks so much for the quick response - I super appreciate it. Secondly that solution is simple and elegant (I should have thought of it myself). Blame it on me being new to IPFS (hah).
Thanks so much for the note , just wanted to make sure that I was using things correctly.

Have a great day!

**Comment by jessicaschilling** [comment]
Thanks @moemurdock - and hope you have fun using IPFS!

**Comment by ValZapod** [comment]
To play mp4 file over the internet, you must place the moov atom at the beginning of the file for efficient seeking or for it to work at all in many cases. 
Something like that `ffmpeg -i input.mp4 -c:a copy -c:v copy -movflags +faststart output.mp4
`
