### ISSUE TITLE
Text coding error in Chinese

### ISSUE THREAD

**Issue by aihy** [ipfs-shipyard/ipfs-desktop#1728]
Text coding error in Chinese

1. Click on Download
![image](https://user-images.githubusercontent.com/16832365/103969249-7ab17700-51a0-11eb-87e9-718363789d3b.png)
2. See two buttons text error
![image](https://user-images.githubusercontent.com/16832365/103969287-8d2bb080-51a0-11eb-93c7-d55382b5bbd8.png)

at macOS Big Sur 11.1
ipfs-desktop 0.13.2

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-desktop/pull/1729 should fix this.
