### ISSUE TITLE
macOS 11.1: IPFS Desktop stuck with "IPFS is Starting"

### ISSUE THREAD

**Issue by NorseGaud** [ipfs-shipyard/ipfs-desktop#1730]
- OS: macOS
- 0.13.2 & go-ipfs 0.7.0
- Both DMG install and brew have been tried.

**Describe the bug**

Desktop shows "IPFS is Starting" indefinitely, though the UI does show a failure after a long wait.

This is my first time ever looking at IPFS, so I haven't changed anything from defaults :)
**macOS Firewall is off**

```
❯ sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/5817224/combined.log)
error.log is empty

The Desktop UI will eventually show: 

<img width="1439" alt="Screen Shot 2021-01-14 at 5 13 20 PM" src="https://user-images.githubusercontent.com/5896030/104655568-e22d6200-568b-11eb-82e6-ac3a371e114d.png">

Oh, it actually looks like ipfs daemon is stuck...
I never see the 
```
> API server listening on /ip4/127.0.0.1/tcp/5001
> Gateway server listening on /ip4/127.0.0.1/tcp/8080
```

---

Trying to use the CLI shows it getting stuck at:

```
❯ ipfs daemon
Initializing daemon...
go-ipfs version: 0.7.0-ea77213
Repo version: 10
System version: amd64/darwin
Golang version: go1.14.12
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/192.168.0.107/tcp/4001
Swarm listening on /ip4/192.168.0.107/udp/4001/quic
Swarm listening on /ip4/192.168.64.1/tcp/4001
Swarm listening on /ip4/192.168.64.1/udp/4001/quic
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/192.168.64.1/tcp/4001
Swarm announcing /ip4/192.168.64.1/udp/4001/quic
Swarm announcing /ip4/24.62.29.132/tcp/4001
Swarm announcing /ip4/24.62.29.132/udp/4001/quic
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic
```

```
❯ netstat -vanp tcp | grep 5001
tcp6       0      0  ::1.5001               ::1.55935              ESTABLISHED 407252 146808    730      0 0x0082 0x00000004
tcp6       0      0  ::1.55935              ::1.5001               ESTABLISHED 407800 146808  41206      0 0x0102 0x00000008
tcp6       0      0  ::1.5001               *.*                    LISTEN      131072 131072    730      0 0x0080 0x00000006
tcp4       0      0  127.0.0.1.5001         *.*                    LISTEN      131072 131072    730      0 0x0080 0x00000006
tcp6       0      0  ::1.55912              ::1.5001               TIME_WAIT   407800 146808  41206      0 0x2131 0x00000008

❯  lsof -i tcp:5001
COMMAND     PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Brave\x20 41206 nathanpierce   42u  IPv6 0x9c1258feff4e2257      0t0  TCP localhost:55935->localhost:commplex-link (ESTABLISHED)
```

**To Reproduce**
1. Install desktop app

**Comment by jessicaschilling** [comment]
The fact that you're experiencing issues running the daemon from the terminal with or without Desktop suggests an issue outside Desktop itself. Since it sounds like you just started using IPFS and therefore don't have a big files repo to preserve, suggest uninstalling as cleanly as possible - both Desktop and any traces Brew might have left in its installation - and starting again. There may also be folks in the discuss.ipfs.io forums who have experienced similar - but at this point it doesn't seem like the problem you're experiencing is a Desktop-specific one.

**Comment by NorseGaud** [comment]
I rebooted my laptop and it's working now. *shrug*

**Comment by jessicaschilling** [comment]
Chalking this one up to gremlins. Hope you have fun with IPFS!
