### ISSUE TITLE
Clicking on anything under "Advanced" in status closes the dropdown view

### ISSUE THREAD

**Issue by ShadowJonathan** [ipfs-shipyard/ipfs-desktop#1731]
- OS: Linux (PopOS 20.10)
- Version of IPFS Desktop: `v2.11.4`

**Describe the bug**
When clicked on the "Advanced" button on the `Status` view, and then clicking (more specifically, releasing mouse1) on anything that pops open via that dropdown, it'll close the Advanced dropdown instantly.

**To Reproduce**
1. Open IPFS desktop
2. Go to Status
3. Open "Advanced"
4. Try to highlight any text in the dropdown, or click "Edit" on the API section

**Expected behavior**
Normal UI behaviour (hightlight stays, button clicks normally)

**Comment by jessicaschilling** [comment]
Thank you, @ShadowJonathan! This is a known issue under https://github.com/ipfs-shipyard/ipfs-webui/issues/1693, so will close this as a duplicate, but thank you for the prioritization - we have been occupied on a large project and will push this up in the queue for when that's done.

Please note that in the meantime, you can edit the API address under the Settings screen.

**Comment by ShadowJonathan** [comment]
oh, sorry for the duplicate then, i wasn't aware that was a seperate project, i searched for it on here before i posted it, but apparently i was in the wrong spot, then

thanks for marking as duplicate! i'll follow and sub to the webui issue
