### ISSUE TITLE
IPFS API/Updating error

### ISSUE THREAD

**Issue by Unke0m** [ipfs-shipyard/ipfs-desktop#1734]
Trying to get IPFS to run, but app says it could not connect to the IPFS API even after uninstalling and reinstalling.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: ctx.manualCheckForUpdates is not a function
    at click (F:\IPFS\IPFS Desktop\resources\app.asar\src\tray.js:198:30)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by jessicaschilling** [comment]
@lidel and/or @rafaelramalho19 (because this issue is Windows), can you please take a quick look? Thank you!

**Comment by jessicaschilling** [comment]
This is actually a duplicate of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1723 - will close this issue for efficiency.
