### ISSUE TITLE
Error Report: Error: spawn npm.cmd ENOENT

### ISSUE THREAD

**Issue by writingpoli** [ipfs-shipyard/ipfs-desktop#1736]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
Error: spawn npm.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by jessicaschilling** [comment]
@writingpoli Can you please describe what you were trying to do when this error happened? Are you still able to use Desktop?

**Comment by writingpoli** [comment]
I just clicked npm on IPFS Desktop and this is the result. May need to add software, but thought I'd share the error message.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jessicaschilling** [comment]
Thanks - if you're trying to enable the "npm on IPFS" function (see screenshot for location, pardon that I'm on a Mac so the UI is slightly different), your OS will prompt you to confirm whether you'd like to install the `ipfs-npm` package locally. Looks like the error you experienced may have happened upon clicking 'Cancel' - I'll close this issue on that assumption, but if you have problems enabling the feature, please re-open.
 
![image](https://user-images.githubusercontent.com/1507828/105092685-cb598780-5a5e-11eb-96d0-713debbb3950.png)
![image](https://user-images.githubusercontent.com/1507828/105092848-065bbb00-5a5f-11eb-80af-428ae1002778.png)
