### ISSUE TITLE
wrong i18n

### ISSUE THREAD

**Issue by bluelovers** [ipfs-shipyard/ipfs-desktop#1743]
- OS: [e.g. macOS, Windows, Linux]
 - Version of IPFS Desktop [e.g. 0.11.1]

![image](https://user-images.githubusercontent.com/167966/105541914-7ace7c80-5d33-11eb-9c13-76cb2e16983e.png)

![image](https://user-images.githubusercontent.com/167966/105541890-730ed800-5d33-11eb-9cf9-3ac53565ac65.png)

**Describe the bug**

![image](https://user-images.githubusercontent.com/167966/105541820-52df1900-5d33-11eb-82e4-106a39e98565.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jessicaschilling** [comment]
This was fixed in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1729 and will be included in the next release. Thanks!
