### ISSUE TITLE
I tried adding ipfs to path (for running daemon)

### ISSUE THREAD

**Issue by ygboucherk** [ipfs-shipyard/ipfs-desktop#1744]
I had an error that said daemon wasn't running, so I tried adding ipfs to path for adding it to CLI, but I got this error. 

If it's hard to fix, I suggest adding an in-gui method for launching daemon ! 

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.7
- **Electron Version**: 6.0.12
- **Chrome Version**: 76.0.3809.146

**Error**

```
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by jessicaschilling** [comment]
We'll go over this in our next triage session, but any other details you could provide could be great - namely how you went about adding IPFS to path? What exactly did you do?

**Comment by ygboucherk** [comment]
I wanted to enable daemon for contributing to IPFS. So I wanted to add ipfs to path for running the `ipfs daemon` command !

**Comment by rafaelramalho19** [comment]
@ygboucherk if I understand correctly, you replaced your whole windows variable paths to add ipfs and you removed powershell from it?

It doesn't make much sense that powershell.exe is not available in your windows machine.

Can you specify what steps you followed and what caused this error?

**Comment by ygboucherk** [comment]
I didn't remove powershell from path, and it's running perfectly from `powershell` command, and I almost never use powershell (I use CMD)

**Comment by ygboucherk** [comment]
And I tried adding it to path from GUI button

**Comment by ygboucherk** [comment]
Without manually editing `PATH`

**Comment by rafaelramalho19** [comment]
Alright, thanks for clearing that up. Apparently it can happen that you don't have powershell in the path.

Can you try following these steps and try again?

```
- cmd+q and search env and hit enter
- click environment variables in the advanced tab
- find Path/PATH variable and click edit
- Click new and paste %SystemRoot%/system32/WindowsPowerShell/v1.0

**Comment by ygboucherk** [comment]
Okay, thanks

**Comment by ygboucherk** [comment]
but, what's `cmd+q` ?
I'm on windows, not on a mac !

**Comment by ygboucherk** [comment]
Should I edit registry (with `regedit`) ?

**Comment by rafaelramalho19** [comment]
Sorry, I meant CTRL + Q (or just press the windows icon for the search to activate)

**Comment by lidel** [comment]
I am afraid the only fix here is to find `IPFS Desktop/config.json` and manually set:
```json
"ipfsOnPath": false,
```
We will be deprecating this feature (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1768), if you want `ipfs` on your `PATH`   follow https://docs.ipfs.io/install/command-line/
