### ISSUE TITLE
add a dark theme or better use the system theme

### ISSUE THREAD

**Issue by promeneur** [ipfs-shipyard/ipfs-desktop#1745]
Please add a dark theme or better use the system theme.

Thanks

openSuse 15.2
kde apps 20.12.1
plasma 5.20.5
frameworks 5.78.0

**Comment by jessicaschilling** [comment]
Thanks - this is already open upstream in https://github.com/ipfs-shipyard/ipfs-webui/issues/1702, so closing to avoid duplication.
