### ISSUE TITLE
fedora

### ISSUE THREAD

**Issue by ojej** [ipfs-shipyard/ipfs-desktop#1746]
I need fedora packahe and redhat

**Comment by jessicaschilling** [comment]
You can see full information on install instructions for various operating systems and what package managers are currently supported here:

https://github.com/ipfs-shipyard/ipfs-desktop/issues/691

https://docs.ipfs.io/install/command-line/

**Comment by ojej** [comment]
fedora nie istnieje na tej liści. pod adresem https://docs.ipfs.io/install/command-line/
nie ma informacji o fedorze. sama nie przeczytałaś a podajesz link.
