### ISSUE TITLE
Installation failed on windows?

### ISSUE THREAD

**Issue by jingyuexing** [ipfs-shipyard/ipfs-desktop#1760]
- OS: WINDOWS
 - Version of IPFS Desktop 0.12.2,0.13.2

**Describe the bug**

**To Reproduce**
1. Double-click the installation package 
2. next (Administrator install or just install as yourself)
3. SEE ERROR(the message is **'Installation aborted'**)

**Expected behavior**

**Screenshots**
I![图片](https://user-images.githubusercontent.com/19589872/107927575-245f0180-6fb2-11eb-9c37-cd692d12753e.png)
**Additional context**

**OTHER**
Because the *IPFS-DESKTOP* can't runing,so, I want reinstall,then has this issue

**Comment by jessicaschilling** [comment]
Hi @jingyuexing - requesting that you please take this question to the forums at https://discuss.ipfs.io/c/help/13. If this uncovers a bug in IPFS Desktop itself, we can re-open this issue. Thank you!
