### ISSUE TITLE
Open app window with double-click on tray icon

### ISSUE THREAD

**Issue by AbakumovAlexandr** [ipfs-shipyard/ipfs-desktop#1764]
Usually, single or double-click on a tray icon opens the main app window.

**Describe alternatives you've considered**
With IPFS Desktop to open the app window, we have to open a tray icon menu and click on a certain item.

Can we have the same behavior in IPFS Desktop: when double-clicking on the tray icon - open the app window on the last 'activity' for faster access to the app via the tray icon?

**Comment by lidel** [comment]
The behavior depends on platform. Some patters are only valid on Windows or Linux, but not macOS.

If someone wants to adjust behavior on specific platform, PRs welcome!
Just make sure to familiarize yourself with limitations listed on https://www.electronjs.org/docs/api/tray

**Comment by lidel** [comment]
Actually, this may be easy to clean up as part of #1762.
I'll look into this.

**Comment by AbakumovAlexandr** [comment]
> platform

I'm talking about Windows. Thank you!

**Comment by lidel** [comment]
@AbakumovAlexandr please update to 0.14.0 and let us know if the double-click behavior is correct.

**Comment by AbakumovAlexandr** [comment]
@lidel Thank you double click is working!

However, for me there are still 2 minor issues:
1. Double click always opens the app on the `STATUS` screen. It would be great if it would open it on the last screen I was on before closing the window.

2. Single click with left mouse button still opens the context menu even when doing double click. So, the first left click quickly opens the menu until the second left click is done. Usually Windows apps are designed so that if tray icon menu opens with the right click, it just ignores the single left click.

**Comment by lidel** [comment]
@AbakumovAlexandr Thanks! Do you mind filling those as two new issues? :pray:

**Comment by AbakumovAlexandr** [comment]
@lidel  Sure, I'm happy to do so. Please see ##1771 and ##1772.
