### ISSUE TITLE
A GitHub login dialog pops up; on cancellation, IPFS Desktop announces an update error

### ISSUE THREAD

**Issue by tmladek** [ipfs-shipyard/ipfs-desktop#1777]
Every once in a while, a random GitHub login dialog pops up. When I cancel it, I get an error from IPFS desktop that updating has failed, with a button for reporting the error that takes me here:

![obrazek](https://user-images.githubusercontent.com/5217341/110255817-f3149880-7f95-11eb-9607-0d3dd6d5e0cc.png)

**Specifications**

- **OS**: win32 (Windows 10)
- **IPFS Desktop Version**: 0.14.0
- **Electron Version**: 11.2.3
- **Chrome Version**: 87.0.4280.141

**Error**

```
Error: Command failed: npm.cmd install -g ipfs-npm
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated libp2p-connection-manager@0.1.0: libp2p-connection-manager is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-switch@0.42.12: libp2p-switch is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-ping@0.8.5: libp2p-ping is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-identify@0.7.6: libp2p-identify is now part of libp2p as
```

**Comment by lidel** [comment]
@tmladek please disable NPM on IPFS experiment (via menu or by editing config.json)
It causes issues like one you describe, and is deprecated in favor of https://github.com/forestpm/forest.

**Comment by tmladek** [comment]
@lidel Sorry, what do you mean by "IPFS experiment"? I looked around for an "experimental" version of IPFS Desktop, but couldn't find any. Also, what would be the config.json setting? I tried googling "ipfs config json disable npm" and variations, but found no help either.

Thank you for your response!
