### ISSUE TITLE
Investigate Uninstaller Options

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-desktop#48]
- Stop the daemon
- Remove app
- Optionally clear `~/.ipfs`

**Comment by jbenet** [comment]
oh whoops sorry just made https://github.com/ipfs/electron-app/issues/49

**Comment by jbenet** [comment]
We need both a "Delete Node" and "Uninstall IPFS" (which implies "Delete Node"). 
- [ ] maybe accessible from Settings, once that exists)
- [ ] asks user to confirm, saying something like `"This will delete all IPFS data (1.3 GB)"`
- [ ] stops the node
- [ ] deletes the data
- [ ] "Uninstall IPFS" shuts down application and removes itself completely

**Comment by VictorBjelkholm** [comment]
@hacdias does merging https://github.com/ipfs-shipyard/station/pull/514 make all this cleaning to happen?

**Comment by hacdias** [comment]
Yup, since the installer will also produce an uninstaller.

**Comment by VictorBjelkholm** [comment]
@hacdias cool! We should not close this until we can have a uninstaller that can completely clean up after Station, like removing the repository after asking for confirmation from the user.

**Comment by hacdias** [comment]
Sure!

**Comment by hacdias** [comment]
Will open an issue just for removing the repository

**Comment by hubbs129** [comment]
Hi all,

how do I reverse the "ipfs init" command (on Mac's terminal)? I want to get a new hash.

**Comment by hacdias** [comment]
@hubbs129 do you mean a new peer ID?

**Comment by hubbs129** [comment]
Hi @hacdias, thanks for getting back to me. 
Basically the answer is yes. I have now found where my IPFS folder is on my mac (I'm a n00b) and all I need now a new peer ID, because I accidentally deleted the one I have created.

regards,
H.

**Comment by hacdias** [comment]
@hubbs129 if you don't mind losing the files on your IPFS repository, just close IPFS Desktop, delete `~/.ipfs`, and restart IPFS Desktop.

**Comment by hubbs129** [comment]
OK I have found my Peer ID thanks to this command "ipfs id" :)

Thanks !

**Comment by hubbs129** [comment]
@hacdias 
I have another question if you don't mind. I have a peer ID who's contents I want to check out, how do I do this?
