### ISSUE TITLE
Add test setup

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-desktop#50]
> Every decent (software) project needs tests
## "Frontend" (browser processes)

This is about testing react components in isolation. To run the tests we should use [karma](http://karma-runner.github.io/0.13/index.html) and spawn a chrome process (close enough to electrons chromium instances). Interesting modules and notes
- https://github.com/sheepsteak/react-shallow-testutils
- https://github.com/percyhanna/rquery
- https://github.com/jhnns/rewire-webpack (mock require calls, especially ipc)
- https://github.com/pgte/nock (mock http calls)
## "Backend" (electron main process)

This is much harder, as too much functionality depends on running the real deal aka an electron instance. So very happy to hear any suggestions around this.

**Comment by hacdias** [comment]
Spectron --> https://github.com/electron/spectron

**Comment by hacdias** [comment]
**State of the thing:** Taking [this branch](https://github.com/ipfs-shipyard/ipfs-desktop/tree/feat/components/src) as the state from which we should start writing tests, we've got many different components to test:

- **components** which Simple React components which seem to be relatively easy to test
- **controls** which are subdivided in two:
	- **main** process handlers.
	- **renderer** process handlers.
- **panes** which are a bit more complex React Components that can use Electron's API directly.
- **utils** some simple... utils? Easy to test.
- **views** main entry points for the pages Welcome and Menubar.
- ```index.js```, `errors.js`, `config.js`

I can easily start to create the tests for the components and the utils. Although, I'm not sure how to do testing for the controls, which are basically event handlers of `ipcMain` and some other general stuff. Nor for panes and views.

**Comment by olizilla** [comment]
WIP on adding spectron test in https://github.com/ipfs-shipyard/ipfs-desktop/pull/730

**Comment by hacdias** [comment]
Superseded by #1121
