### ISSUE TITLE
Create Help Page

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-desktop#51]
There should be some form of help/documentation page inside the app, so people can understand what the app is doing and how to use it.

**Comment by RichardLitt** [comment]
> @Dignifiedquire: @RichardLitt: yes it would be great to get some help on that, my idea was to do the setup once the PR is merged, as it has been long running enough for now, but if you want to start writing content in markdown format that would be great

Sweet!

**Comment by Dignifiedquire** [comment]
- Sync from ipns when available 
- Ship initial version so it's always available

**Comment by Dignifiedquire** [comment]
1. Create a directory called `docs`
2. Create a window that renders those docs using a markdown renderer inside a nice help window
3. Add ipfs sync capabilities to allow auto updates of those docs

**Comment by hacdias** [comment]
@diasdavid is this supposed to be done? If so, what should this Help page contain?

**Comment by diasdavid** [comment]
This is a really old proposal (Oct 2015). Yes, docs are great but even greater is making sure that the IPFS GUI is cohesive so that part of the documentation is just UX.

**Comment by hacdias** [comment]
Oh, I thought this was more about a end-user help page. For devs, we already started writing some stuff: https://github.com/ipfs-shipyard/ipfs-station#file-structure

**Comment by RichardLitt** [comment]
Ah, word. Yeah. In that case, David is probably right. Some basic text may help, though. The most use might be gotten out of drawing up some wireframes or user flows, and then implementing them in the GUI.

**Comment by diasdavid** [comment]
In any case, @hacdias already did some valuable work to fulfil the need you described, @RichardLitt , check it out here https://github.com/ipfs-shipyard/ipfs-station#file-structure

**Comment by hacdias** [comment]
Should we close this?

**Comment by hacdias** [comment]
After more than I year, let's close this. The README contains information about how the app works. Now, IPFS Desktop is a relatively simple app and doesn't seem to need 'help'/how-to-use info.
