### ISSUE TITLE
placement of dropdown with disappearing task bar is odd

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/ipfs-desktop#529]
![screen shot 2017-12-05 at 9 11 03 am](https://user-images.githubusercontent.com/1243164/33620274-46b7721c-d99c-11e7-8a59-f9c0b445457d.png)

**Comment by hacdias** [comment]
Hey @whyrusleeping, this issue should be opened on https://github.com/maxogden/menubar, please. 😄

**Comment by machawk1** [comment]
@whyrusleeping What OS is this? I don't experience the clipping on macOS 10.13.1 that you showed.

<img width="891" alt="screen shot 2017-12-05 at 12 27 22 pm" src="https://user-images.githubusercontent.com/2514780/33621085-b29ceb0e-d9b7-11e7-86f2-e4d689517492.png">

The empirical placement paradigm seems to be that popups are left left with the icon or use some a callout-style triangle to associate an icon with a popup that has a larger width than can be displayed (or simply not left-pinned, e.g., Dropbox).

<img width="356" alt="screen shot 2017-12-05 at 12 31 34 pm" src="https://user-images.githubusercontent.com/2514780/33621302-432cc680-d9b8-11e7-888b-a198979d486f.png">

**Comment by whyrusleeping** [comment]
Its probably because i set my menubar to autohide.

**Comment by hacdias** [comment]
Same happens on Windows when the taskbar is set to autohide.

**Comment by hacdias** [comment]
On Windows, though, when you put the cursor above the application, the taskbar hides again so there's no problem at all. It doesn't happen on macOS too @whyrusleeping ?

**Comment by machawk1** [comment]
The menu bar where the station icon resides cannot be hidden nor auto-hidden, @hacdias .

**Comment by hacdias** [comment]
@olizilla please check if this is still an issue with `master`.

**Comment by hacdias** [comment]
@olizilla @fsdiogo @machawk1 ping 😄 Could one of you test if this is still happening?

**Comment by machawk1** [comment]
@hacdias I pulled, compiled, and ran the latest master 529a292bb32886caf9f170d161c11732b8970e3e .

I made sure to hide the menu bar per @whyrusleeping.

The positioning on macOS now seems correct.

![screen shot 2019-01-03 at 11 15 46 am](https://user-images.githubusercontent.com/2514780/50648397-1b815200-0f49-11e9-9df3-acbfce3c24b0.png)
![screen shot 2019-01-03 at 11 15 52 am](https://user-images.githubusercontent.com/2514780/50648398-1b815200-0f49-11e9-9564-541b0dacb452.png)

**Comment by hacdias** [comment]
Thanks @machawk1! Closing this then 😄

**Comment by machawk1** [comment]
A quick followup. After writing the last comment, I relaunched using npm start and experienced some weird positioning behavior. This was tested on a two monitor setup with the left being vertically oriented.

@hacdias I would recommend not closing this issue just yet.

![screen shot 2019-01-03 at 11 19 54 am](https://user-images.githubusercontent.com/2514780/50648613-b2e6a500-0f49-11e9-8b4e-7180da59cd4d.png)
![screen shot 2019-01-03 at 11 20 27 am](https://user-images.githubusercontent.com/2514780/50648614-b2e6a500-0f49-11e9-8204-53250b1beb9a.png)

**Comment by hacdias** [comment]
Ref.: https://github.com/electron/electron/issues/13461

**Comment by hacdias** [comment]
Just tried to replicate this and it seems to be solved with #756.
