### ISSUE TITLE
Setup automated release process

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-desktop#54]
- Bump version (major/minor/patch)
- Generate packages 
- Generate changelog
- Commit and push to github
- Upload packages and changelog to github releases pages

**Comment by jbenet** [comment]
See also https://github.com/ipfs/distributions <--- (we need to ship this damn thing. @RichardLitt have you taken a look at the frontend of this?)

**Comment by jbenet** [comment]
and :+1: to all of the above

**Comment by Dignifiedquire** [comment]
Also for reference: 
* https://github.com/ajoslin/conventional-changelog
* https://github.com/stevemao/conventional-github-releaser

**Comment by RichardLitt** [comment]
@jbenet not yet, added to list of things to do this sprint.

**Comment by Dignifiedquire** [comment]
This should take into consideration #14 

Also this looks interesting, but is sadly OS X only: https://github.com/jenslind/electron-gh-releases

**Comment by Dignifiedquire** [comment]
Some work has been done for the code part: https://github.com/ipfs/station/blob/master/CONTRIBUTING.md

**Comment by Dignifiedquire** [comment]
Lots of good ideas here: https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/master/gulpfile.coffee

**Comment by hacdias** [comment]
We now have an automated release process. We just need Binary Signing (#66 #705). Closing this in favour of more up to date issues.
