### ISSUE TITLE
Let Desktop use pre-existing IPFS installation or already running daemon

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#542]
Ref.: https://github.com/ipfs/js-ipfsd-ctl/issues/182

/cc @machawk1 @diasdavid

**Comment by machawk1** [comment]
It might also be good to advertise a way for other tools to leverage Station's IPFS installation. I am thinking of this in the context of https://github.com/oduwsdl/ipwb, which initially checks IPFS_PATH then defaults to ~/.ipfs if it hasn't been set. For other tools to leverage Station's IPFS, both the binary and the repo, might require an API on Station's end to ensure that Station gets all of the information needed for files added via other tools.

**Comment by lidel** [comment]
Another data point from me :)

On one of my workstations I run go-ipfs under Docker.
Due to this my `~/.ipfs` has only one text file named  `~/.ipfs/api` with multiaddr of remote node:

```
$ cat ~/.ipfs/api
/ip4/127.0.0.1/tcp/5001
```

This setup seems to break startup of ipfs-desktop:

```$ DEBUG='desktop' npm start

> ipfs-desktop@0.3.0 start /home/lidel/projects/ipfs-desktop
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 3 / 3
✔ Launching Application
  desktop Application is ready +0ms
  desktop Starting daemon +5ms
  desktop Uncaught Exception: Error: ENOENT: no such file or directory, open '/home/lidel/.ipfs/config' +23ms
```

I guess ipfs-desktop should  detect `~/.ipfs/api` and connect to remote node 🚀

**Comment by bedri** [comment]
Files added with command line ipfs (I think I had installed ipfs-go but it shouldn't matter which client user uses) does not show up in the ipfs-desktop GUI. I guess this should also go under this topic. If requested I can open a separate issue for this.

Thank you.

**Comment by hacdias** [comment]
@bedri the files we show on IPFS Desktop are the same we show on IPFS WebUI: from the Mutable File System. They should be added through `ipfs files write` and not `ipfs add`.

**Comment by bedri** [comment]
@hacdias oh ok. I did not know that. I will check it.
Although I am able to see the files that I add with "ipfs add" from Web UI. I am confused at that part.
I couldn't also managed to use ipfs files write to add files but i will figure it out eventually.

**Comment by hacdias** [comment]
@bedri I think the version on `/webui` address is not the same from master on IPFS-WebUI repo and they probably have some differences regarding on which files they show. 😄 

About `ipfs files write`: `ipfs files write --create [path-on-mfs] [path-of-the-data-on-your-disk]`. MFS is like a file system (you can have directories and all of that. Imagine you have a file called `sec.txt` you want to add to the root of MFS, just run:

```
ipfs files write --create /sec.txt ~/my/path/to/sec.txt
```

**Comment by bedri** [comment]
Oh got it. Thank you very much :smile:

**Comment by zricethezav** [comment]
Any plans to have cli `ipfs add` populate files in the gui by default?? Otherwise i think the their needs to be a disclaimer in the gui.

**Comment by hacdias** [comment]
@zricethezav the GUI shows your MFS (Mutable File System) and not files added by `ipfs add`. That command only adds files to your repo temporarily unless you pin them. If you add something to MFS (through `ipfs files write/cp/mv`), it will be automatically pinned and won't be removed by the garbage collector.

We recommend you to use the MFS so you can see the files on the UI and you also have the feel of a file system with directories and such things.

@olizilla please correct me if I'm wrong.

**Comment by olizilla** [comment]
@zricethezav yes, very much so. Right now, `ipfs add` does the job of adding files to the IPFS universe... chunking and hashing them to calculate the CID (Content ID). What it doens't do _yet_ is update your local file-system view of the repo (internally referred to as the Mutable File System, as it's the view of your files that you can edit). It's a significant UX issue that we are working on!

@hacdias MFS isn't a concept users should have to think about, it's an implementation detail. The workaround right now is an extra step to `ipfs files cp` things into it after adding them, but that's not the UX we want.

**Comment by lidel** [comment]
Obligatory disclaimer:

- In case someone notice "ipfs add" and "ipfs files write" commands return different CIDs –  [this is why](https://github.com/ipfs/support/issues/45#issuecomment-269296211) :)
- A lot changed since https://github.com/ipfs-shipyard/ipfs-desktop/issues/542#issuecomment-373913101: we switched Web UI to use `ipfs add && ipfs files cp` instead of `ipfs write`   (details: https://github.com/ipfs-shipyard/ipfs-webui/issues/676).
