### ISSUE TITLE
New name! Propose and vote in your favourite! Date of decision is Dec 30, 2017

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-desktop#561]
It has dawned on us that IPFS Station is not the best name for this project. _IPFS Station_ doesn't communicate what this repo is about and it also doesn't get better when we announce an update on twitter, IRC or Reddit about the latest _IPFS Station_.

With this in mind and similar to what we did to find a name for [IPFS Compation](https://github.com/ipfs-shipyard/ipfs-companion/issues/225), we open this issue to welcome name proposals and encourage everyone to vote on what they like the most. We will use the proposals and that feedback to pick the new name.

Please submit your proposals by creating a _separate comment per proposal_ and give votes with 👍 👎 on that comment.

**Comment by diasdavid** [comment]
Keep `IPFS Station`

**Comment by diasdavid** [comment]
`IPFS App`

**Comment by lgierth** [comment]
Voted 👎 on IPFS App because it feels a tad to generic. IPFSdroid is also an IPFS app, and in a slightly different context, any app built with IPFS is an IPFS app.

**Comment by lgierth** [comment]
`IPFS Desktop`

**Comment by machawk1** [comment]
`IPFS Commander`

**Comment by machawk1** [comment]
I also want to provide another perspective cf. @lgierth that many Mac apps are Something.app (e.g., Calculator.app, Calendar.app) but outside of built-in Apple apps, I rarely see it used (e.g., one doesn't say, "VLC.app" . `IPFS Desktop` is good and expresses the desktop interface...even though Station is a task-/menu-bar based interface.

**Comment by diasdavid** [comment]
# We have a winner 🏆

<img width="774" alt="image" src="https://user-images.githubusercontent.com/1211152/34575167-a6708684-f171-11e7-9d3b-56cdff188836.png">

Thank you all that participated in this discussion :) @lgierth you can claim your prize (a nice chocolate) the next time we hangout 🍫
