### ISSUE TITLE
Publishing to the AppStore

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-desktop#569]
Lot's of valuable learnings here https://hackernoon.com/electron-on-the-appstore-pain-tears-iii-ship-it-a8c6bb141ece, we should take them all in mind for our release process.

**Comment by diasdavid** [comment]
@hacdias can you own this?

**Comment by hacdias** [comment]
I believe it would be better that someone with a mac took care of this because of testing and to make sure things work.

**Comment by hacdias** [comment]
Closing in favour of #691.
