### ISSUE TITLE
npm install WARN deprecations

### ISSUE THREAD

**Issue by nothingismagick** [ipfs-shipyard/ipfs-desktop#576]
With all the fuss over at NPM the other day, I thought I would post the modules that complain during the `npm install`. I am somewhat alarmed about the **minimatch** version from 2014...

I am running node v8.9.1 and npm v5.6.0.

```
npm WARN deprecated graceful-fs@3.0.11: 
  please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated wrench@1.5.9: 
  wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.3.0: 
  Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.12.7: 
  CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jade@1.11.0: 
  Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: 
  Deprecated, use jstransformer
```

**Comment by nothingismagick** [comment]
So it seems that most of the problems are upstream. I checked with `npm ls [package]` and got these results (edited for brevity, my comments after `#`)

```
ipfs-desktop@0.3.0 (graceful-fs)
└─┬ ipfsd-ctl@0.26.0
  └─┬ go-ipfs-dep@0.4.13
    └─┬ unzip@0.1.11 # is the latest version (and three years old, btw.)
      └─┬ fstream@0.1.31 # is currently at v1.0.11
        └── graceful-fs@3.0.11 # other modules dedup to graceful-fs@4.1.11

 ipfs-desktop@0.3.0 (wrench)
└─┬ electron-forge@4.2.0
  └─┬ electron-windows-store@0.12.0
    └─┬ flatten-packages@0.1.4
      └── wrench@1.5.9 # should be fs-extra because wrench is discontinued

ipfs-desktop@0.3.0 (minimatch)
├─┬ electron-forge@4.2.0
  └─┬ zip-folder@1.0.0 # 3 years old.
    └─┬ archiver@0.11.0 # currently at v2.1.0
      └─┬ glob@3.2.11 # glob package is currently at v7.1.2
        └── minimatch@0.3.0 # this is very bad.

ipfs-desktop@0.3.0 (coffee-script)
└─┬ electron-prebuilt-compile@1.7.9
  └─┬ electron-compilers@5.9.0 # is current
    ├── coffee-script@1.12.7 
    └─┬ cson@3.0.2
      ├── coffee-script@1.12.7  deduped
      └─┬ cson-parser@1.3.5
        └── coffee-script@1.12.7  deduped

ipfs-desktop@0.3.0 (jade)
└─┬ electron-prebuilt-compile@1.7.9
  └─┬ electron-compilers@5.9.0
    └── UNMET DEPENDENCY jade@1.11.0 

ipfs-desktop@0.3.0 (transformers)
└─┬ electron-prebuilt-compile@1.7.9 
  └─┬ electron-compilers@5.9.0
    └─┬ UNMET DEPENDENCY jade@1.11.0
      └── transformers@2.1.0 

npm ERR! missing: jade@1.11.0, required by electron-compilers@5.9.0

``` 

**Fazit:** 

- package `electron-prebuilt-compile' should be updated in the dev deps to
    `"electron-prebuilt-compile": "^1.8.1"`
- package `electron-compilers` needs some love - i.e. the maintainers notified that **jade** is now known as **pug** and **coffee-script** is known as **coffeescript**. Jeesh. But technically this won't affect ipfs-desktop at all, since covfefe script is not being used, and neither is jade.
- package `electron-forge` is currently using a 3-year-old repo 'zip-folder' with outdated deps. That smells...
- package `go-ipfs-dep` should look into using something other than `unzip` for its needs, or the organization should fork 'unzip' and update the deps and/or interface to maintain conventions...

**Comment by hacdias** [comment]
Hello @nothingismagick! Thanks for noticing this. Just updated `electron-prebuilt-compile` to 1.8.1. This dependency must be set for a specific version and not a range. That's something Electron Forge needs.

About the other dependencies, I suggest you to do the same as you did for go-ipfs-dep and open an issue there 😄

**Comment by hacdias** [comment]
I'm not sure if we should leave this open since it is not directly related to issues of `ipfs-desktop`. What do you think?

**Comment by nothingismagick** [comment]
Closing with pleasure and glad to help out.
