### ISSUE TITLE
npm start on mac osx 10.13.1 high sierra 

### ISSUE THREAD

**Issue by alexgarciac** [ipfs-shipyard/ipfs-desktop#577]
hi, I followed the instructions but it did not work. from the shell I get
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 1 / 1
✔ Launching Application
2018-01-09 19:11:41.562 Electron[59234:27504278] *** WARNING: Textured window <AtomNSWindow: 0x7ff74ed8b790> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
info: Application is ready {}
info: Start daemon {}
info: Started daemon {}

at the end it does not display the menu bar. what am I missing?

**Comment by hacdias** [comment]
Hello @alexgarciac! Never saw that error before 😞 @diasdavid could you try it out on your mac, please?

**Comment by machawk1** [comment]
I pulled 2aa8e947c4d34c8b34c38267ab1affc3c470afc7 and got the same output as @alexgarciac but see the menu bar icon.

```
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 1 / 1
✔ Launching Application
2018-01-10 00:23:46.778 Electron[13564:935244] *** WARNING: Textured window <AtomNSWindow: 0x7fe3095b60a0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
info: Application is ready {}
info: Start daemon {}
info: Started daemon {}
```

macOS v10.13.2
node v8.9.4
npm v5.6.0

![screen shot 2018-01-10 at 12 26 20 am](https://user-images.githubusercontent.com/2514780/34757080-fb71aaa8-f59c-11e7-8176-992a699fa730.png)

**Comment by hacdias** [comment]
Could you try removing [this lines](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/src/index.js#L228-L246) and execute the code again?

**Comment by alexgarciac** [comment]
No, did not work. I deleted the lines from the index.js started the app and then nothing happened so I had to ctrl-c. 

> ipfs-desktop@0.3.0 start /Users/alexgarciac/Documents/ipfs-desktop/ipfs-desktop
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 1 / 1
✔ Launching Application
2018-01-10 16:19:19.251 Electron[2434:518158] *** WARNING: Textured window <AtomNSWindow: 0x7fd255ce1f40> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
info: Application is ready {}
info: Start daemon {}
info: Started daemon {}
info: Shutting down application {}
info: Stopping daemon {}

**Comment by hacdias** [comment]
That is strange. I'll probably open an issue on electron today. Did you
update macOS since the he last time you tried ipfs-desktop?

**Comment by alexgarciac** [comment]
I actually updated yesterday. I have 10.13.2 (17C88) I will test this in a linux mint box and let u know if it works.

**Comment by hacdias** [comment]
Actually, by the error message we can see our seems to be sighing only
affecting Mac OS. But give it a shot. 👍

**Comment by alexgarciac** [comment]
I am on linux mint. running on a vbox from my mac. npm version 3.5.2, nodejs 9.4.0 now I get

npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ipfs-desktop@0.3.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipfs-desktop@0.3.0 start script 'electron-forge start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipfs-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-forge start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipfs-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipfs-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/ipfs-shipyard/ipfs-desktop/npm-debug.log

**Comment by hacdias** [comment]
Could you send the log, please? That error doesn't say much 😞

**Comment by hacdias** [comment]
@alexgarciac could you try deleting `node_modules` folder and running `npm install` again? Just to make sure native dependencies were built with the correct version of node.

**Comment by alexgarciac** [comment]
how can I get the log? npm start --save log but does not make any difference.

**Comment by alexgarciac** [comment]
working!!!! as funny as it may sound rebooting was enough.... anyway it is working now.

**Comment by hacdias** [comment]
@alexgarciac nice!

@machawk1 any developments from your side?

**Comment by machawk1** [comment]
@hacdias I was unable to replicate the UI issue @alexgarciac mentioned and wanted to confirm that for the sake of testing on macOS. All is well and functional on my end.

**Comment by hacdias** [comment]
But you both still get the warning @machawk1 @alexgarciac?

**Comment by machawk1** [comment]
Just re-pulled and ran via `npm start` from 2e6d0980ae519f3dccbc929eb979bd42bbe6a1da.

This warning is still present:
`2018-01-10 19:45:51.160 Electron[23725:1481990] *** WARNING: Textured window <AtomNSWindow: 0x7fcc52de7a60> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by hacdias** [comment]
Okay. I'll close this issue then. The discussion about that warning will continue on Electron's repository. Ref.: https://github.com/electron/electron/issues/11150.
