### ISSUE TITLE
Save daemon logs

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#581]
Save the daemon logs to somewhere in the universe.

**Comment by VictorBjelkholm** [comment]
Hopefully, the log entries can end up where a user expects the logs to be.

- Unix: syslog
- OSX: Console
- Windows: EventLog (I think?)

**Comment by hacdias** [comment]
@VictorBjelkholm I'm willing to create a simple package to automatically log stuff to syslog and Event Logger on Windows. But... is it worth it? Right now, we can get all of the info by setting the DEBUG environment variable.

The use case I can see is when the end-user installs trough the installer, but that way how could MacOS users get the logs?

And there doesn't seem to be any good syslog package. The best I could find is [node-syslog](https://www.npmjs.com/package/node-syslog) and it appears to be inactive and with some issues (but I think we could fix them.)

**Comment by hacdias** [comment]
I'm having some troubles with this one because the system we're using right now doesn't work synchronously and there is no way to know if the logger wrote to the file before exiting the process.
