### ISSUE TITLE
Make hashes into fully-qualified paths

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/ipfs-desktop#582]
E.g. `QmSomeFile` => `/ipfs/QmSomeFile`, or maybe even `ipfs://QmSomeFile`. The less users have to convert between various ways of representing hashes/paths, the less likely they get confused or frustrated.

**Comment by hacdias** [comment]
If I understand correctly, we would make that change on Peer ID and Peers since they are the only places where we are showing hashes. Wouldn't it make the interface a bit more cluttered?

**Comment by lgierth** [comment]
Later we should also make the PeerIDs into fully-qualified paths, but for now it'd be best to just to it for content.

Reason to wait with the PeerIDs is that the multiaddrs are still using the `/ipfs` namespace. We want to migrate that to `/p2p` (ipfs/notes#201), but until then it'd be best to just omit it here, so we don't unneccessarily confuse users ("doesn't /ipfs mean content?").

**Comment by hacdias** [comment]
But right now we aren't even showing the hash of the files/contents. Only Peers'. But we can leave this a future note.
