### ISSUE TITLE
Something seems broken on macOS

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/ipfs-desktop#586]
<img width="718" alt="screen shot 2018-01-10 at 11 52 35 am" src="https://user-images.githubusercontent.com/1243164/34792441-dcdc7cb6-f5fc-11e7-91d5-be0a8e824721.png">

Note the large black box at the bottom of my screen. Thats the app. Any ideas?

**Comment by hacdias** [comment]
I see macOS is getting too much broken #577. I'll see what I can do.

**Comment by machawk1** [comment]
Things seem to be ok on my (macOS 10.13.2) end:

![screen shot 2018-01-10 at 7 48 17 pm](https://user-images.githubusercontent.com/2514780/34803074-3b42ed5c-f63f-11e7-927a-f1ac4da955c8.png)

**Comment by whyrusleeping** [comment]
Ah, i've got this error message in the logs:
```
2018-01-10 16:57:07.340 Electron[7285:3495859] *** WARNING: Textured window <AtomNSWindow: 0x7f986cdbe9a0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by machawk1** [comment]
@whyrusleeping That's the same warning reported in #577. Even with this warning, I still do not get the all-black display that you do.

**Comment by whyrusleeping** [comment]
@machawk1 do you have your taskbar set to autohide?

**Comment by machawk1** [comment]
By taskbar I presume you mean "menubar" on macOS, @whyrusleeping, in which case, I was unaware that it was possible to even hide the menu bar. I know it's possible on both Linux and Windows but as far as I am aware, the menubar is omnipresent.

**Comment by whyrusleeping** [comment]
System Settings -> General -> 'Automatically Hide and Show menu bar'

<img width="541" alt="screen shot 2018-01-10 at 5 05 31 pm" src="https://user-images.githubusercontent.com/1243164/34803498-7f5a75b2-f628-11e7-9fb0-0dbc0f5c0f96.png">

**Comment by machawk1** [comment]
Whoh, ok. That's news to me.

I hid my menubar, restarted ipfs-desktop and I get the same odd placement as @whyrusleeping but my panel is populated.
![screen shot 2018-01-10 at 8 06 55 pm](https://user-images.githubusercontent.com/2514780/34803562-f2e49f08-f641-11e7-9de2-2a72e8eaa28e.png)

**Comment by hacdias** [comment]
@whyrusleeping could you try running it directly from master and not from the binary? That way, you can open the developer console (using F12) and check if there are any errors. 😄

**Comment by lanzafame** [comment]
I am hitting a kind of related issue with workspaces, where clicking on the ipfs-desktop icon, moves me to another workspace (my guess is the one that I started the program on) and then fails to appear (more like it blinks and disappears). Though, if I stay on that workspace and click the icon again, it opens perfectly. I can open a separate issue if you like?

**Comment by hacdias** [comment]
@lanzafame do that please 😄

**Comment by whyrusleeping** [comment]
<img width="605" alt="screen shot 2018-03-26 at 10 13 53 am" src="https://user-images.githubusercontent.com/1243164/37921397-948a7b9e-30de-11e8-8060-efe7800b80ad.png">
bump (using the 0.4.0 release)
