### ISSUE TITLE
Daemon randomly crashing on Ubuntu

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#589]
/cc @VictorBjelkholm

**Comment by hacdias** [comment]
@VictorBjelkholm could you check if you still get this weird behavior on master?

**Comment by VictorBjelkholm** [comment]
Yeah, started a node via ipfs-desktop just now, will let it run for a while

**Comment by VictorBjelkholm** [comment]
Been letting it run for an hour now and seems to be running fine :+1:

**Comment by hacdias** [comment]
Thanks @VictorBjelkholm 😄
