### ISSUE TITLE
No files listed on new install with existing repo

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#590]
Just installed IPFS Desktop (Amazing work, it is rad!). I've got an existing repo, and the node stats show i'm sharing a bunch of things

![screenshot 2018-01-11 09 38 55](https://user-images.githubusercontent.com/58871/34818660-62b90e56-f6b3-11e7-8ea9-e9c8af66aca7.png)

But the files panel shows an empty list, which is surprising.

![screenshot 2018-01-11 09 38 59](https://user-images.githubusercontent.com/58871/34818684-75d8ef88-f6b3-11e7-9fea-5b56e350a4dc.png)

This is on:

- OSX 10.12.6
- IPFS Desktop 0.3
- go-ipfs 0.4.11

**Comment by hacdias** [comment]
The Files panel only works for files you've uploaded with Station. Do you think we should show the files you are *sharing* on your node even if you didn't upload them?

Let's say you opened a link with your gateway. Then, the file gets added to your repo, right? If we show everything in there, you'll be seeing stuff you didn't add to the repo yourself.

I'm not sure if it makes sense for you, but I'll wait for a reply 😄

**Comment by olizilla** [comment]
Totally makes sense. This is only gonna appear for existing users, and I I think it's probably more confusing to see that I'm sharing 180MB that I can't see, so I'd vote for making the entire repo browsable. That way people can review and choose what they host.

This could be tackled as part of the IPFS Dashboard, and have way to open it from Desktop. But in that case the label "Files" is misleading if it's actually going to stay as "things I have uploaded via Desktop".

**Comment by olizilla** [comment]
Perhaps a simple change would be to add divider to the files section pane, with "Recently added" at the top, and empty in the case of a new install, and then the files from the existing repo listed out below the divider.

**Comment by olizilla** [comment]
@hacdias I've been meaning to get stuck into the IPFS Desktop code, so I'll put together a PR for you to take a look at with that idea in.

**Comment by hacdias** [comment]
Sure! I think it's a great idea 😄 Will wait for the PR then.

**Comment by olizilla** [comment]
Ok, so if you've not uploading anything via desktop, but you have files in your repo, as an incremental improvement I'm proposing something like this

**mockup**
![ipfs-desktop-recently-added-files](https://user-images.githubusercontent.com/58871/34832753-a8d9bfca-f6e5-11e7-80e3-e34d647c44a2.png)

**Comment by hacdias** [comment]
@olizilla looking at that interface it seems to bit too... hmm... "heavy" you know? You can only see two files per "category". Would there be an option to hide the "all files" section? What do you think about diving it in two columns instead of two rows?

**Comment by olizilla** [comment]
I'm imagining that the "Recently added" section would grow as you add files to it. We could collapse the "All files" section if there are any recently added ones.

**Comment by hacdias** [comment]
I'm just not sure if we can retrieve the files we have on the repository programmatically. I couldn't find a command for it. The `ipfs files ls` command is for the Mutable File System.

**Comment by hacdias** [comment]
@olizilla this isn't using MFS. After being able to bundle the new file system on WebUI, I'll then start using MFS here.

Currently, this only adds a file to IPFS and then saves its hash on an internal state which is the wrong thing to do. By using MFS, we can have the files accessible through all of the interfaces without any trouble. 😄

**Comment by hacdias** [comment]
Current state:

![image](https://user-images.githubusercontent.com/5447088/35150297-d46290e0-fd11-11e7-818e-0a14e02d41e0.png)

**Comment by hacdias** [comment]
@akrych check this screenshot ^^ You can now click on folders to open them as you suggested when you tried it!
