### ISSUE TITLE
Make pinning hashes more intuitive

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#593]
Right now, the pin hash feature requires the user to enter an optional title and a hash and click the check mark to confirm.

![screen shot 2018-01-12 at 16 14 11](https://user-images.githubusercontent.com/58871/34884124-a5a9b5ac-f7b3-11e7-8869-b71f59a6185f.png)

It's not obvious from the UI that the user needs to fill anything out in the green bar. 

We can make this more intuitive by:
- Make it look more like a form. Use a less saturated background color, and add some framing to the input fields with a per input background color and/or border.
- Use a muted color for the placeholder text.
- Indicate required and optional fields.
- Change the placeholder text to show example content
  - title: My favourite pin
  - hash: QmHash...

As the title is optional, to make the action feel simpler, we could simply let the user enter a hash, pin it, and then make it easy for them to add a label while it's pinning.

If you try to pin a hash you already have pinned, we should informed the user, and scroll to the item in the list. Right now the new pin name (or empty name) overwrites any existing label you might have.

To be able to label an unlabelled pinned hash the user needs a way of previewing or opening the file to see what it is.

The add pin icon might be more intuitive in the top right corner, as a button with text for "Add". This applies to the "Add files" action on the files pane too.

**Comment by hacdias** [comment]
Hey @olizilla! You're right: the current interface is not the best and doesn't speak for itself. Would you mind to do some kind of sketch to show the way you think the form should be? 😄

**Comment by hacdias** [comment]
@olizilla any updates on this? 😄

**Comment by lidel** [comment]
I suggest we should wait for canonical icons for pin actions: https://github.com/ipfs-shipyard/ipfs-ui-style-guide/issues/3#issuecomment-358105234

**Comment by nothingismagick** [comment]
The checkmark and the green color together make it seem like it was successful before the user even interacts. It always makes me pause when I see it.

**Comment by lidel** [comment]
Ditto.  Let's redirect discussion related to pinning/adding to:

- Design: Pinning Content https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/10

**Comment by hacdias** [comment]
Closing as unrelated to the newer version.
