### ISSUE TITLE
Pinned hashes don't show up

### ISSUE THREAD

**Issue by Cole128** [ipfs-shipyard/ipfs-desktop#600]
I have just started using IPFS Desktop, and noticed that my pinned hashes weren't listed in the Pin tab. But when I run `ipfs pin ls` in the command line I get several hashes, including non-default ones. These hashes were pinned before I used IPFS desktop, but shouldn't it still see them?
EDIT: I'd like to add that hashes pinned through IPFS desktop show up in the command line, just not the other way around. I'd like to also say that when I add a file, it doesn't show in the pin tab as well, even though files you add are automatically pinned.

**Comment by hacdias** [comment]
Hello @Cole128! I'm preparing a PR (#596) with a lot of bug fixes and I'll add this one to the list 😄 The problem is that, right now, we are using a file to match the tags to the hashes and only the hashes you pinned using Desktop will be on that file, but it will change soon!

**Comment by Cole128** [comment]
Thanks, that sounds great. Is there any way for me to get notified when that happens?

**Comment by hacdias** [comment]
Yeah, sure. I just can't give you a ETA about that PR.

**Comment by Cole128** [comment]
Alright, I just don't want to miss it. As long as you add to a mailing list or something. 
colecmac@gmail.com

**Comment by Cole128** [comment]
Thanks, I'll download it.

**Comment by Cole128** [comment]
It still doesn't show hashes I've pinned through the command line. 😞

**Comment by hacdias** [comment]
Let's reopen this then. I'll check it when I get back to my computer.

**Comment by hacdias** [comment]
@Cole128 right now, there are two issues I can identify that can be related to your problem:

1. `indirect` pins are now shown.
2. The list isn't refreshed at a defined interval.

**Comment by Cole128** [comment]
@hacdias Ok, that sounds like it would cause my issue for sure. It should be recursive pins only, with the list updating every few seconds if you're on the pinned tab or update immediately when you switch to the tab, right?

**Comment by hacdias** [comment]
@Cole128 oops... I misspelled "not" and wrote "now". It was supposed to show recursive **and** direct pins right now. But it isn't refreshing at a constant rate. I'll open a PR for this and ask you to try it out 😄

**Comment by Cole128** [comment]
@hacdias Alright, sounds great! Although I have a question about showing indirect pins: Why would you want to? My understanding is that indirect pins are just the hashes for blocks, the hashes for subsections of files that you've pinned. 

You can't access these hashes directly (you get an error), they are only for usage by the nodes. As a user, I find that they clutter a pinned list because I only want to see the hashes of the files I pinned, and seeing hashes I didn't pin is confusing.

**Comment by hacdias** [comment]
@Cole128 yeah, it makes sense. So what I'm going to do is to refresh the pins every 1 or 2 seconds so it is always updated 😄

**Comment by Cole128** [comment]
Alright, sounds good. When you said makes sense were you referring to what I was saying about indirect pins, or what I said about refreshing?

**Comment by hacdias** [comment]
Both 😄

**Comment by Cole128** [comment]
Awesome! I love being able to help contribute to projects I like, and to actually talk to devs. Thank you for taking the time. Whenever you create the PR or a new version that fixes this, just send it my way and I'll happily test it out!

**Comment by hacdias** [comment]
@Cole128 😃 Take a look at #606
