### ISSUE TITLE
Pin files on other nodes

### ISSUE THREAD

**Issue by victorb** [ipfs-shipyard/ipfs-desktop#602]
Usually when I add something to IPFS, I add it to my local peer, save the hash, ssh into pollux (one of our storage hosts) and pin the hash there as well.

Would be nice to have this flow supported on ipfs-desktop, as I'm sure I'm not alone in doing this. 

I know the focus of ipfs-desktop is currently not on "power users" but to be as user friendly as possible, but opening up this issue for reminding ourselves in the future.

**Comment by machawk1** [comment]
This goes hand-in-hand with interacting with other IPFS daemons from IPFS-Desktop, be it the one installed on the system independent on IPFS-Desktop (e.g., tell the system daemon to pin it) or a remote daemon through its API endpoint.

**Comment by lidel** [comment]
There is a related UX discussion at: https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/36

**Comment by roscoevanderboom** [comment]
if pinning is the way to make file links permanent, shouldn't it be part of the adding process by default?
also pinning the content of trusted peers should be as easy as browsing to their shared folder/content and one-click pin. 
once our peer-to-peer connectivity is secure, I would like to "ipfs add+pin+publish+share with (private or public), all in one step.

**Comment by hacdias** [comment]
Will close this issue on this repository and let the discussion flow on ipfs/ipfs-gui#36. We first need to know how to do the whole process before thinking about how to implement it on IPFS Desktop.
