### ISSUE TITLE
IFPS desktop doesn't work on Ubuntu?

### ISSUE THREAD

**Issue by PaddedGamer** [ipfs-shipyard/ipfs-desktop#603]
Do I need to turn off IFPS companion? Because my IFPS desktop server isn't working at all. I currently have 843 peers on IFPS companion. But zero people on my IFPS desktop. 

The peer ID, location information is completely broken. I installed it using the .deb file on Ubuntu 16.04.  

![ifps is broken](https://user-images.githubusercontent.com/6026744/35455701-d0fecee8-0287-11e8-8d36-6eed70125efe.png)

**Comment by hacdias** [comment]
Hey @PaddedGamer! Right now, IPFS Desktop can't connect to already existent daemons. Could you try switching off all the daemons you have running and then restarting Desktop?

The last time I tried those binary, it was working on Linux Mint (haven't tried directly on Ubuntu).

**Comment by PaddedGamer** [comment]
I just restarted my PC after shutting down daemon and then ran the application. Unfortunately, it hasn't resolved the issue.

**Comment by hacdias** [comment]
Let's debug then: could you set the env variable DEBUG to `'desktop'` before running Desktop? And if it doesn't show anything that looks like errors, you can also open the developer tools inside Desktop with CTRL-SHIFT-I.

**Comment by PaddedGamer** [comment]
What command do I run in order to set the env variable? Sorry for asking, but I'm just not failure with the terminal command. I tried opening the developer tools using the shortcut and nothing opened up.

**Comment by PaddedGamer** [comment]
I accidentally found a solution to the problem. I had to delete my .ipfs folder entirely and then reboot the application.

Basically, what never happened was the installer. When I installed the .deb file, it didn't give a first time setup menu. Deleting the config folder forced the application to give me a first time setup installer.

**Comment by hacdias** [comment]
I see. Although, it was supposed to work with an already existent installation! I'll try to figure out what might have been wrong.
