### ISSUE TITLE
repo.lock does not delete automatic after closing ipfs-desktop

### ISSUE THREAD

**Issue by wintuxx** [ipfs-shipyard/ipfs-desktop#610]
Hello!

After closing and restarting ipfs desktop i get a error that ipfs is still running.

i find out, that the problem is the repo.lock in the ipfs directory. Will it not delete after closing ipfs-desktop.

My System is Windows 10

**Comment by VictorBjelkholm** [comment]
@hacdias ipfs-desktop is using ipfsd-ctl right? Might be because graceful stop is missing: https://github.com/ipfs/js-ipfsd-ctl/pull/205 Similar issues is happening on the tests for ipfs/js-ipfs, that the repo is not properly closed.

**Comment by hacdias** [comment]
Yes, it is using ipfsd-ctl. I'm a Windows 10 user myself and I also have that problem! Although, I pushed a "fix" to delete that file if it wasn't locked to prevent this issue. But it was after the 0.3.0 release.
