### ISSUE TITLE
OpenSUSE Tumbleweed - Some unexpected error occurred and we couldn't handle it. 

### ISSUE THREAD

**Issue by bedri** [ipfs-shipyard/ipfs-desktop#612]
Hello,
I am getting this error in a window and cannot run the application. I compiled it from source and also installed it from rpm package but the result is the same. I also checked .config/ipfs-desktop/logs/error.log but that error.log file does not exist at all. The full error message in the window opened is given below:

> Some unexpected error occurred and we couldn't handle it. Please check /home/user/.config/ipfs-desktop/logs/error.log for the latest logs and open an issue on https://github.com/ipfs-shipyard/ipfs-desktop/issues.

Thank you in advance.

**Comment by hacdias** [comment]
Fixed today with #615 😄 
A new version will be released soon!

**Comment by bedri** [comment]
I am longing for it. Thank you :)
