### ISSUE TITLE
Minimize DHT bandwidth usage: switch node to `dhtclient` profile

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#619]
User installs IPFS Desktop. Has no files, but network monitor shows kilobytes of data going in and out.

### Solution

Until we have bandwidth controls in place, the `go-ipfs` node spawned by desktop app should stop acting as a DHT server. It can be done by passing the `--routing=dhtclient` flag to `ipfs daemon`.

### Y/n?

Are there any downsides to this change? It seems to make sense for "desktop" nodes:

> Eventually, we'll probably make this the default for non-server profiles (saves battery and will actually make the network faster as we'll have fewer flaky DHT nodes). –  @Stebalien  @ [discuss.ipfs.io](https://discuss.ipfs.io/t/do-i-need-to-manually-connect-to-every-member-in-a-network/1331/6?u=lidel)

**Comment by hacdias** [comment]
Yeah, but I think we should also provide a setting for this. I'll do this ASAP.
