### ISSUE TITLE
Adding thousands of files at once (EMFILE)

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#628]
It seems that adding a directory with thousands of files on it can cause the `EMFILE: too many open files` error.

Ref.: https://github.com/ipfs-shipyard/ipfs-desktop/pull/624#issuecomment-375607420

**Comment by magik6k** [comment]
Is this error returned by go-ipfs? If yes then it is likely a bug in flatfs (I think so), opened https://github.com/ipfs/go-ds-flatfs/issues/36.

Can you try this on a node with badger datastore - `ipfs init --profile=badgerds` or `ipfs config profile apply badgerds`+`ipfs-ds-convert convert --keep`?

**Comment by hacdias** [comment]
@magik6k could you test if you have this error with the [latest version](https://github.com/ipfs-shipyard/ipfs-desktop/releases/latest)?

**Comment by magik6k** [comment]
I'm assuming this should be done via the 'Files' screen. I can't add folders at all through there, it just fails with `Failed to add files to IPFS. Please try again.` - adding single file works fine. (running from source with `npm i` + `npm start`, node 11.5.0, npm 6.5.0)

**Comment by hacdias** [comment]
This bug was fixed on the latest version! Closing 😃
