### ISSUE TITLE
ipfs-desktop 0.4.0 bugs with debian package

### ISSUE THREAD

**Issue by kyledrake** [ipfs-shipyard/ipfs-desktop#630]
```
$ sudo dpkg -i ipfs-desktop_0.4.0_amd64.deb 
Selecting previously unselected package ipfs-desktop.
(Reading database ... 210948 files and directories currently installed.)
Preparing to unpack ipfs-desktop_0.4.0_amd64.deb ...
Unpacking ipfs-desktop (0.3.0-1) ...
dpkg: dependency problems prevent configuration of ipfs-desktop:
 ipfs-desktop depends on libgconf2-4; however:
  Package libgconf2-4 is not installed.

dpkg: error processing package ipfs-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 ipfs-desktop
```

Note the weird "0.3.0-1" versioning in the process, and the warning about a missing library. dpkg -l indicates that 0.3.0-1 is the one that was installed (forgot to change the version somewhere?)

When I run `ipfs-desktop`, an error message pops up asking me to read the error.log but the error.log has not been created yet.

Running `sudo apt-get install libgconf2-4` fixes the problem.

**Comment by hacdias** [comment]
@kyledrake updated!

**Comment by kyledrake** [comment]
I think it still needs to be told to install libgconf2-4 as a dependency:

```
 ipfs-desktop depends on libgconf2-4; however:
  Package libgconf2-4 is not installed.
```

**Comment by hacdias** [comment]
@kyledrake I'll put that note on Release Notes

**Comment by kyledrake** [comment]
@hacdias Is it possible to have that package get listed as a dependency? Debian should be installing that package automatically when the package is installed. Users shouldn't need to add it manually.

**Comment by lidel** [comment]
@kyledrake are you getting the error on upt-to-date Debian stable, or something else?

`.deb` attached to Release Notes  ([ipfs-desktop_0.4.0_amd64.deb](https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.4.0/ipfs-desktop_0.4.0_amd64.deb)) announces dep on `libgconf2-4` in its manifest:

```
dpkg-deb --info ~/tmp/ipfs-desktop_0.4.0_amd64.deb | grep libgconf2-4
 Depends: kde-cli-tools | kde-runtime | trash-cli | libglib2.0-bin | gvfs-bin, libgconf2-4, libgtk2.0-0, libnotify4, libnss3, libxtst6, xdg-utils
```

I tried to replicate the problem in docker with `debian:stable` image:
```
docker run -it --rm -v ~/tmp/ipfs-desktop_0.4.0_amd64.deb:/ipfs-desktop_0.4.0_amd64.deb debian:stable /bin/bash
apt update
apt install /ipfs-desktop_0.4.0_amd64.deb
```
..but dependency tree resolves fine:
```
Need to get 169 MB/235 MB of archives.
After this operation, 1068 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by kyledrake** [comment]
```
$ sudo apt-get remove -y libgconf2-4 ipfs-desktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libgconf2-4' is not installed, so not removed
The following packages will be REMOVED:
  ipfs-desktop
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 282 MB disk space will be freed.
(Reading database ... 226241 files and directories currently installed.)
Removing ipfs-desktop (0.4.0-1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
```

```
$ sudo dpkg -i ipfs-desktop_0.4.0_amd64.deb 
Selecting previously unselected package ipfs-desktop.
(Reading database ... 210953 files and directories currently installed.)
Preparing to unpack ipfs-desktop_0.4.0_amd64.deb ...
Unpacking ipfs-desktop (0.4.0-1) ...
dpkg: dependency problems prevent configuration of ipfs-desktop:
 ipfs-desktop depends on libgconf2-4; however:
  Package libgconf2-4 is not installed.

dpkg: error processing package ipfs-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 ipfs-desktop
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

Never seen this issue with any other package before. It seems to recognize the dep but then doesn't install it?

**Comment by hacdias** [comment]
@kyledrake since it is already on the manifest as a dependency, I don't really know what I can do to help. The package seems to be fine.

**Comment by lidel** [comment]
Ok, I see now why it worked for me and not for Kyle. I was using `apt install`. 

AFAIK `dpkg -i` does not install deps. It fails if any of dependencies are missing and that is _expected_ behaviour of that tool.  If you want to install missing deps automatically, you need to follow it with `apt-get -f install` or use modern `apt install`.

Starting with apt 1.1 (Ubuntu 16.04, Debian Stretch) `apt install` allows local files and now became the default way to install `.deb`

@kyledrake  Give it a try, it does the same job as `dpkg + apt-get` but with one clean command:
```
sudo apt install ./ipfs-desktop_0.4.0_amd64.deb
```

I've added this note to Release Notes and  to `README` in PR #634.
