### ISSUE TITLE
Bad UX on pinning big ipfs-pack trees

### ISSUE THREAD

**Issue by nothingismagick** [ipfs-shipyard/ipfs-desktop#633]
I have a pinset (actually a folder with subfolders and lots of files from ipfs-pack) and I want to be able to ipfs-get the whole thing to my computer with ipfs-desktop... Will that work? Would it work with ipfs-cluster?

I also have tried adding the peer ID of the ipfs-pack daemon, but nothing. 

I added the Pack Root Hash, but all I see is nothing and a moving yellow bar...

![screen shot 2018-03-29 at 17 50 03](https://user-images.githubusercontent.com/35242872/38098969-a775b3ca-3379-11e8-8166-aa18b47c9bba.png)

I am on OSX 10.12.6 using 0.4.0...

**Comment by lidel** [comment]
Pinning huge data set started, but it probably takes time and the only visual feedback that something is happening is yellow spinner. Ouch. This is an important data point, thank you for reporting.

Ideally, app should detect that data fetch takes longer than a few seconds and display some kind of progress bar and ETA (like in torrent client or other download manager). 

Good news is that we are designing better UI abstractions for Pinning/Adding in GUI apps that will address these problems.

Check relevant discussions:

- Design: Pinning Content https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/10
- Design: Add files to IPFS https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/35#issuecomment-373929197

**Comment by hacdias** [comment]
Closing as unrelated to the newer version.
