### ISSUE TITLE
[Suggestion] Adding the possibility of manually executing the garbage collector

### ISSUE THREAD

**Issue by JanSeW** [ipfs-shipyard/ipfs-desktop#635]
#### Components
*IPFS Desktop* is a standalone version of an IPFS node with a user-friendly UI. The application is for users who do not like or do not want to work with a CLI at all.

The *garbage collector* (part of an IPFS installation) is used to manage the local repository and deletes unpinned content from it, when it is executed or triggered by the values from the config file (normally 10 GB).

#### Proposal
The garbage collector is triggered by the values defined in the configuration file, but cannot be started manually by the user. To do this, an appropriate CLI-compatible package (e.g. *go-ipfs*) must first be installed in order to access the repository. This way is extremely inconvenient and not suitable for a user with little IT knowledge. But IPFS Desktop is especially aimed at these users.

Adding a button, which starts the garbage collector manually, allows users to easily and cleanly remove content that is not pinned (e.g. if illegal content was loaded by mistake). This will attract more users to install a local IPFS node.

#### Mockups / Examples
One possibility to place this function would be in the settings.

![Alternative link to the mockup: https://i.imgur.com/FsjL8e0.jpg](http://gateway.ipfs.io/ipfs/QmQfXsixUzdJ8R7mg4XGTberf8MSdLdRZCvpY1cmwktEuT)

#### Benefits
- Users without CLI knowledge can easily clean up their repository.
- This removes the fear that inexperienced users can share illegal content and cannot stop it without deleting the entire IPFS installation.
- As a result, more people will be able to use IPFS Desktop and the IPFS will grow.
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@janse/adding-the-possibility-of-manually-executing-the-garbage-collector">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hacdias** [comment]
@JanSeW actually this is a very good idea and I don't really know why we didn't have this before. I liked it so much that there's already a PR for it (#636).
