### ISSUE TITLE
Why is it using bandwidth when I have no files yet?

### ISSUE THREAD

**Issue by balupton** [ipfs-shipyard/ipfs-desktop#637]
![screen shot 2018-04-12 at 9 45 10 pm](https://user-images.githubusercontent.com/61148/38681314-ed6f25ec-3e9a-11e8-8f4b-dfa2bc78524f.png)
![screen shot 2018-04-12 at 9 45 18 pm](https://user-images.githubusercontent.com/61148/38681315-ed6f504e-3e9a-11e8-8a32-b9f4816ffc10.png)
![screen shot 2018-04-12 at 9 45 22 pm](https://user-images.githubusercontent.com/61148/38681316-ed74d0c8-3e9a-11e8-899d-2ac66bcdb725.png)
![screen shot 2018-04-12 at 9 45 56 pm](https://user-images.githubusercontent.com/61148/38681317-eda96162-3e9a-11e8-9e96-59d464ce5f0f.png)

Been installed and running for about 5 minutes.

**Comment by lidel** [comment]
That looks high indeed. 
- Was the "DHT client profile" (settings)  enabled by default, or did you just enable it? (it requires restart)
- Did you pin anything? 
- Are you able to run `ipfs rep stat` ?

**Comment by roscoevanderboom** [comment]
will an ipfs connection consume bandwidth, even when not browser or adding files?

**Comment by hacdias** [comment]
We're now using the flag `--routing=dhtclient` by default to avoid consuming a lot of bw.

**Comment by lidel** [comment]
cc https://github.com/ipfs-shipyard/ipfs-webui/issues/848 in case someone experiences high bw usage when opening Web UI :)
