### ISSUE TITLE
Add a PPA/repo for ubuntu

### ISSUE THREAD

**Issue by mkg20001** [ipfs-shipyard/ipfs-desktop#638]
This would allow auto-updates of the debian package.
I've create a simple repo @ https://deb.mkg20001.io/ipfs with https://github.com/mkg20001/ppa-script ([config used](https://ipfs.io/ipns/deb.mkg20001.io/config.ipfs.sh))
_(This could - and should - be moved to the IPFS infrastructure)_

Installing the PPA:
```sh
curl -s https://deb.mkg20001.io/key.asc | sudo apt-key add -
echo "deb https://deb.mkg20001.io/ipfs $(lsb_release -cs) beta" | sudo tee /etc/apt/sources.list.d/mkg.list
```

**Comment by hacdias** [comment]
Closing in favour of #691.
