### ISSUE TITLE
Hangs during installation on Windows

### ISSUE THREAD

**Issue by akavel** [ipfs-shipyard/ipfs-desktop#639]
I tried installing on Windows (IPFS.Desktop-0.4.2.Setup.exe). I changed the "installation directory" to `d:\ipfs` (the same path that I've been using previously as IPFS_PATH with go-ipfs client). Then I click "install" and the installer seems to hang...

![issue-ipfs-desktop-installer-hang](https://user-images.githubusercontent.com/273837/39266320-00155322-48ca-11e8-96e9-7f613063b99f.gif)

Are there some logs somewhere that I could attach?...

**Comment by hacdias** [comment]
Closing as unrelated to the newer version.
