### ISSUE TITLE
Try it out with js-ipfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-desktop#641]
With Electron 2.0 and js-ipfs 0.29, ipfs-desktop should also be capable of working with js-ipfs. See more here https://github.com/ipfs/notes/issues/256#issuecomment-392434248

**Comment by diasdavid** [comment]
@hacdias can you add a mode for js-ipfs, like IPFS Companion does?

**Comment by hacdias** [comment]
Will work on this, yes 😄
