### ISSUE TITLE
Doesn't work with Node.js 10.7 at the moment.

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-desktop#645]

**Comment by hacdias** [comment]
Working on PR #644 with Node 10.8 and it works. May be a dependencies issue. I won't merge it until Jenkins works again though. /cc @VictorBjelkholm

**Comment by VictorBjelkholm** [comment]
@hacdias CI runs `8.11.3` and `10.4.1` currently, which was the current versions last time we changed. Anything you need from CIs side to have this working?

**Comment by hacdias** [comment]
@VictorBjelkholm it keeps saying there are incompatible modules https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-desktop/detail/PR-644/3/pipeline

**Comment by hacdias** [comment]
@VictorBjelkholm it seems to run on 9.2 https://github.com/ipfs/jenkins-libs/blob/master/vars/electronForge.groovy#L48

**Comment by VictorBjelkholm** [comment]
@hacdias right, my mistake, was looking at the `javascript` pipeline. Updated to `10.4.1` here https://github.com/ipfs/jenkins-libs/commit/7b47b73503bdc9532a188b36ab3b3209013f82fb and started another run: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-desktop/detail/PR-644/4/pipeline/13

**Comment by hacdias** [comment]
Cool! Thanks!! macOS and Linux already passed. Waiting for Windows
