### ISSUE TITLE
productName can't have spaces with latest electron-forge

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-desktop#647]
https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/package.json#L3

**Comment by hacdias** [comment]
@diasdavid where did you find that information? I can't seem to find it.

**Comment by diasdavid** [comment]
@hacdias try to build the app, it will error and give you that log.

**Comment by hacdias** [comment]
I did and I did not receive errors. It just says:

```
Attempting to build a module with a space in the path

See https://github.com/nodejs/node-gyp/issues/65#issuecomment-368820565 for reasons why this may not work
```

But it doesn't fail and builds the modules successfully with spaces. But I'll try to figure out if I really need to change that.

**Comment by hacdias** [comment]
Closing as unrelated to the newer version.
