### ISSUE TITLE
Remove the pinning feature

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#652]
Some time ago (one year ago more or less), the WebUI moved from Pinning to using the MFS entirely.

Since we're going to incorporate the new WebUI in the following months on Desktop, I also suggest removing the Pinning feature from it so the users start getting more comfortable with MFS.

Feedback needed: @diasdavid @ipfs-shipyard/gui

**Comment by lidel** [comment]
cc highly relevant discussion @ https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/10#issuecomment-373928862

**Comment by lidel** [comment]
https://github.com/ipfs/ipfs-gui/issues/10#issuecomment-415683436:
> This is an important point to look at after we finish the new WebUI. IPFS Desktop currently provides pinning and I believe a lot of people will notice we took the pins away. Right now, their labels are being written on a `.pinset` file.
> 
> I'd like to release a new version removing the pinning feature, moving the files to a Pin folder on MFS. What do you think? That way the users could start getting used to it.

@hacdias  I am afraid if we name it "Pin" in MFS it will increase confusion even more.
People may  assume it is a permanent part of experience and that only content inside of that one directory is pinned. And we kinda want to remove the "pin" word from GUI.

I feel its safer to wait until WebUI is ready to be shipped with IPFS Desktop, and then do the change once:
- remove pinning feature from Desktop's UI
- make it possible to  open WebUI's Files screen via one click
- on first start detect and  convert `.pinset` to a directory with self-evident name, eg. `pinset_from_old_ipfs-desktop` + optionally display info and a link to the directory in  WebUI/Files.
  (idea is to indicate this is one-time thing and it is up to user to manage them now)

**Comment by hacdias** [comment]
@lidel actually, that might happen, yes. I like your idea to move everything when we ship WebUI with Desktop! 😄 Let's keep this opened and get back to it when it's time

**Comment by hacdias** [comment]
As we've talked @lidel, the pinning tab has some flaws and bugs right now and it's completely unusable. There are two options:

1. Fix it, which might require rewriting the whole pinning thing for IPFS Desktop.
2. Implement the flow you suggested above and add an option to Files tab to Add by Path (easiest and the way we're doing in the future anyways).

/cc @ipfs-shipyard/gui @diasdavid

**Comment by lidel** [comment]
I'm quite sure we  don't want to invest time in codebase that will be removed in near future (been there done that with old Firefox SDK).   Second option is a sensible way to go IMO.

@hacdias Just to clarify what you mean by (2), my understanding is that you want to:

1. remove Pinning tab from Desktop's UI
2. <del>make it possible to  open WebUI's Files screen via one click</del> (not possible yet, waiting for WebUI)
   -  Instead, keep using current Files tab, but add a button for adding assets via IPFS Path (in addition to already existing option to add assets from local machine).
3. on first start detect and  convert `.pinset` to a directory with clear name, eg. `pinset_from_old_ipfs-desktop` + optionally display short dialog info, eg.  _"Pinned assets were moved to <dirname>. Everything in Files tab is implicitly pinned. You can add new files from the local machine or via IPFS Path."_
  (idea is to indicate this is one-time thing and it is up to user to manage them now)

Y/n?

**Comment by hacdias** [comment]
@lidel Exactly that!
