### ISSUE TITLE
new version, install ipfs, path error

### ISSUE THREAD

**Issue by StepOITD** [ipfs-shipyard/ipfs-desktop#656]
I was trying to understand the project, and met this at staring phase:

![1571535699484_ pic_hd](https://user-images.githubusercontent.com/14295658/44898044-5ae82980-ad30-11e8-84b6-4b140e028f3e.jpg)

**Comment by hacdias** [comment]
Hello @StepOITD! I can see you're also using macOS. There is one more report of this issue. Are you running from the command line?

If so, could you see the logs path (given in the first log message) and see if there is a config.json file there and paste it here?

**Comment by nrpalao** [comment]
[Former report on the same issue https://github.com/ipfs-shipyard/ipfs-desktop/issues/631#issuecomment-416973038]

@hacdias could you please provide some more guidance on how to retrieve the `config.json` related to the apparent path on the error view? Haven't been able to find it yet.

**Comment by StepOITD** [comment]
@hacdias Hi, I think I found that file
![image](https://user-images.githubusercontent.com/14295658/44945946-11c5d180-ae25-11e8-9e35-c80ab7cafeee.png)
And I checked that this is the file mentioned in log message
![image](https://user-images.githubusercontent.com/14295658/44945966-6a956a00-ae25-11e8-8046-3da1c8c619a4.png)

I have ipfs-go installed on my mac before, but I have uninstalled and used docker. I'm thinking maybe it's due to environment variables or what ?

**Comment by StepOITD** [comment]
@hacdias solved, thanks for helping!

**Comment by hacdias** [comment]
@StepOITD no problem. I guess there might be an issue with configuration migration but I'm not sure why. It would only happen if `ipfsPath` was set to `null` before.

**Comment by hacdias** [comment]
For those coming here with this issue, please do as I said on https://github.com/ipfs-shipyard/ipfs-desktop/issues/656#issuecomment-418301293 and it will work. I've already pushed a fix. 😄
