### ISSUE TITLE
 How to download files 

### ISSUE THREAD

**Issue by jieweili** [ipfs-shipyard/ipfs-desktop#658]
I didn't find a place where I could download files.

**Comment by hacdias** [comment]
@jieweili currently we don't have a streamlined way to download files. If they are files and not folders, clicking on them will most likely work as they'll open in the web browser.

If it's a folder, you'll need to download them one by one.

It will change soon as we approach the release of the new WebUI version. We'll then work on IPFS Desktop to make it more IPFS-y and much better!
