### ISSUE TITLE
How to generate  IPFS.20Desktop-0.5.0.20Setup.exe

### ISSUE THREAD

**Issue by jieweili** [ipfs-shipyard/ipfs-desktop#659]
I hope I can get help.

**Comment by hacdias** [comment]
You can:

1. Clone the repository.
2. Execute `npm install`.
3. `npm run make`.

And it will build the Windows binary if executed on Windows. Sorry for not having it available to download on our page, but our CI is failing on Windows and it wasn't possible to solve the issue yet.

**Comment by jieweili** [comment]
![default](https://user-images.githubusercontent.com/4555301/45581641-9d833780-b8d4-11e8-8859-2983260a0389.png)

**Comment by jieweili** [comment]
run as administrator
error 

EPERM: operation not permitted, scandir 'C:\Users\x\AppData\Local\Temp\electron-packager\win32-x64\IPFS Desktop-win32-x64\resources\app\node_modules\abab'

**Comment by hacdias** [comment]
@jieweili try cleaning node_modules and doing everything again. NPM has some permission issues on Windows. Although I can't reproduce it here
