### ISSUE TITLE
How do I increase the function of downloading files?

### ISSUE THREAD

**Issue by lockzero0** [ipfs-shipyard/ipfs-desktop#663]
How do I increase the function of downloading files?

I also hope to increase the download progress display function.

**Comment by hacdias** [comment]
Hello @lockzero0! We're working on a new version with IPFS Web UI bundled with IPFS Desktop. Then, you'll have all the advantages that come from IPFS Web UI and Desktop together!

**Comment by hacdias** [comment]
@lockzero0 [we have a new release ready](https://github.com/ipfs-shipyard/ipfs-desktop/releases/latest)! Please try it out 😄
