### ISSUE TITLE
Tweak default config of IPFS node

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#665]
Default settings of go-ipfs are not optimized for Desktop use.

Let's collect things IPFS Desktop should set during repo init.

Initial ideas:
-  [x] Enable GC - https://github.com/ipfs-shipyard/ipfs-desktop/pull/826
-  [x] We should limit on the number of connections, as it is known to choke cheap consumer routers and wifi cards. Some insight on sane  defaults is max of ~300 conns:  https://github.com/ipfs/go-ipfs/issues/1482#issuecomment-427346155 - https://github.com/ipfs-shipyard/ipfs-desktop/pull/828
- [x] Make sure dhtclient remains to be set :) (https://github.com/ipfs-shipyard/ipfs-desktop/issues/619)

cc #661

**Comment by olizilla** [comment]
See also https://github.com/ipfs/go-ipfs/issues/4989

**Comment by lidel** [comment]
I think now that https://github.com/ipfs-shipyard/ipfs-desktop/pull/828 is merged we got MVP  :)
