### ISSUE TITLE
Can't tag more than one pin

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#680]
A video is worth a thousand words : 

![2018-11-05_10-40-19](https://user-images.githubusercontent.com/10495562/48008318-6ddbf900-e0e7-11e8-943f-58c1c8909198.gif)

![4](https://user-images.githubusercontent.com/10495562/47887463-dab87000-de15-11e8-9b9a-da8ba8eb303e.PNG)

**Comment by hacdias** [comment]
I'll close this since the new version we're working on doesn't include this feature (it will be even better!).

**Comment by NatoBoram** [comment]
Oh! I'm looking forward for better ways to recognize my pins! :)

**Comment by hacdias** [comment]
You'll be able to add as much files as you want! 😄
