### ISSUE TITLE
fail to build source code 

### ISSUE THREAD

**Issue by royforu** [ipfs-shipyard/ipfs-desktop#690]
hello everyone,
Sorry to bother. When I build source code, I encounter one problem. can not find file: openssl/rsa.h 
C:\Users\royhsu\ipfs-desktop>npm start

> ipfs-desktop@0.5.0 start C:\Users\royhsu\ipfs-desktop
> electron-forge start

√ Checking your system
√ Locating Application
× Preparing native dependencies: 6 / 7

An unhandled error has occurred inside Forge:
�b���ѨM��פ��@���ظm�@�ӱM�סC�Y�n�ҥΥ���ظm�A�зs�W "/m" �ѼơC
  ursaNative.cc
  win_delay_load_hook.cc
c:\users\royhsu\ipfs-desktop\node_modules\ursa-optional\src\ursanative.h(13): fatal error C1083: �L�
k�}�ҥ]�t�ɮ�: 'openssl/rsa.h': No such file or directory (���b�sĶ��l�{���� ..\src\ursaNative.cc) [C:\
Users\royhsu\ipfs-desktop\node_modules\ursa-optional\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\B
in\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\royhsu\ipfs-desktop\node_modules\node-gyp\lib\bu
ild.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\royhsu\\ipfs-desktop\\node_module
s\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.7" "--arch=x64" "--dist-url=https://atom.io/d
ownload/electron" "--build-from-source"
gyp ERR! cwd C:\Users\royhsu\ipfs-desktop\node_modules\ursa-optional
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
==================================================
my environment:
os: win7
nodejs version: 10.13.0
npm version: 6.4.1
openssl version: 1.0.2p
also use npm install --global windows-build-tools
Did I miss something? 
Thanks for everybody's help~~

**Comment by hacdias** [comment]
To build on windows, you need [`windows-build-tools`](https://www.npmjs.com/package/windows-build-tools). I can assure you it will work since it's the platform I use 😄  Do not forget though that `new` isn't finished.
