### ISSUE TITLE
Mac OS X Mojave 10.14.1, can't start up ipfs-desktop

### ISSUE THREAD

**Issue by Maxzong** [ipfs-shipyard/ipfs-desktop#693]
Following the steps in https://github.com/ipfs/fs-repo-migrations/blob/master/run.md I finished ipfs update and migration, killed ipfa daemon process and open IPFS-Desktop. but there's some warning popped up.

**Some unexpected error occurred and we couldn't handle it. Please check /Users/maxzong/Library/Application Support/ipfs-desktop/logs/error.log for the latest logs and open an issue on https://github.com/ipfs-shipyard/ipfs-desktop/issues.**

I checked out the log, list below:

{"message":"Uncaught Exception: Error: non-zero exit code 1\n\n            while running: /Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon\n\n\n            **Error: Your programs version (6) is lower than your repos (7).\nPlease update ipfs to a version that supports the existing repo, or run\na migration in reverse.\n\nSee https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details**.\n\n    at Stream.listeners.done.once (/Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/ipfsd-ctl/src/exec.js:39:11)\n    at Stream.f (/Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/once/once.js:25:25)\n    at emitTwo (events.js:125:13)\n    at Stream.emit (events.js:213:7)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)","level":"error"}
{"message":"Launch on startup enabled","level":"info"}

IPFS info list below
bogon:bin maxzong$ ipfs daemon &
[1] 19303
bogon:bin maxzong$ Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.10.54/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.10.54/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

How could I solve this problem? 
<img width="423" alt="screen shot 2018-11-16 at 10 48 11 am" src="https://user-images.githubusercontent.com/17782773/48595121-6261bb00-e98e-11e8-89a2-286a11dbfad1.png">

@hacdias

**Comment by hacdias** [comment]
Hello! Did you download from releases? It doesn't have the latest version from master so you might experience issues. We're working towards a new version so keep tuned!

**Comment by phoniks** [comment]
I can confirm that the prepackaged binary works on my machine but the clone of the repo does not launch the menubar icon.  It does seem to start the IPFS daemon, however.  Looking forward to the new version!

**Comment by hacdias** [comment]
Which error do you get? Or you don't simply have any error?

/cc @olizilla can you reproduce this?

**Comment by hacdias** [comment]
The new version has this error fixed 😄 Please try it out
