### ISSUE TITLE
docs(README): Usage section missing despite ToC link

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/ipfs-desktop#699]
The README Table of Contents section links to a `Usage` section, which does not exist in the README.md document.

It looks like @hacdias's refactoring in 21e4545dcbf52bd6adf8cade538968013cb8fdca "toward 1.0" removed this but left the entry in the ToC.

**Comment by hacdias** [comment]
@machawk1 thanks for noticing that 😄
