### ISSUE TITLE
CI: Travis + AppVeyor

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#700]
Set up Travis and AppVeyor (for Windows) and auto-deploy the latest binaries to a GitHub pre-release.

**EDIT:** Travis now seems to support Windows! https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by hacdias** [comment]
Questions:
- Shall we move to Travis? Or stick with Jenkins?
- Shall we publish every push to master as a pre-release?
- Does Jenkins have secret management? Or at least some way to set an env variable with an API key?

/cc @ipfs-shipyard/gui

**Comment by daviddias** [comment]
great convo on CI happening here https://github.com/ipfs/infrastructure/issues/442

**Comment by lidel** [comment]
> ### Shall we move to Travis? Or stick with Jenkins?

I think we could try Jenkins (see the end of this comment) and if it does not work for us or require time commitment from infra team that blocks this endeavor then we could try Travis.

AFAIK in Travis we can configure secrets ourselves: 

- People with admin privileges  to this repo (eg. me) will see the below form at https://travis-ci.org/ipfs-shipyard/ipfs-desktop/settings:
  > ![2018-11-25--02-15-41](https://user-images.githubusercontent.com/157609/48974525-1c76b800-f05c-11e8-897e-fe149ae932d4.png)
  - It enables us to define environment variables and mark them as secrets to ensure they will not leak in build logs
  - Related docs: https://docs.travis-ci.com/user/best-practices-security/#Steps-Travis-CI-takes-to-secure-your-data

> ###  Shall we publish every push to master as a pre-release?

I feel it could be safer to have `beta` branch. That way you would create a "pre-release" PR that merges from `master` to `beta`, triggering the build.

In the future, we could have `release` branch as well, and it would work the same.

This would make release process easy and auditable (PR per release).

> ###  Does Jenkins have secret management? Or at least some way to set an env variable with an API key?

Depends on permissions your jenkins user has at [ci.ipfs.team/../ipfs-desktop](https://ci.ipfs.team/job/IPFS%20Shipyard/job/ipfs-desktop/).

In my case I see "Credentials":
> ![2018-11-25--02-29-07](https://user-images.githubusercontent.com/157609/48974449-44651c00-f05a-11e8-826b-8cb0bc4a95f4.png)

When clicked, new screan appears and I can switch "Kind" to "Secret text" -- those are injected as a raw secret string under environment variable "ID":

> ![2018-11-25--02-33-33](https://user-images.githubusercontent.com/157609/48974457-a45bc280-f05a-11e8-8685-faf819cdbbda.png)


Some related docs:
- https://wiki.jenkins.io/display/JENKINS/Credentials+Plugin
- https://wiki.jenkins.io/display/JENKINS/Plain+Credentials+Plugin
- https://support.cloudbees.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs

----

@hacdias  Hope this helps! 

Let me know if you don't have access to secrets management at Travis/Jenkins – I can set secrets for you.
Just remember to keep them.. secret  :upside_down_face: (send them via private channel).

**Comment by hacdias** [comment]
Closing this as CI is set up.
