### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#707]
When cloning the app, it seems like `package-lock.json` is present while it probably shouldn't, because it is changed when the package is built. It is a per-developer, developer-specific auto-generated file and should be discarded from the git repository.

As a side node, I think it would be appropriate to use [gitignore.io](https://www.gitignore.io/?templates=node,linux,macos,windows,visualstudiocode) to generate a proper template for the `.gitignore`

![1-before](https://user-images.githubusercontent.com/10495562/48951996-a7499c80-ef0e-11e8-9fed-d0108a26c697.png)
![2-after](https://user-images.githubusercontent.com/10495562/48951997-a7499c80-ef0e-11e8-8d75-21192c51246c.png)

**Comment by hacdias** [comment]
Hello @NatoBoram! Actually, `package-lock.json` was meant [to be committed into the repository](https://docs.npmjs.com/files/package-lock.json). It makes sure we all use the same version of each dependency.

**Comment by NatoBoram** [comment]
I might be wrong, but it doesn't seem to work like that. Installing dependencies trough `npm i` changes `package-lock.json` and updates them.

![image](https://user-images.githubusercontent.com/10495562/48970652-f3fba900-efdc-11e8-8a6b-a59276238a82.png)

My guess would be that dependencies are supposed to be fixed inside `package.json` and there's nothing we can do about `package-lock.json`.

**Comment by hacdias** [comment]
@NatoBoram if we use `npm ci` it will install the exact same dependencies without updating them: https://docs.npmjs.com/cli/ci. It's useful to use in test environments to make sure everything is the same.

**Comment by olizilla** [comment]
The idea behind `package-lock.json` is to publish and share a complete dependency tree for the app between all developers. On a good day, running `npm i` from from a fresh clone should not cause any changes to the `package-lock.json`, but historically this has not always been true, particularly for deps that are platform specific.

I hear you @NatoBoram that it is suprising to find a file has been changed after running `npm i`. We can reduce the likelyhood of that by all using the same version of `npm`. I'm using `v6.4.1`.

`npm ci` is a neat trick for getting your first copy of the `node_modules` dir in sync with everyone, but it shouldn't be required. `npm install` is the intended for developers to use. `npm` will tweak the `package-lock.json` format as there are improvements, and these will appear as suprising mutations to the lockfile from time to time.

**Comment by hacdias** [comment]
As @olizilla explained, we shall keep using the package-lock.json, hence we're not adding it to the the ignored list
