### ISSUE TITLE
Improve UX when $IPFS_PATH/api exists and API is offline

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#713]
The `$IPFS_PATH/api` file is used by a lot of developers to talk to remote nodes  (learning from ipfs-companion users). T

How to improve UX for "the API defined in `$IPFS_PATH/api` is offline" scenario?

Perhaps like this:

- IF `$IPFS_PATH/api` file exists and is different from the one in the `config` file
- AND IF multiaddr inside of `api` file points at remote API  which produces `ECONNREFUSED` error,
- THEN ipfs-desktop should inform user about the problem with connection to remote node at `{multiaddr}` and display error window with _built-in UI_ for dealing with it.

It could be a styled window similar to [this mockup](https://user-images.githubusercontent.com/58871/48784853-6ae22a80-ecdb-11e8-957c-e6c49c5548c0.png) but with nice UI to:
  - (A) Change value in `api` file
    - open file with `$EDITOR` or provide built-in editor directly in the error window [similar to what ipfs-webui does](https://user-images.githubusercontent.com/157609/48969821-911e0800-f004-11e8-9865-3de1fb662ff5.png)
  - (B) Run `ipfs repo fsck`
    - to remove `api` and potential lockfiles and try again (should be safe, technical user can always restore file by hand)
  - (C) Quit

**Comment by hacdias** [comment]
Reminder to self: https://github.com/ipfs-shipyard/ipfs-desktop/pull/711#pullrequestreview-178054088.

**Comment by lidel** [comment]
(updated description to reflect what we learned during today's sync call)

**Comment by hacdias** [comment]
I believe we can close this now as #722 was closed!

**Comment by lidel** [comment]
Just tested `master` @ 3b7c7812fa4ff717c4e16317ae6deefb5242c7e1  and having an empty `$IPFS_PATH` with `api` file alone produces this error:


```
Error: ENOENT: no such file or directory, open '/home/lidel/.ipfs/config'
```

**Comment by hacdias** [comment]
@lidel that error might be caused [by this line](https://github.com/ipfs-shipyard/ipfs-desktop/commit/3b7c7812fa4ff717c4e16317ae6deefb5242c7e1#diff-3fb9ae4a7e04ebf3125d50d302b3531eR21) which will be removed as soon as the CORS PR (#738) is merged 😄 So it won't be a problem as we won't be testing the existence of any files.

**Comment by hacdias** [comment]
That case is already solved. I'm closing this for now since we've already added the necessary logic for the scenarios here described.
