### ISSUE TITLE
npm ERR from npm install

### ISSUE THREAD

**Issue by waye750504** [ipfs-shipyard/ipfs-desktop#715]
Enviroment Setting :
ubuntu 18.04
NodeJs 11.2.0
Npm 6.4.1

Issud :

> ipfs-desktop@1.0.0 build:webui:fetch-ipfs /home/via/ipfs-desktop
> cross-env-shell "ipfs get $CID -o src/hooks/webui/app/"

/bin/sh: 1: ipfs: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ipfs-desktop@1.0.0 build:webui:fetch-ipfs: `cross-env-shell "ipfs get $CID -o src/hooks/webui/app/"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ipfs-desktop@1.0.0 build:webui:fetch-ipfs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/via/.npm/_logs/2018-11-23T11_28_13_203Z-debug.log

> ipfs-desktop@1.0.0 build:webui:fetch-http /home/via/ipfs-desktop
> cross-env-shell "node scripts/fetch-webui-from-gateway.js $CID src/hooks/webui/app/"

Fallback to HTTP GET from: https://ipfs.io/api/v0/get?arg=QmR6FjMewzJRuVq6e9RCbB7akjURSuoGqYxrUurTKS3QQ5&archive=true&compress=true
Status Code 200
Done! webui extracted to: src/hooks/webui/app/

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/via/.config │
└───────────────────────────────────────────────────────┘

**Comment by hacdias** [comment]
The error from `ipfs not found` is just a false alarm. Everything worked as expected. Although I've never seen `│ npm update check failed`. Is that the error you meant?

**Comment by olizilla** [comment]
`npm update check failed` looks like an error occured while `npm` was checking to see if there is a newer version of `npm`.

@waye750504 I believe this error is an issue with `npm`. Try running the command suggested in the error: 
```
sudo chown -R $USER:$(id -gn $USER) /home/via/.config
```

**Comment by hacdias** [comment]
I'm closing this since we add no further response. @waye750504 if you still have this issue with the latest version, please re-open the issue.
