### ISSUE TITLE
Upgrade to ipfs-go 0.4.18

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-desktop#716]
The [ipfs-go 0.4.16 release](https://github.com/ipfs/go-ipfs/releases/tag/v0.4.18) was released 25 days ago and contains some interesting features like QUIC-support.

**Comment by hacdias** [comment]
If you use the latest version from master, you'll have [go-ipfs 0.4.18](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/package.json#L88). We're planning the release soon!
