### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rudgh1368** [ipfs-shipyard/ipfs-desktop#718]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 3.0.10
- **Electron Version**: 3.0.10
- **Chrome Version**: 66.0.3359.181

**Error**

```
Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

**Comment by hacdias** [comment]
Closing in favor of #713
