### ISSUE TITLE
Fix devtron app lint warnings

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#719]
I got [Devtron](https://electronjs.org/devtron) installed in the devtools of IPFS Desktop. To access it I had to:

- `npm i --save-dev devtron`
- Open the dev tools on the webui window and detach them, then close it... just to get the dev tools window to default to opening in detached mode.
- Use the keyboard shortcut to open the dev tools on the main menubar window. <kbd>⌥</kbd> + <kbd>⌘</kbd> + <kbd>i</kbd> on macos.
- run `require('devtron').install()` in the dev tools console. (this doesn't work in the webui browser window devtools.)

but once that tricky process was out of the way, it offered up this list of electron app lint warnings that we should review and fix.

<img width="987" alt="screenshot 2018-11-28 at 11 44 22" src="https://user-images.githubusercontent.com/58871/49154112-8074d700-f30f-11e8-8b82-58f39b200bfc.png">

**Comment by hacdias** [comment]
After going through Devtron's warnings, they're all fixed by now. Closing this!
