### ISSUE TITLE
Can't start on Ubuntu 18.10

### ISSUE THREAD

**Issue by skomaromi** [ipfs-shipyard/ipfs-desktop#729]
Fresh clone from GitHub, commit ```f06cc59```.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 3.0.10
- **Electron Version**: 3.0.10
- **Chrome Version**: 66.0.3359.181

**Error**

```
Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

**Comment by hacdias** [comment]
Closing in favor of #713.
