### ISSUE TITLE
Desktop ask to control System Events on macOS on first run

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#753]
On first run on macOS, we get this dialog

<img width="532" alt="screenshot 2018-12-17 at 11 22 13" src="https://user-images.githubusercontent.com/58871/50084194-063cc180-01ee-11e9-84fd-f1d53ce5357f.png">

We should see if we can remove the need for the System Events, as I don't think we're doing  anything that directly needs it.

**Comment by hacdias** [comment]
Did you always get that or it was after a specific commit? On Windows it doesn't need any special permission. It doesn't even ask for Administrator permission unless you install it for the whole system.

**Comment by olizilla** [comment]
I get it when using desktop from the .dmg. I'll see what I can find out about it.

**Comment by fsdiogo** [comment]
Before that I get this:
<img width="532" alt="oops" src="https://user-images.githubusercontent.com/33324750/50218408-c0b1fd00-0383-11e9-9256-423f6e5d671a.png">

We can easily open it by right-clicking the app icon on the `Applications` folder an click `Open`, but many people don't know about this.

Is there a plan to identify the app so the user doesn't get this?

**Comment by hacdias** [comment]
@fsdiogo yes! https://github.com/ipfs-shipyard/ipfs-desktop/issues/66 😄

**Comment by meiqimichelle** [comment]
+1 to @olizilla 's experience -- same thing happened to me, also downloaded as .dmg .

**Comment by svitekpavel** [comment]
+1.

Also, from UX perspective the app is opened in background and put into Mac menu bar. However, the app in launch bar is not opened (there is not a dot under the icon - indicating the app is opened). I tried to open the app multiple times till I realised that I can access the app from menu bar. It would be great to see at least a message every time you try to open the app saying "IPFS Desktop is already running. You can access the app from menu bar."

**Comment by hacdias** [comment]
Well, we [only allow one instance at a time](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/src/index.js#L9-L18) and we tell the user if they try to launch Desktop more than one time. At least on Windows it is working, but I see macOS has different mechanisms. @olizilla @fsdiogo could you check that please?

**Comment by hacdias** [comment]
Closed in favour of #901
