### ISSUE TITLE
Menu bar always open in the main display

### ISSUE THREAD

**Issue by fsdiogo** [ipfs-shipyard/ipfs-desktop#756]
In a dual display setup, the IPFS Desktop menu bar works great if clicked in the main display:

<img width="333" alt="main-monitor" src="https://user-images.githubusercontent.com/33324750/50220166-7c296000-0389-11e9-8a72-38f6c88d48a0.png">

But if clicked in the secondary display, it opens up in the main one, on the bottom right corner of the screen:

<img width="590" alt="second-monitor" src="https://user-images.githubusercontent.com/33324750/50220314-f3f78a80-0389-11e9-8cee-90fff95d1c6d.png">

**Comment by fsdiogo** [comment]
@hacdias can you check if this happens on windows too?

**Comment by hacdias** [comment]
@fsdiogo those kind of icons (in the menubar) only show up on the main display on Windows so that problem doesn't exist here.

**Comment by fsdiogo** [comment]
Hmm, ok.. I'll take a look then!

**Comment by olizilla** [comment]
related issue from deep history https://github.com/ipfs-shipyard/ipfs-desktop/issues/586

**Comment by olizilla** [comment]
the fix for this will probably be in [hacdias/electron-menubar](https://github.com/hacdias/electron-menubar) https://github.com/hacdias/electron-menubar/issues/2

**Comment by meiqimichelle** [comment]
Related, I expect. It's not that the menu always opens on the main display, but on my second screen it opens reliably on the left-middle.

![screenshot 2018-12-21 13 09 56](https://user-images.githubusercontent.com/4827522/50361845-68653180-0522-11e9-9e43-2fee2ec52ed4.png)

**Comment by hacdias** [comment]
Ref: https://github.com/electron/electron/issues/13461
