### ISSUE TITLE
Snap install requires --dangerous flag

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#757]
Installs fine, but there is some metadata missing that triggers an error and needs to be bypassed with `--dangerous`:
```console
$ snap version                                                                       
snap    2.21-2+b1
snapd   2.21-2+b1
series  16
debian  9

$ snap install /home/lidel/tmp/ipfs-desktop_0.6.0_amd64.snap                         
error: cannot find signatures with metadata for snap "/home/lidel/tmp/ipfs-desktop_0.6.0_


$ snap install --dangerous /home/lidel/tmp/ipfs-desktop_0.6.0_amd64.snap
ipfs-desktop 0.6.0 installed
```

**Comment by hacdias** [comment]
Just a reference issue: https://github.com/electron-userland/electron-builder/issues/3187

**Comment by hacdias** [comment]
Electron Builder now supports publishing the package to the store and that's what I'm going to do. As far as I understood, by publishing it to the store, the dangerous flag won't be needed. Perhaps we don't even need to publish the `.snap` package to the GitHub releases anymore.

Thoughts @lidel?

**Comment by hacdias** [comment]
Published to Snap Store. Now you can just `snap install ipfs-desktop`!

**Comment by lidel** [comment]
@hacdias sgtm! https://snapcraft.io/ipfs-desktop  looks good

I don't use Snap, but see @elopio created one for go-ipfs (https://snapcraft.io/ipfs). @elopio – are you able to check if ipfs-desktop installs fine via `snap install ipfs-desktop`?

**Comment by hacdias** [comment]
@lidel I did try to install on Ubuntu and it seemed to work well too!
