### ISSUE TITLE
UX on Linux: needs additional click to access Web UI

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#758]
When I click on tray icon, a single-item context menu is displayed:

> ![2018-12-19_16-00](https://user-images.githubusercontent.com/157609/50228261-ca4d5c00-03a7-11e9-974c-879c949c58c2.png)

When I click on it the actual Menu opens as expected:

> 
![2018-12-19_16-16](https://user-images.githubusercontent.com/157609/50228974-84919300-03a9-11e9-9fc9-8047fbff1f2a.png)
I've seen this glitch in past, but was fixed some time ago. 
Not sure what could cause this. 

@hacdias  Was electron version updated recently or something? 
Should I go back in time and find a version without this glitch, so we can see what changed since then?

**Comment by hacdias** [comment]
Not really sure if the version of Electron was updated. If comparing to 0.5.0, yes, it was updated. Although I've never heard of this issue before. When you click the first time the icons are colored or faded out?

**Comment by hacdias** [comment]
This doesn't happen anymore 😃
