### ISSUE TITLE
Black screenshots - master branch

### ISSUE THREAD

**Issue by TheChiefMeat** [ipfs-shipyard/ipfs-desktop#772]
I just finished building the 0.6.0.exe from the master branch, and screenshots no longer work for me, I simply get black screenshots. I've tested this against the pre-release 0.6.0 build and screenshots work fine on that previous build.

Running Windows 10, dual monitors.

**Comment by hacdias** [comment]
Are you sure they work on pre-release 0.6.0 with **dual** monitors? Which OS are you using?

**Comment by hacdias** [comment]
Oh, maybe something changed on Electron's API. The screenshot's code wasn't changed, but I updated the Electron version to 4.0. I'll check! THanks

**Comment by TheChiefMeat** [comment]
No worries, I just did the exact same test on my other PC, Windows 10, dual monitors and the exact same issue is there; Black screenshots with master, fine on pre-release.

**Comment by hacdias** [comment]
Yes, it doesn't need to be dual monitors. With a single one it doesn't work either. Nor CTRL-SHIFT-I shortcut...

**Comment by hacdias** [comment]
@TheChiefMeat could you please check if #773 fixes the issue on your end?

**Comment by TheChiefMeat** [comment]
Fixes it, well done :)
