### ISSUE TITLE
Crash when attempting to quit again

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-desktop#776]
1. Open the tray and click Quit
2. Wait, get impatient, reopen tray, and Quit again

Crash.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.6.0
- **Electron Version**: 3.0.13
- **Chrome Version**: 66.0.3359.181

**Error**

```
Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

**Comment by hacdias** [comment]
Hello @da2x! Sorry for hearing this. Did it ever started up IPFS? Was the logo glowing?

**Comment by da2x** [comment]
@hacdias yes, I'd been using IPFS in the browser for a few hours. Then I wanted to quit the app (high CPU over several minutes). So opened the menu, clicked the quit icon, waited a minute, opened the menu again, and clicked quit again. The crash happen immediately following this. The state of IPFS was "exiting", so I don't really know whether it was running or not at the time.

**Comment by hacdias** [comment]
I'm closing this since I think it is closed on the latest pre-release. If any of this happens again, please let me know.
