### ISSUE TITLE
How to set the IPFS config in the source code

### ISSUE THREAD

**Issue by jianhuaixie** [ipfs-shipyard/ipfs-desktop#780]
I want to edit the source code to fix the IPFS config

**Comment by jianhuaixie** [comment]
> Hello! Just to check if I understood what you meant: you want to know where to set the IPFS repository path? Or you want to know where the IPFS configuration is?

I want to konw how to set the IPFS configuration in the source code.

**Comment by hacdias** [comment]
We start the daemon using [IPFS Daemon Controller](https://github.com/ipfs/js-ipfsd-ctl) on [src/utils/daemon.js](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/src/utils/daemon.js). Not sure if it helps.

**Comment by olizilla** [comment]
You can edit your IPFS config file that is stored at `$IPFS_HOME/config`. By defualt, that is the `~/.ipfs/confg`. You'll need to restart the app after saving changes to that file.

Are you trying to customise your IPFS node? Or are you trying to fix a bug with IPFS Desktop?

**Comment by AkshitV** [comment]
I have a similar query,
I wanted to make my own private ipfs network and needed to change the default bootstrap nodes to my own nodes, 
i tried eddititng daemon.js at line 79: 
          config.Swarm.ConnMgr.HighWater = 300
I changed the value to a new value to a new value, **but its not getting reflected in .ipfs/config file**
That is just an example, i want to change config.Bootstrap to my own nodes
Can someone help please

**Comment by olizilla** [comment]
Edit `.ipfs/config` directly then restart the daemon

**Comment by hacdias** [comment]
I'm closing this issue as the initial question seems to have an answer even though there was no more information.

@AkshitV sorry for taking so long. Will get to you on #950
