### ISSUE TITLE
Clicking once on 'Quit' doesn't work

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#781]
Prior discussion: https://github.com/ipfs-shipyard/ipfs-desktop/pull/779#pullrequestreview-189448408

![image](https://user-images.githubusercontent.com/5447088/50738829-2c8fc480-11d0-11e9-90c5-f785d91d65ac.png)

It seems that we need to click twice on Linux to make it exit.

**Comment by hacdias** [comment]
@lidel is still an issue?

**Comment by lidel** [comment]
Unable to reproduce with latest `master`. 
Probably got fixed at some point since January.
