### ISSUE TITLE
Add home and removable-media plug to the snap

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#782]
I launched IPFS-Desktop. At first I had plenty of errors, solved a bunch of them, but now I'm stuck.

Repo was probably migrated to badgerds at one point. `$IPFS_PATH` is set to `/mnt/HDD/IPFS`.

Permissions on `/mnt/HDD/IPFS` are the following : 

```bash
total 32
drwxr-xr-x 1 nato nato   86 Jan  6 17:36 .
drwx------ 1 nato nato  218 Dec 17 18:03 ..
drwxr-xr-x 1 nato nato 2744 Jan  6 17:31 badgerds
-rw-rw---- 1 nato nato 5348 Dec 18 14:42 config
-rw------- 1 nato nato   37 Nov 23 00:43 datastore_spec
drwx------ 1 nato nato   14 Nov 18 10:47 keystore
-rw-r--r-- 1 nato nato    2 Oct 13 11:50 version
```

A wild guess would be there's a problem with IPFS-Desktop's snap connections, preventing it from accessing user-defined `$IPFS_PATH`.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.6.1
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: Command failed: /snap/ipfs-desktop/x1/resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon --migrate=true --routing=dhtclient
Error: error opening repository at /mnt/HDD/IPFS: permission denied


    at makeError (/snap/ipfs-desktop/x1/resources/app.asar/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/snap/ipfs-desktop/x1/resources/app.asar/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hacdias** [comment]
Hey! The user that's executing Desktop has permissions to access the repository?

**Comment by hacdias** [comment]
Could you try running `ipfs daemon --migrate=true --routing=dhtclient` manually and see if it works?

**Comment by NatoBoram** [comment]
It seems that it's a limitation of snaps, I think they can't read outside of `$HOME` and `/media`. https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1643706

That leads to other problems like https://github.com/elopio/ipfs-snap/issues/16.

In my particular setup, `ipfs daemon --migrate=true --routing=dhtclient` would have worked since I was already using `ipfs` compiled from source prior to trying IPFS Desktop.

A possible workaround would be : 

1. Catch a `permission denied`
2. Check if `$IPFS_PATH` exists
3. Create a simlink from `~/.ipfs-desktop` to `$IPFS_PATH`
4. Set `$IPFS_PATH` to `~/.ipfs-desktop` for the current session
5. Launch the node again.

That would allow IPFS Desktop to use the user-defined `$IPFS_PATH` in a somewhat hacky but non-breaking way.
