### ISSUE TITLE
Self-destructed on auto-update from v0.6.0 to v0.6.1

### ISSUE THREAD

**Issue by da2x** [ipfs-shipyard/ipfs-desktop#783]
I just had v0.6.0 auto-upgrade to v0.6.1. Some unseemly terminal windows popped up on screen and disappeared almost immediately. The `resources` directory was removed during the update. The app is completely unusable after the update:

```
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'c:\Program Files\IPFS Desktop\resources\electron.asar\browser\init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
```

**Comment by hacdias** [comment]
@da2x what OS are you using? It would be helpful to know. We're aware that it's working on Windows but not on macOS/Linux.

**Comment by da2x** [comment]
This was on Windows 10.

**Comment by hacdias** [comment]
That's strange. On my Windows 10 computer I received a notification saying the new version has been downloaded and that it would be installed after quitting the app. Then I closed the app, reopened, and there it was the new version. It didn't even show up any console window.

Did you also receive the notification?

**Comment by da2x** [comment]
I didn’t receive any notifications, but I did indeed quit the app when the UAC dialog (unexpectedly, I might add) asked for permission to run an executable. I knew IPFS Desktop had recently added auto-update and I knew a new pre-release was out. I assumed that was what triggered the dialog.

The executable was unsigned so I could have run just about anything.

**Comment by hacdias** [comment]
I didn't even get a UAC dialog. Which version were you using before?

**Comment by da2x** [comment]
I just reproduced it on the same system.

1. Download and run the v0.6.0 installer for Windows
2. Select install for all users during the installation
3. Choose to Run IPFS at the end of the installer
4. Wait until you get an update notification
5. Open C:\Program Files\IPFS Desktop in File Explorer
6. Quit IPFS Desktop
7. Click Okay on the UAC prompt
8. Watch as every file in C:\Program Files\IPFS Desktop is deleted

I've done this a couple of times now. Every time all files are deleted. I don't know why only some of the files were deleted the first time this happen.

**Comment by hacdias** [comment]
@da2x thanks for the report. Could you also try with the single user installation, please?

**Comment by hacdias** [comment]
This issue on Windows won't happen again. I've also removed the system wide installation from the options and it will only be user specific. I've tested on 3 different machines from 3 different people and auto-update is working well. Closing this. If any other issue appears, please let us know ;)
