### ISSUE TITLE
Can't preview PDFs

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#785]
It seems that we can't preview PDFs inside Web UI on IPFS Desktop.

1. I tried activating the [plugins option](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions) on Browser Window. That would also require changing `object` to `embed` on the PDF. I changed to `embed` and all I got was 'Couldn't load the plugin'.
2. Also tried `https://github.com/gerhardberger/electron-pdf-window` but it seems that it is used so a Window can load a PDF URL and not to embed PDFs.

Needs more research.

**Comment by lidel** [comment]
We probably should avoid running plugins for security reasons.
Instead, a safer approach could be https://mozilla.github.io/pdf.js/

**Comment by hacdias** [comment]
@lidel do you think this should go into Web UI or just IPFS Desktop?

**Comment by lidel** [comment]
I believe preview logic should stay in Web UI.
In this case, PDF preview could get smarter: somehow check if there is native/plugin support for PDF in the browser, if not, lazy-load and run pdf.js, so the preview always works.

@olizilla do you feel the same?

**Comment by hacdias** [comment]
I agree with you! Let's wait for Oli's word.

**Comment by hacdias** [comment]
Ping @olizilla

**Comment by olizilla** [comment]
@hacdias can we just use an iframe for pdf previews?

**Comment by hacdias** [comment]
@olizilla yes, but that would need us to rely on Electron's PDF viewer through plugins. It doesn't work though. It's an issue since 3.0.0 that hasn't been fixed yet: https://github.com/electron/electron/issues/12337 😞

**Comment by lidel** [comment]
This got fixed in [v0.13.x](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2) where we switched to Electron 9.x which has a backported fix for https://github.com/electron/electron/issues/12337
