### ISSUE TITLE
Handle ipfs://, ipns:// and dweb: system-wide

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#807]
We have kind of a bit stale issue (#35) about handling `ipfs://` at a system wide level. With the help of Electron Builder ([docs](https://www.electron.build/generated/platformspecificbuildoptions)) we can easily configure one or more schemes to be handled by our program. Ideas ideas!!

- Handle `ipfs://` URLs and show a dialog asking whether to open it in the gateway or explore in IPLD Explorer. Wouldn't a 'Add to my repository' option be interesting too?
Or we could have a way of opening it inside Web UI and then Web UI would have those options (instead of showing a dialog).
- Shall we handle `ipns://` to and redirect to the browser?
- Shall we also support `.ipfs` files that can contain an IPFS path? https://github.com/ipfs-shipyard/ipfs-companion/issues/641

---

- macOS: works.
- Windows: works.
- Linux: ??

/cc @ipfs-shipyard/gui

**Comment by hacdias** [comment]
Sure, let's keep `.ipfs` file support on a different PR! 😄 In the meanwhile, I'll open a PR about the scheme handler.

**Comment by hacdias** [comment]
@ipfs-shipyard/gui working well on Windows. On macOS is working if Desktop is already running. Didn't test on Linux but it is not supposed to work yet.

Ref.: https://github.com/electron-userland/electron-builder/issues/1413

**Comment by hacdias** [comment]
Update: working on macOS.

**Comment by sneak** [comment]
question - if ipfs-desktop is running a local ipfs daemon (with gateway), shouldn't it be rewriting ipfs: and ipns: URLs to localhost:8080/{ipfs,ipns} instead of the public gateway?

**Comment by lidel** [comment]
AFAIK it is by design, to make links always work (even when your local node is shut down).
If you have [ipfs-companion](https://github.com/ipfs/ipfs-companion/) browser extension it will redirect to your local node and public gateway won't get hit.

**Comment by hacdias** [comment]
Yeah, we did it that way to make sure they were always available. _But_ we can detect if the daemon is on, and if so, use the local gateway.
