### ISSUE TITLE
Explain how it works?

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/ipfs-desktop#817]
Would be great to have a section on the readme (or elsewhere) that explains some particulars of how this app works. Specifically looking to know:

- where the config of the app is 
  - looks like in OS defaults -- eg inside `~/Library/Application\ Support/IPFS\ Desktop` for macos
- how the app finds the local ipfs repo 
  - looks like the app config file points to default installation spot via a string in the app config (`~/Library/Application\ Support/IPFS\ Desktop/config.json/.ipfsConfig/path` -- LGTM 👍)
- which version of the `ipfs` binary the app uses
  - looks like its own, from within `/Applications/IPFS\ Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs version`
- how the app starts up the `ipfs daemon` (ie, what flags? )
  - looks like w/ the options passed into here: https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/src/utils/daemon.js#L56

All the choices LGTM 👍.

(Ran into these questions trying to figure out why my cli `ipfs`'s node is pointing to a different repo than IPFS Desktop's ipfs node. The `ipfs` in my `$PATH` was using a different repo than the default)

**Comment by hacdias** [comment]
Hey @jbenet! Those are, indeed, good questions. I've just added a [section to the README](https://github.com/ipfs-shipyard/ipfs-desktop#faq) answering those questions 😄
