### ISSUE TITLE
Keep getting IPFS Desktop hash shutdown because of an error lately

### ISSUE THREAD

**Issue by Gozala** [ipfs-shipyard/ipfs-desktop#840]
<img width="705" alt="screen shot 2019-02-22 at 10 03 31 am" src="https://user-images.githubusercontent.com/21236/53261652-684ff200-3689-11e9-998b-14e00b891d1d.png">

Not sure what exactly causes the crash, but I'm under impression that it usually happens in coffeeshops with spotty wifi.

**Comment by Gozala** [comment]
I'm on Revision fc83788.

**Comment by Gozala** [comment]
Is there some error log I can look into /  paste here ?

**Comment by hacdias** [comment]
Hey @Gozala! Probably you've version 0.6.0 which has some bugs when the internet connection is unstable. Please try installing the newest version:

https://github.com/ipfs-shipyard/ipfs-desktop/releases

Also, when you click 'Report the error to the developers', it will open a tab on your browser with a pre-filled issue with the information of the error and the version of IPFS Desktop you're running.

**Comment by Gozala** [comment]
I did update after reporting and so far no crashes, I’ll assume it was fixed and will report new issue if it occurs again.

> Also, when you click 'Report the error to the developers', it will open a tab on your browser with a pre-filled issue with the information of the error and the version of IPFS Desktop you're running.

I tried that but it was actually opening Electron window with github in it with no details & I didn’t wanted to login there, maybe that is also artifact of that version. I’ll verify when I’m by computer

**Comment by Jan877** [comment]
[error.log](https://github.com/ipfs/ipfs-desktop/files/10529196/error.log)
Here is the error log. I cannot open/use IPFS

**Comment by Jan877** [comment]
[error.log](https://github.com/ipfs/ipfs-desktop/files/10529197/error.log)
