### ISSUE TITLE
IPFS_PATH not used on macOS

### ISSUE THREAD

**Issue by hoogw** [ipfs-shipyard/ipfs-desktop#843]
Mac, latest 0.4.18, 
terminal run 'env', confirm that IPFS_PATH=/Volumes/d/ipfs_repo 

However, when start ipfs-desktop
it supposed to use env IPFS_PATH=/Volumes/d/ipfs_repo ,
but it did not. It init a new default  $user/.ipfs repos. 

I delete default  $user/.ipfs repos , try again, still not pick up the customized IPFS_PATH=/Volumes/d/ipfs_repo 

I tried on windows, same issue. 
It would NOT pick up the customized IPFS_PATH=/Volumes/d/ipfs_repo

**Comment by hoogw** [comment]
I try run
     ipfs daemon
It correctly pick up the IPFS_PATH=/Volumes/d/ipfs_repo 

But ipfs desktop failed to do so.

use 
      ipfs repo 

list all help

     ipfs repo fsck ( will remove the repo.lock file)

make sure the your ipfs_repo directory does not have a repo.lock file. 
If it exist, use ipfs repo fsck to remove it. 

now you are ready to run  ipfs daemon, it will use your IPFS_PATH=/Volumes/d/ipfs_repo
but when I use ipfs desktop, it still use default user/.ipfs.

This is the bug, should be fixed easily.

**Comment by hoogw** [comment]
I can manually update config.json file, let it point to customized ipfs repo directory.
It works fine.

On windows, 
                    C:\Users\your-user-name-here\AppData\Roaming\IPFS Desktop

open config.json

              update the path

"ipfsConfig": {
		"type": "go",
		"path": "D:\\ipfs_repo",
		"flags": [
			"--migrate=true",
			"--routing=dhtclient"
		],
		"keysize": 2048
	},

**Comment by hoogw** [comment]
On Mac:

manually change ipfs_path repo,

(library is hidden directory, cmd+shift+. to show hidden)

$user/Library/Application Support/IPFS Desktop

Edit config.json



"path": "/Volumes/ipfs1/ipfs_repo",

Unfortunately, when I re-start ipfs-desktop, it auto over-write above change, to default
"path": "/Users/you/.ipfs",

This is a bug, need to fix, should be easy, because windows version of ipfs-desktop do not have this issue, 
on windows, manually update config.json,  it will correctly pick up new path. 

But on Mac, re-open ipfs-desktop, it just over-write the change, annoying, 
I have to use cmd "ipfs daemon", not use ipfs-desktop for now.

**Comment by hoogw** [comment]
version 0.7 rc Mac did not fix this bug, 
Windows version does not have this bug.

**Comment by hacdias** [comment]
@hoogw what I understood from what you said is that IFPS_PATH environment variable is being ignored on macOS. Just a few points to clarify:

- IPFS_PATH is only used the first time IPFS Desktop runs. After that, its configuration is its source of truth.
- We're using [`ipfsd-ctl`](https://github.com/ipfs/js-ipfsd-ctl) which takes care of that. Also, we have tests for custom IPFS_PATH and they're passing on macOS.

How're you running IPFS Desktop? From the command line? Executing the binary?

I'm not sure how environment variables work on macOS: does a var set in the CLI persist to an external program that executes outside of it? /cc @olizilla

**Comment by hoogw** [comment]
Good news, you fixed the problem on newest release. v0.7.0-rc.5. 


Here is how to do notes:

If you want ipfs-desktop use new ipfs_repo, you have to do following





...............

Windows:



ipfs repo

          will list all help



ipfs repo stat

       

           will list current repo path ( which read from IPFS_PATH=D:/ipfs_repo environment variable)

            default is (c:/users/you/.ipfs)







Before you run ipfs daemon or ipfs desktop, you need to set ipfs repo(block, datastore etc)

run

ipfs init

           will use your current ipfs_path as repo location.





Now you are ready to run ipfs daemon,



 Because of bug of ipfs desktop, you need to manually config new repo_path, othewise, it always use default \.ipfs





I can manually update config.json file, let it point to customized ipfs repo directory.

It works fine.



On windows,

C:\Users\your-user-name-here\AppData\Roaming\IPFS Desktop



open config.json



```

          update the path

```

"ipfsConfig": {

"type": "go",

"path": "D:\ipfs_repo",

"flags": [

"--migrate=true",

"--routing=dhtclient"

],

"keysize": 2048

},









On Mac:



(library is hidden directory, cmd+shift+. to show hidden)



$your-user-home/Library/Application Support/IPFS Desktop



Edit config.json



"path": "/Volumes/ipfs-1tb/ipfs_repo",
