### ISSUE TITLE
Update on macOS needs to be manually restarted

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#851]
On macOS, after clicking on the notification about the available update, it doesn't seem to shut down IPFS Desktop to proceed with the installation. It currently requires the user to manually shut down IPFS Desktop so it updates.

Some reference issues that might help:

- https://github.com/electron-userland/electron-builder/issues/1604
- https://github.com/electron/electron/issues/3583

**Comment by olizilla** [comment]
@hacdias did you look in to the fix suggested here https://github.com/electron-userland/electron-builder/issues/1604#issuecomment-306709572
