### ISSUE TITLE
Visualise the status of the ipfs daemon and be robust to it not stopping.

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#857]
If you leave the IPFS daemon running for a long time, trying to stop it can take a long time. The user has no clue what is going on, so it just seems like the app is stalled... I took a screen recording of a particularly suprising session, that stalled, then crashed, then installed an update

https://ipfs.io/ipfs/QmWEDikLypHaWYNJC3ftmGNkuZCogeSoMSnwAp7UaLyCdz/ipfs-desktop-no-node-status.mp4

The app should not crash if the daemon takes a long time to stop. We may have to consider killing the process or offering the user a way to do it, if it does take a really long time. Command line users are just another ctrl+c away from killing it.

We could indicate the current status of the daemon by adding a label to the "Status" entry on the menubar with labels for ["stopped", "starting...", "connected", "stopping..."] or similar. I've used "connected" for the all ok label, as that mirrors the language in the web ui.

We would be good if the power button visually indicated if the "power" was on or not, as companion does. It may make more sense as a slider toggle switch, as per https://github.com/ipfs-shipyard/ipfs-companion/issues/689#issuecomment-469496633

**Comment by hacdias** [comment]
![image](https://user-images.githubusercontent.com/5447088/54198811-5068d280-44bf-11e9-80cd-d78bdcf72db9.png)

I personally like the idea of keeping the power button and add a circle on its right telling the current state,

**Comment by hacdias** [comment]
![image](https://user-images.githubusercontent.com/5447088/54199069-ea307f80-44bf-11e9-8175-3c2c60e9c358.png)


![image](https://user-images.githubusercontent.com/5447088/54199117-06342100-44c0-11e9-836b-bdab6178d8d7.png)

![image](https://user-images.githubusercontent.com/5447088/54199151-1946f100-44c0-11e9-9fee-cffb5dec5eac.png)

**Comment by olizilla** [comment]
For the status, I'd go for a label + colored circle. We can add it to the status section in the menu. We can't rely on just a color change to communicate state to the user as many folks have some form of color blindness.

This is what docker does
<img width="316" alt="Screenshot 2019-03-12 at 12 08 57" src="https://user-images.githubusercontent.com/58871/54199101-f74d6e80-44bf-11e9-8dbc-bcbcb2e94b6a.png">

A toggle would work for the start/stop button, tho the power button does match the one in companion right now. The smallest change is that it should give the user some feedback that it was clicked. The one in companion turns gray when the intergration is switched off.

**Comment by fsdiogo** [comment]
@hacdias I'm also up for keeping the power button instead of a toggle.

This can be tricky as it may confuse users and seem like a button too:

<img width="574" alt="stat" src="https://user-images.githubusercontent.com/33324750/54207890-e9551900-44d2-11e9-8e0e-ceed2084081d.png">
