### ISSUE TITLE
On Manjaro Gnome Linux no desktop integration

### ISSUE THREAD

**Issue by tiotrom** [ipfs-shipyard/ipfs-desktop#859]
As said above. Installed properly. Works properly, but I do not see how to start it unless I "npm start" from the ipfs-desktop folder. Cheers!

**Comment by tiotrom** [comment]
Ok, using appimage is better. Cheers!

**Comment by hacdias** [comment]
@tiotrom which package did you install before?

**Comment by tiotrom** [comment]
I installed it via:
```

git clone https://github.com/ipfs-shipyard/ipfs-desktop.git
cd ipfs-desktop
npm install
npm start
```
By the way it could help if on Linux you would create a .desktop file that goes into .local/share/applications - else the appimage does not integrate with the system. I know this is experimental for Linux. I hope you'll focus more and more on Linux :)

**Comment by hacdias** [comment]
Close in favour of #1153.
