### ISSUE TITLE
Faster Protocol Handler

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#862]
So, we already have a protocol handler for ipfs, ipns and dweb protocols. Although I'd like to suggest something else.

- Right now, every time we open a link on those protocols, we call an electron app so it can just tell the OS to open a browser link. Not worth it. Too many resources. Slow.
- Faster idea? Create a static binary. In Go perhaps to do this.
- Would work on Windows since we can tell directly which binary to handle the protocols.
- On macOS? No clue. Perhaps we'd need to create a separate app and install it with Desktop and leave it always running so we wouldn't need to have IPFS Desktop running to handle the links. It would be harder for us than to the end user. But if we got a better UX, I think it'd be worth it.

**Comment by lidel** [comment]
Somehow related: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1646

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1646
