### ISSUE TITLE
Upgrade to go-ipfs 0.4.19

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#864]
Folks want the latest shiny. See https://github.com/ipfs-shipyard/ipfs-webui/issues/988

We need to unblock the [0.7 release](https://github.com/ipfs-shipyard/ipfs-desktop/issues/788) so we can get it to them!

**Comment by hacdias** [comment]
@olizilla only @daviddias has permission to update npm-go-ipfs-dep. We have pinged him some days ago on https://github.com/ipfs/npm-go-ipfs-dep/pull/30#issuecomment-469737899. We're just waiting for feedback.

**Comment by daviddias** [comment]
Not anymore :) 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/1211152/54284267-ed9b3800-459f-11e9-84dd-e5db1d593984.png">

@achingbrain @olizilla and @alanshaw should be able to do it too

**Comment by olizilla** [comment]
Thanks @daviddias. I shall commence the publishing ritual.

**Comment by hacdias** [comment]
Niiiice. Thanks @daviddias!!

**Comment by alanshaw** [comment]
`go-ipfs-dep@0.4.19` it is released!
