### ISSUE TITLE
Move to menubar menu only

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#865]
Most menubar apps have the same behaviour when using the right or left click and right now we have different actions for both. On left click, we open the real React menubar and with the right click we option a native menu with some options.

Since this goes against what most do, probably people would get confused and we thought about moving it only to a menubar menu app. With this we could simplify the user experience (on all OSes) and reduce lots of dependencies we need right now.

/cc @ipfs-shipyard/gui

**Comment by fsdiogo** [comment]
On macOS it's not rare a menubar app having different actions for click, although I can agree that most users may be unaware of that capability.

Would the right click actions be aggregated somehow in the menubar?

**Comment by lidel** [comment]
As a minimalist, I'm for making it a simple menu that looks native to the OS, but it is a big change.

@hacdias @fsdiogo are you able to add screenshots of the native menu under Windows/Mac? 
I believe seeing it will make it easier for others to join this discussion.

**Comment by hacdias** [comment]
@fsdiogo no, it would be the opposite way: just have the native menubar. It would be just simpler for everyone.

@lidel here's one on macOS: https://github.com/ipfs-shipyard/ipfs-desktop/issues/857#issuecomment-471975834

**Comment by olizilla** [comment]
Docker for mac is a useful reference point for this (as a fellow OS intergration for a command line tool with a long-running process behind it)

<img width="424" alt="Screenshot 2019-03-12 at 14 40 22" src="https://user-images.githubusercontent.com/58871/54209031-ebb87280-44d4-11e9-8087-62bfd80e2043.png">

**Comment by hacdias** [comment]
Docker on Windows:

![image](https://user-images.githubusercontent.com/5447088/54209190-3cc86680-44d5-11e9-97fe-39dda5cbc652.png)

**Comment by olizilla** [comment]
In conversation with @ericronne it came up that the menubar UI was mostly still there becuase this app started life as a menubar app, and then we changed course.

I am in favour of using a system menubar (like the docker example above) for simplicity, and to make it feel more like a native app, and to remove the left/right click distinction, where left clicks gets you a fancy menu, and right click gets you a system menu with different options

**Current right click menu in IPFS Desktop**

<img width="237" alt="Screenshot 2019-03-12 at 14 44 41" src="https://user-images.githubusercontent.com/58871/54209395-9c267680-44d5-11e9-9acf-74371be23c7a.png">

**Comment by hacdias** [comment]
A possible idea of what it could be (options would need to be tweaked):

![image](https://user-images.githubusercontent.com/5447088/54209916-7e0d4600-44d6-11e9-8518-ef483d856124.png)

We could mimic the status in the top as Docker Desktop do. We could perhaps hide the versions on a sub menu or About dialog.

And perhaps hiding "Configuration folder", "logs directory" and eventually "IPFS repository" under advanced sub menu.

**Comment by fsdiogo** [comment]
> @fsdiogo no, it would be the opposite way: just have the native menubar. It would be just simpler for everyone.

Oh ok, wasn't expecting that to be honest 😮

Well, it kind of makes sense as right now we don't get that much with the menu bar app, being Web UI the central point of it, so I think it's ok just having a native menu. I'm up for it 👍

**Comment by hacdias** [comment]
@fsdiogo yeah, it might be a little sad (and I trully feel it since I've been working on this for a long time haha), but it just gets a better native feeling and simplifies everything

**Comment by ericronne** [comment]
I'd add my vote in favor of "killing our darlings" in this case, and removing the custom menu …
![image](https://user-images.githubusercontent.com/9259185/54228688-adb94f80-44d0-11e9-89c6-fdee56b12cc1.png)
… in favor a native-os one.

The current behavior seems a little unorthodox, since the five primary menu options (Status, Files, Explore, &c) merely open the desktop app, with the chosen section active. I don't think it users would mind if we merely offered an "Open IPFS Desktop" option instead.

I'm unclear about some of the other functionality at this point, but it might be good to avoid duplicating options which are available in the desktop app, unless they are things a user would want to fiddle with frequently.

**Comment by hacdias** [comment]
![image](https://user-images.githubusercontent.com/5447088/54232122-ddcd1680-4501-11e9-9125-06b53b2dbeac.png)

This is what I've been working for the last hour. Just to try it out. It would work. We'd still use Electron. It looks more native on macOS than on Windows because Chromium never used Windows' native context menu. But I don't believe that'd be an issue. Yes, the color icon is not aligned/with the correct size.

I wonder if in the future we could ditch Electron and find a way to create a menubar without the heavy baggage that Electron is.

What do you think about this?

**Comment by ericronne** [comment]
I'd suggest collapsing "Status / Files / Explore / Peers" into "Open IPFS Desktop" or something similar. Does this work for you?

![image](https://user-images.githubusercontent.com/9259185/54233734-8f0c8600-44db-11e9-9155-22d09e6e9c27.png)

**Comment by hacdias** [comment]
@ericronne or "Open Web UI". But that'd be better to check with everyone 😄This is just an experiment, although it seems to be working well.

**Comment by ericronne** [comment]
Ah, taxononmy! (shakes fist)
