### ISSUE TITLE
Font weights are thinner in electron than chrome on macos

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#869]
I think this is https://github.com/electron/electron/pull/15007 but seems the fix hasn't landed yet, or needs chrome >= 70

perhaps electron@5 will fix it.

**Comment by olizilla** [comment]
@hacdias did this get fixed?

**Comment by hacdias** [comment]
It seems the linked PR was merged and released in the meanwhile
