### ISSUE TITLE
Failed to add files to IPFS. Please try again. [0.7.1]

### ISSUE THREAD

**Issue by DavidBurela** [ipfs-shipyard/ipfs-desktop#881]
Under 0.6.1 I was able to add files.
I upgraded to 0.7.0 this week, I can still see my previous files that were pinned, but I'm unable to add new files or folders as it simply gives the error message:
`Failed to add files to IPFS. Please try again.`

If I add from IPFS then it works fine.
I upgraded to 0.7.1 and it has the same error.
The `error.log` file is empty, so there are no logs I can attach.

I did some research and it seems there was an issue, but it was fixed 2 months ago in the IPFS-webUI.
https://github.com/ipfs-shipyard/ipfs-webui/issues/928

**Comment by hacdias** [comment]
Hey @DavidBurela! Sorry for this. Just to make sure I understood correctly: the error is through the Web UI window right? Or is it through any other integration?

**Comment by DavidBurela** [comment]
It is in the Web UI.
If I drag a file in, or I use the buttons to click "add file" or "add desktop", then it fails.
If I use the button to "add from IPFS" then it succeeds.

**Comment by olizilla** [comment]
thanks for reporting it @DavidBurela, I've fixed the issue in ifps-webui and opened a PR to update ipfs-desktop to the new release in #883

**Comment by olizilla** [comment]
see: https://github.com/ipfs-shipyard/ipfs-webui/pull/995 for details

**Comment by hacdias** [comment]
@DavidBurela 0.7.2 just release with a fix for that: https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.7.2

😃

**Comment by DavidBurela** [comment]
Thanks.
I can confirm now that clicking "add file" now works.

However clicking "add folder" seems to add an empty folder. I have created a new bug with screencapture to track it
https://github.com/ipfs-shipyard/ipfs-desktop/issues/884
