### ISSUE TITLE
Using "add folder" does not add a folder correctly [0.7.2]

### ISSUE THREAD

**Issue by DavidBurela** [ipfs-shipyard/ipfs-desktop#884]
- **OS**: win32
- **IPFS Desktop Version**: 0.7.2
- **Electron Version**: 4.0.8
- **Chrome Version**: 69.0.3497.128

Dragging a folder into the web ui, will add it correctly.
But clicking "add folder" seems to add an empty folder, that if you try to navigate into will result in it just continuously trying to load.

I have included a screencapture gif to show the bug.

![BF29E87D-D9A4-4005-914E-DF3BEEA09E28](https://user-images.githubusercontent.com/1320729/54661246-8811f300-4b2d-11e9-9fcf-296408e27c82.GIF)

**Comment by hacdias** [comment]
Hey again @DavidBurela! Once again, sorry. Yes, I can reproduce this 😞For me I get a "Failed to add to IPFS". I don't even get an empty folder. @olizilla @fsdiogo could you take a look at this one, please?

**Comment by olizilla** [comment]
interesting! I can't recreate this in Chrome 72 or Firefox 65, but I can on the 0.7.2 desktop release.

In chrome 72 via webui the same action leads to an add request with

```
----------------------------872277512022848910475489
Content-Disposition: file; filename="foox%2FUntitled.txt"
Content-Type: application/octet-stream

hello world
----------------------------872277512022848910475489--
```

and we get the response

```js
{"Name":"foox/Untitled.txt","Bytes":11}
{"Name":"foox/Untitled.txt","Hash":"Qmf412jQZiuVUtdgnB36FXFX7xg5V6KEbSJ4dpQuhkLyfD","Size":"19"}
{"Name":"foox","Hash":"QmbdfJiE1XZRJVmxQAvArWpDz89jno5cRKpZGpQqFJvMiz","Size":"77"}
```

When we add a folder called `foox` in ipfs-desktop via the folder input, we're sending

```
----------------------------323655909678229599284643
Content-Disposition: file; filename="Desktop%2Ffoox"
Content-Type: application/octet-stream


----------------------------323655909678229599284643--
```
and we get the response

```js
{"Name":"Desktop/foox"}
{"Name":"Desktop/foox","Hash":"QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH","Size":"6"}
{"Name":"Desktop","Hash":"QmaVFREPrsbhyjViXGo8DkKSHSG2go1Dpxhpob5aPBFfrp","Size":"56"}
```

so it looks like the version of chromium in desktop has a different opinion about how the file path info for folders added via file input elements should be provided, which is another fun edge-case for that logic to deal with.

**Comment by olizilla** [comment]
@hacdias can you take a look at this?

**Comment by hacdias** [comment]
Note to self: https://github.com/electron/electron/issues/839
