### ISSUE TITLE
Resizing the window causes a crash [0.7.2]

### ISSUE THREAD

**Issue by DavidBurela** [ipfs-shipyard/ipfs-desktop#885]
With the Web UI, if you resize the screen at all, it will crash.
Includes maximising or draging a window edge to resize.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.7.2
- **Electron Version**: 4.0.8
- **Chrome Version**: 69.0.3497.128

**Error**

```
Error: EBADF: bad file descriptor, close
    at Object.closeSync (fs.js:401:3)
    at Object.closeSync (C:\Users\xxx\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:52:27)
    at Function.writeFileSync [as sync] (C:\Users\xxx\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\write-file-atomic\index.js:228:16)
    at ElectronStore.set store [as store] (C:\Users\xxx\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\conf\index.js:168:19)
    at ElectronStore.set (C:\Users\xxx\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\conf\index.js:82:14)
    at BrowserWindow.<anonymous> (C:\Users\xxx\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\late\webui\index.js:54:18)
    at BrowserWindow.emit (events.js:182:13)
```

**Comment by hacdias** [comment]
@DavidBurela I can't reproduce this one. Neither on a Mac, nor on Windows. Honestly EBADF seems like a file error that could happen anything for some sort of problem on the OS and that might not be related to IPFS Desktop.

Can you still reproduce it after closing and re-opening IPFS Desktop? If not, try going to (on IPFS Desktop): Advanced -> Open Configuration File. Did your editor open it correctly? If not, try to delete that file (it might be corrupted). Otherwise, make sure it looks like this:

```
{
	"ipfsConfig": {
		"type": "go",
		"path": "/Users/xxxxx/.ipfs",
		"flags": [
			"--migrate=true",
			"--routing=dhtclient",
			"--enable-gc=true"
		],
		"keysize": 2048
	},
	"version": 5,
	"language": "en",
	"window": {
		"width": 612,
		"height": 746
	},
	"downloadHashShortcut": true,
	"screenshotShortcut": true
}
```

If so, try restarting your computer. But hopefully just re-restarting IPFS Desktop should work.

**Comment by DavidBurela** [comment]
Very strange.
It was a fresh install (as I had been wiping everything from the .ipfs folder during installs to try and resolve the other bugs).
Restarting IPFS didn't resolve as it would still crash on every window resize.

But restarting the computer resolved it.
Maybe a file got a weird lock on it during the install, which got resolved after the restart.  Closing the issue.

**Comment by DavidBurela** [comment]
Reopening this bug.
It seems that after leaving it running for a while, the same issue has come back.  IPFS now instantly crashes if I resize the window.

I'm able to use all functions inside of IPFS web ui. adding files, exploring, viewing the config file, editing the config file. It all works. But as soon as I resize, it crashes with no error logs on disk.

**Comment by hacdias** [comment]
@DavidBurela how many time would you estimate to be needed to replicate the issue? I've been running it for a few hours and I can still open Web UI and resize without issues

**Comment by olizilla** [comment]
Thanks for digging into this @DavidBurela, and all your reports! Could you give us more info about your set up? What version of windows are you on? If you're ok with it, you could enable error reporting analytics from the settings page (its an advanced option, hidden by default behind the configure... details element), in case the error info manages to get before it dies, though I suspect it wont.

@hacdias I can't think of any of our code that is run on a window resize event, but it'd be worth  double checking that

**Comment by hacdias** [comment]
@olizilla it's to save the dimensions to the configuration file. That's what's causing ' bad file descriptor'. I just don't understand how the file descriptor gets 'bad' during execution unless something the OS is doing is wrong.

**Comment by DavidBurela** [comment]
Latest version of Windows 10 (1809).
I have now enabled the advanced error reporting and triggered the resize crash a number of times. Hopefully some of them go through.

The error.log file is now showing errors, but nothing too helpful
`2019-03-22T01:55:22.102Z error: EBADF: bad file descriptor, close`

**Comment by DavidBurela** [comment]
I haven't found any concreate ways to repo the bug.

The closest I've found is that if I leave it running in my system tray, then I go away for a few hours and my laptop goes to sleep. When I resume my laptop, if I open IPFS desktop and then try to resize, it will crash.  But doesn't happen every time.

**Comment by hacdias** [comment]
@DavidBurela please try the following: start IPFS Desktop; put laptop to sleep; open it again and see if the error occurs. 

> But doesn't happen every time.

Hmm... that is even weirder. I also used a Windows 10 computer with the same version to try this out.

**Comment by DavidBurela** [comment]
I've been trying to repo it, but it has been rock solid and won't doesn't crash.
Lets put it down to some temporary oddity and hope it doesn't come back.

**Comment by olizilla** [comment]
Thanks for keeping an eye on it @DavidBurela
