### ISSUE TITLE
Remove "Restart" option from menu when app isn't running

### ISSUE THREAD

**Issue by ericronne** [ipfs-shipyard/ipfs-desktop#887]
I believe that the restart option is superfluous when the app isn't running. Start suffices, right? 

![image](https://user-images.githubusercontent.com/9259185/54908799-97ec5700-4ee0-11e9-94e8-3f1ec5d0f78e.png)

**Comment by hacdias** [comment]
Yup, you're right @ericronne! Thanks for noticing that 😄
