### ISSUE TITLE
2019-04-01T09:46:39.098Z error: Error: 36:68: execution error: “System Events”遇到一个错误：不能获得“login item "IPFS Desktop"”。 (-1728)

### ISSUE THREAD

**Issue by poseidonplan** [ipfs-shipyard/ipfs-desktop#892]
2019-04-01T09:46:39.098Z error: Error: 36:68: execution error: “System Events”遇到一个错误：不能获得“login item "IPFS Desktop"”。 (-1728)

macOS report this error. and can't use ipfs in the cmd.

**Comment by hacdias** [comment]
@poseidonplan please ignore the error.

IPFS will be available on cmd on the next version ;)
