### ISSUE TITLE
IPS desktop died

### ISSUE THREAD

**Issue by tjayrush** [ipfs-shipyard/ipfs-desktop#895]
Please describe what you were doing when this error happened.
I started IPFS desktop more than a week ago, and then literally forgot it was running. Appearently, it runs in the background or as a tray icon. Last night it crashed. No idea why, but I did notice for the first time in X weeks that my Mac tried to 'auto-upgrade' the OS (it failed because other programs were running). Maybe that's related.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.6.0
- **Electron Version**: 3.0.13
- **Chrome Version**: 66.0.3359.181

**Error**

```
Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

**Comment by hacdias** [comment]
@tjayrush hello! Sorry for that. That issue was fixed already. Please upgrade to v0.7.2: https://github.com/ipfs-shipyard/ipfs-desktop/releases 😃

**Comment by tjayrush** [comment]
Thanks.
