### ISSUE TITLE
How to "pin" in current version?

### ISSUE THREAD

**Issue by henrypijames** [ipfs-shipyard/ipfs-desktop#922]
I am aware a UX overhaul is underway to update the pinning/seeding feature. But in the mean time, for the current version (0.7.2), I can't find how to pin/seed someone else's file/site.

**Comment by hacdias** [comment]
Hey @henrypijames! Currently, there's no way through the GUI to add pins unfortunately. We're on talking on Web UI (https://github.com/ipfs-shipyard/ipfs-webui/issues/1025) to bring the pins to the Files page so you have easy access to them in the future.

**Comment by hacdias** [comment]
Will close this as it will be included in the next version!
