### ISSUE TITLE
Interaction between provided ipfs-go cli and desktop ui ?

### ISSUE THREAD

**Issue by jonmaim** [ipfs-shipyard/ipfs-desktop#929]
On MacOs, the `ipfs-go` is present here: `/Applications/IPFS\ Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs`

Is it possible to add files with the provided `ipfs-go` cli and see changes in desktop ui ?

**Comment by olizilla** [comment]
In the next release of ipfs-desktop, it will add the `ipfs` to your PATH, so that you can do exactly that. The desktop app will also be able to keep the command line tool up to date for you.

https://github.com/ipfs-shipyard/ipfs-desktop/issues/880
