### ISSUE TITLE
Dont show a dialog box to ask if the user wants replace the ipfs command

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#933]
It would be jarring to see a dialog box when ipfs-deskopt auto-updates. We are working on a experiements UI for the settings page which we could add a "let desktop manage the `ipfs` command`.

First step is to disarm the dialog box. While in there, please ensure that we gracefully handle a situation where the user doesn't have polkit available on linux... we should just skip trying to check for `ipfs` if we can't.

**Comment by olizilla** [comment]
Dialog boxes are for terrible failure cases where we haven't had the time to come up with something better. Imagine you are getting some work done, and desktop auto-updates, and then BONG a dialog box, unbidden, appears and steals focus.

**Comment by hacdias** [comment]
Just some notes:

> It would be jarring to see a dialog box when ipfs-deskopt auto-updates.

Our auto-update always requires manual action to be triggered. Also, the dialog is shown once, not every update.

> We are working on a experiements UI for the settings page which we could add a "let desktop manage the ipfs command`.

Nice, we already have that. But it's nice to have a better documented section.

> While in there, please ensure that we gracefully handle a situation where the user doesn't have polkit available on linux... we should just skip trying to check for ipfs if we can't.

We only show the dialog about polkit if the user tells IPFS Desktop explicitly to add IPFS to the PATH and it doesn't have polkit.
