### ISSUE TITLE
Making a private network using ipfs desktop, it doesn't have a swarm.key right ?

### ISSUE THREAD

**Issue by AkshitV** [ipfs-shipyard/ipfs-desktop#950]
Ipfs desktop runs without swarm key right ?
i could check that in config, under Identity it also has PrivKey, whats this for and why do i not have this, when i make a private network right ?
is think this is used to find the location of files right ? correct me if i am wrong ,
why does a private network not have this ?
does this mean that a private network is working without a priv key of every peer?
this would impact security of the private network right ?

**Comment by hacdias** [comment]
@AkshitV by default, IPFS Desktop just runs a regular installation of `go-ipfs` with some flags for optimization for a regular user.

To create a private network using IPFS Desktop, you need to do the same as you would need to in any other IPFS installation. I will leave some links here that may be help you better than I do:

- Documentation for [Private Networks](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks)
- A [tutorial](https://mrh.io/ipfs-private-networks/) explaining how to create a private network

Please let me know if you need further help. These kind of questions would perhaps get more replies on our forum: [discuss.ipfs.io](https://discuss.ipfs.io/).

**Comment by stanlypalathingal** [comment]
Hi ihave my ipfs private network running. but cannot start the ipfs-desktop. 

![Screenshot from 2022-10-06 13-05-49](https://user-images.githubusercontent.com/57093376/194308323-768b348a-804c-44d2-841a-7709dfddeaea.png)
