### ISSUE TITLE
Crashed while idle on another desktop

### ISSUE THREAD

**Issue by gcavalcantes** [ipfs-shipyard/ipfs-desktop#954]
Launched IPFS desktop for the first time and it opened normally. I moved the IPFS Desktop window to another desktop after pressing **WIN + TAB**. It crashed while idle after about 60 seconds of me working on another desktop.
My internet speed is really bad at the moment. It might have something to do with this.
Also, the specifications below shows "win32". My Acer Aspire 5 laptop is running Windows 10 64 bits version. Not sure the specifications are accurate.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.7.2
- **Electron Version**: 4.0.8
- **Chrome Version**: 69.0.3497.128

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by hacdias** [comment]
Hey @gcavalcantes! Thanks for the report. I don't think the error is in any way related to the fact you were working on another desktop. This seems an error related to auto update mechanism and some network failure. Although, that was supposed to have been fixed on 0.7.0.

Could you show me `%appdata%/IPFS Desktop/errors.log`?

Also, please update to 0.8.0 https://github.com/ipfs-shipyard/ipfs-desktop/releases 😃

**Comment by gcavalcantes** [comment]
Hi sorry for the delay in response.
I couldn't find any erros.log file. But here's the content from the **error.txt** file:

> 2019-05-21T19:19:20.165Z error: ProcessUncleanExitError: DELETE command exited with code 1:
> 
> ERRO: O sistema n�o p�de localizar a chave do Registro ou valor especificado.
>     at mkErrorMsg (C:\Users\sckar\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\winreg\lib\registry.js:111:12)
>     at ChildProcess.<anonymous> (C:\Users\sckar\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\winreg\lib\registry.js:771:10)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 2019-06-07T23:06:20.766Z error: ProcessUncleanExitError: DELETE command exited with code 1:
> 
> ERRO: O sistema n�o p�de localizar a chave do Registro ou valor especificado.
>     at mkErrorMsg (C:\Users\sckar\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\winreg\lib\registry.js:111:12)
>     at ChildProcess.<anonymous> (C:\Users\sckar\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\winreg\lib\registry.js:771:10)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 2019-06-07T23:12:10.584Z error: net::ERR_CONNECTION_RESET
> 2019-06-08T01:52:39.606Z error: ProcessUncleanExitError: DELETE command exited with code 1:
> 
> ERRO: O sistema n�o p�de localizar a chave do Registro ou valor especificado.
>     at mkErrorMsg (C:\Users\sckar\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\winreg\lib\registry.js:111:12)
>     at ChildProcess.<anonymous> (C:\Users\sckar\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\winreg\lib\registry.js:771:10)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by hacdias** [comment]
Weird, the file should be `error.log` and not `.txt`. Also, the error described on the logs (could not find a registry value) doesn't even seem related to networking... Could you try updating to the latest version (0.8.0) and leave it running some days and see if we can reproduce this?

**Comment by gcavalcantes** [comment]
Hi. I upgrade to version 0.8.0 and ran it for a few days. Everything is running fine and I could not reproduce the error.

**Comment by hacdias** [comment]
I'm closing this for now. If you ever get any other error, please lemme know!
