### ISSUE TITLE
Unable access files

### ISSUE THREAD

**Issue by miguelito9** [ipfs-shipyard/ipfs-desktop#955]
I've installed latest ipfs desktop (go-ipfs v0.4.21) on Win7 XP with an external drive as described in last entry at 
https://discuss.ipfs.io/t/how-to-setup-ipfs-desktop-with-repository-in-external-hd/5490/2 
I’m running a VPN exiting Iceland with the IPFS Desktop behind a router. Others are having trouble accessing my files. For example the file https://ipfs.io/ipfs/QmdMkoevxiyexeM21jAgKDrjrZ6G8DqvYpUBs6s3nVNeab
doesn’t seem to be accessible from any browser or PC. Have tried Brave with IPSF Companion disabled and Chrome without Companion installed. Tried Firefox browser on another PC without companion. With repository and PC at another location behind different router tried without VPN and no success. Desktop seems to be working OK with varying large numbers of peers discovered and some incoming/outgoing activity. There have been no antivirus flags. 

Am I missing something important in the setup? Should it work through a VPN? behind a router? Without a static IP? On an external/USB HD?

**Comment by hacdias** [comment]
Hey @miguelito9, thanks for the report. Unfortunately, it doesn't seem to be your fault. @olizilla and I have also been having some issues with that.

It seems there is an issue already open on `go-ipfs` repository (https://github.com/ipfs/go-ipfs/issues/6385). I'll wait for feedback.

**Comment by hacdias** [comment]
I'm closing this as this is not directly related to IPFS Desktop and the issue was mitigated in the recent versions of the gateway
