### ISSUE TITLE
Tray Icon - Colors, more info?

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#956]
Right now, IPFS Desktop tray icon is coloured. That goes against some guidelines and "what we usually" see on macOS. If we notice, when using the dark theme, we get white icons, and when using the light theme, we get dark/coloured icons.

The same applies for the most recent version of Windows 10, where there are effectively two themes (light and dark). System icons honour that, although since it is a really recent thing, most apps don't.

![image](https://user-images.githubusercontent.com/5447088/59181536-7570ee00-8b5f-11e9-8e64-09feb2013850.png)

![image](https://user-images.githubusercontent.com/5447088/59181875-33947780-8b60-11e9-9e60-234cca6dbbd7.png)

I think we could provide a coloured icon and a black and white version. By default, it would honour the system settings (dark or light theme) and we could let the user choose if they want a coloured icon or not in settings (like Mullvald does).

Also, we could expand our icon to show some interesting features. @daviddias has suggested, on https://github.com/ipfs-shipyard/ipfs-webui/pull/1048#issuecomment-500196126, the following:

> The most important question of all (:D), will my little IPFS Cube in my nav bar become the npm on IPFS cube?
> 
> <img width="159" alt="image" src="https://user-images.githubusercontent.com/1211152/59156911-2f565480-8aa3-11e9-9c5a-3ad1bbf09fb8.png">
> 
> <img width="183" alt="image" src="https://user-images.githubusercontent.com/1211152/59156913-35e4cc00-8aa3-11e9-9c60-ab272409eff0.png">
> 
> It would feel it gets equipped with a super power!

Despite our cube only having three faces, surely not most of the experiments/features deserve to be "shown off" on the icon. Some of them could be js-ipfs (#601) and npm-on-ipfs (#911).

/cc @ipfs-shipyard/gui @daviddias

**Comment by lidel** [comment]
The same "dark" and "light" icon variants could be used in [ipfs-companion](https://github.com/ipfs/ipfs-companion/) in Firefox
(it supports [`theme_icons`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action))

**Comment by lidel** [comment]
The same "dark" and "light" icon variants could be reused in [ipfs-companion](https://github.com/ipfs/ipfs-companion/) in Firefox
(it supports [`theme_icons`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action))

**Comment by ericronne** [comment]
+1 to following the apple [guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/) and using a monochromatic "template image" for the menu bar.

**Comment by hacdias** [comment]
@ericronne any suggestion to distinguish between an online and offline node with a monochromatic image?

**Comment by ericronne** [comment]
Taking a 👀now!

**Comment by ericronne** [comment]
Here's a design which better aligns with the rule book, and helps bring desktop more closely into alignment with the browser extension. When running, the framing semicircles break out of their mask and become full circles (ready for connection, symbolically :)

Pls critique!

![image](https://user-images.githubusercontent.com/9259185/61251431-1420d980-a720-11e9-9bad-ff9810e037f5.png)

**Comment by hacdias** [comment]
I like the idea! Ping @olizilla @lidel!

Could you send me the source files so I can try them out? To see how they work out with dark/light themes.

**Comment by ericronne** [comment]
@hacdias do you know the size parameters? In order to make this look the best, i may want to recreate it on a pixel grid. Also what format would you like? thx!

**Comment by hacdias** [comment]
@ericronne:

Please do the following:

- `off-big.png` - 512x512px
- `off.png` - 22x22px
- `off@2x.png` - 44x44px
- `off@2.5x.png` - 66x66px
- `off@3x.png` - 88x88px
- `offTemplate.png` - 22x22px black&alpha channels only
- `offTemplate@2x.png` - 44x44px black&alpha channels only
- `offTemplate@2.5x.png` - 66x66px black&alpha channels only
- `offTemplate@3x.png` - 88x88px black&alpha channels only

And the same for `on` 😃

**Comment by ericronne** [comment]
Is this overlay box created separately, with code?

**Comment by hacdias** [comment]
Yes!

**Comment by ericronne** [comment]
Hm this desktop screen grab measures 30 x 33 …
![image](https://user-images.githubusercontent.com/9259185/61307552-28aeb180-a7b4-11e9-90b3-81388d96aa22.png)

and the chrome extension clocks in at about 28 x 32 …
![image](https://user-images.githubusercontent.com/9259185/61307661-58f65000-a7b4-11e9-86b5-fa0994816167.png)

Does the size include "padding"? The menubar itself seems to be 44 …
![image](https://user-images.githubusercontent.com/9259185/61307861-b1c5e880-a7b4-11e9-950e-4a32ce4bf133.png)

🆘

**Comment by hacdias** [comment]
The sizes I gave you are for IPFS Desktop and they **must** contain padding. Trust me on the sizes! You have an high-dpi screen (2x) that's why you measure 44px and not 22px which is the base 😃

**Comment by hacdias** [comment]
For IPFS Companion I don't know. @lidel must know :)

**Comment by hacdias** [comment]
Also, the template images **must** be only black and alpha channel. The grays must be made of alpha changes in the black color. Just a FYI if you didn't know 😃

**Comment by ericronne** [comment]
How do the `off` images differ from the `offTemplate` ones? All are grayscale/black, right?

**Comment by ericronne** [comment]
Also where are the `big` icons used? 512x512 is a mighty big "icon" 😮

**Comment by hacdias** [comment]
The big ones are for Windows and Linux - you can make them a bit smaller if you want. Anyways if you're using something vectorial, we just need to export to the right sizes. Not really a big deal. 😄

A note about template files: all colours must be a mix of black and opacity! Using grays will only make an opaque image that doesn't work. Just black and alpha. The non-template ones are coulored.

**Comment by hacdias** [comment]
@ericronne if you're using Sketch and if it makes it easier for you, you can just send me the Sketch file with all artboards (on/off black&alpha/coloured) and I can export them to the right sizes.

**Comment by ericronne** [comment]
I think i need to better understand where each of the images will be displayed. My new design is really best suited to very small implementations. Is there a way for me to see where each icon is used, so i can get the proper context? Sorry, i'm guessing that could be a lot of legwork for you. 😬 

And yep, i'm creating vectors in sketch. Black fills, alphas for "gray."

**Comment by hacdias** [comment]
Hey Eric. Despite the big size, it will be displayed on a small taskbar icon too. I know it doesn't need to be that big, but I'll take a look at electron's documentation and provide you with better sizes. But I assure you they will only be shown on taskbar/menubar.

**Comment by hacdias** [comment]
@ericronne so I have been trying and experiment and I've got the right sizes I need! Please let me know if you have any doubts.

### For macOS

On macOS, the icons **must** include padding. The base size is 22x22px which is the size of a 'square' in the menubar. The [current offline icon](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/assets/icons/tray/black.png). So, the files for macOS are:

- `off-22.png` - 22x22px coloured
- `off-22@2x.png` - 44x44px coloured
- `off-22@3x.png` - 88x88px coloured
- `off-22Template.png` - 22x22px black&alpha channels only
- `off-22Template@2x.png` - 44x44px black&alpha channels only
- `off-22Template@3x.png` - 88x88px black&alpha channels only

The same for `on`.

### For Windows

On Windows, on the other hand, the base size is 16x16px and they **must not** contain padding. Of course it can contain some horizontal padding if needed to fit the 16 pixels.

Here I need an `.ico` file with the sizes 16, 20, 24, 32, 48 and 64 pixels. They should be colourful (we're only giving macOS b&w icons right now because Windows doesn't have any guidelines yet).

- `off.ico` - coloured, no padding, sizes 16, 20, 24, 32, 48 and 64px embedded into single file
- `on.ico`  - coloured, no padding, sizes 16, 20, 24, 32, 48 and 64px embedded into single file

If you cannot provide an `.ico` file, please provide the following:

- `off-16.png` - 16x16px coloured
- `off-20.png` - 20x20px coloured
- `off-24.png` - 24x24px coloured
- `off-32.png` - 32x32px coloured
- `off-48.png` - 48x48px coloured
- `off-64.png` - 64x64px coloured

Same for `on`.

### For other OSes

Just provide a `on-64.png` and `off-64.png` colourful 😃

**Comment by ericronne** [comment]
Ok! Here's a [full set](https://drive.google.com/drive/u/0/folders/1rbAGNa6_8ToLo-FkCMYyAYUZL32rUV1S).
- I dumped them onto the google drive, since the names didn't match icons i see on the master branch
- [Sketch file](https://drive.google.com/open?id=1Jm1l0xaP9mtR97X-PaXzGzbYPtZmegRB) is there, too (bc Open Source!)
- I'd love to see know how the colored icons are applied, so that i can ensure proper contrast, etc.
- The 22px icons are pretty fuzzy, would be curious to see those in context as well, at some point
- Thanks for bearing with me, hope this does the job! 🙏 🤞 📿

**Comment by hacdias** [comment]
@ericronne not a major thing, but since I didn't know if I have permission to edit the Sketch file, the coloured ones must not have the 'Template' part on the name:

![image](https://user-images.githubusercontent.com/5447088/61393179-52e99780-a8b8-11e9-8665-c5eb6c46d496.png)

I have made some updates on the sizes here:

https://github.com/ipfs-shipyard/ipfs-desktop/issues/956#issuecomment-512193391

Using your sketch file, I can get all of those, I'll see how they look and update you later.

**Comment by ericronne** [comment]
Removed `Template` from the names of colored-icon artboards. You should be able to edit the sketch file, just lmk if you do, so that i can keep my local file up to date, thx!

[updated sketch file](https://drive.google.com/open?id=1Jm1l0xaP9mtR97X-PaXzGzbYPtZmegRB)

**Comment by lidel** [comment]
@ericronne I really like semicircles as indicator of node being online (ready for connection).
In the browser we need PNG with alpha channel (not every vendor support SVG) in sizes: 16, 24 and 32

Details: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#Choosing_icon_sizes

ps. The badge with a number will probably go away (we will display only the icon).

**Comment by ericronne** [comment]
Picking this up again … here's another approach, where i've tried to solve a couple of issues with the previous design.

This version:
- Uses only black and white, no gray. (Most tray icons seem to go this route.)
- Is more eye catching / harder to miss
- Makes on and off more visually distinct from each other

![image](https://user-images.githubusercontent.com/9259185/61909918-ec3c2d80-aef8-11e9-9573-90192bafe645.png)

please 👍 /  👎 thanks! :)

**Comment by hacdias** [comment]
Love them! I think they'll work really nicely on macOS. Just to remember that we need some coloured form for Windows and Linux.

**Comment by ericronne** [comment]
Yep onnit

**Comment by ericronne** [comment]
**[Updated files!](https://drive.google.com/drive/u/0/folders/1rbAGNa6_8ToLo-FkCMYyAYUZL32rUV1S)** LMK if anything's awry. Would love to see how these look in the various implementations. 🤞

**Comment by hacdias** [comment]
Thanks @ericronne! They look fantastic! Could you just update the icons to this nomenclature, please? https://github.com/ipfs-shipyard/ipfs-desktop/issues/956#issuecomment-512193391

**Comment by ericronne** [comment]
@hacdias i've modified the names of the existing files on the gdrive, but i don't have the bandwidth for additional granular production work. Could we post a help wanted for that, perhaps?

**Comment by hacdias** [comment]
@ericronne don't worry! I can make the missing ones!

**Comment by hacdias** [comment]
So on macOS I think it just looks beautiful 😃 

| | Light | Dark |
| ---|---|---|
| On | <img width="231" alt="Screenshot 2019-07-28 at 23 01 41" src="https://user-images.githubusercontent.com/5447088/62012851-ba8ec500-b18b-11e9-96cb-0c210ee7abba.png">| <img width="211" alt="Screenshot 2019-07-28 at 23 01 34" src="https://user-images.githubusercontent.com/5447088/62012850-ba8ec500-b18b-11e9-88eb-a6b9878c48a9.png">|
| Off | <img width="212" alt="Screenshot 2019-07-28 at 23 01 54" src="https://user-images.githubusercontent.com/5447088/62012853-bb275b80-b18b-11e9-8c99-9303ed506b22.png">|<img width="222" alt="Screenshot 2019-07-28 at 23 01 58" src="https://user-images.githubusercontent.com/5447088/62012852-bb275b80-b18b-11e9-845c-a61f4792dc78.png"> |

On Windows it looks a bit clumsy though:

| | Light | Dark |
| ---|---|---|
| On |<img width="279" alt="Screenshot 2019-07-28 at 23 05 00" src="https://user-images.githubusercontent.com/5447088/62012905-3a1c9400-b18c-11e9-86b7-e038533c32dd.png"> |<img width="280" alt="Screenshot 2019-07-28 at 23 04 13" src="https://user-images.githubusercontent.com/5447088/62012901-3983fd80-b18c-11e9-9852-dc67387dd13e.png"> |
| Off |<img width="272" alt="Screenshot 2019-07-28 at 23 04 50" src="https://user-images.githubusercontent.com/5447088/62012904-3a1c9400-b18c-11e9-9443-717497da5bc8.png"> | <img width="270" alt="Screenshot 2019-07-28 at 23 04 21" src="https://user-images.githubusercontent.com/5447088/62012903-3983fd80-b18c-11e9-9e4a-9a191741b467.png">|

The issue on Windows is: **we can't detect the dark or light theme right now**. I'd suggest we remove the colours and take an approach similar to what Keybase did:

| | Light | Dark |
| ---|---|---|
| On |<img width="272" alt="Screenshot 2019-07-28 at 23 15 54 1" src="https://user-images.githubusercontent.com/5447088/62013036-cf6c5800-b18d-11e9-87e7-62522f6d0871.png"> | <img width="272" alt="Screenshot 2019-07-28 at 23 15 54" src="https://user-images.githubusercontent.com/5447088/62013035-cf6c5800-b18d-11e9-91d5-e57bfa038fd2.png">|
| Off |<img width="277" alt="Screenshot 2019-07-28 at 23 16 02" src="https://user-images.githubusercontent.com/5447088/62013037-d004ee80-b18d-11e9-9f79-6a4c778935c0.png">|<img width="263" alt="Screenshot 2019-07-28 at 23 16 08" src="https://user-images.githubusercontent.com/5447088/62013038-d004ee80-b18d-11e9-8b72-a4a7047056f0.png"> |

With the white background that can certainly be improved. That way we could, perhaps, drop the coloured icons. I'd love to get some feedback from other people here. /cc @olizilla @lidel 

On macOS it seems it's settled and that it works pretty well with the styles of the other icons.

**Comment by lidel** [comment]
## In Browser toolbar (ipfs-companion)

@ericronne not sure how useful this is here, but I tried it in ipfs-companion (swapped the icon and disabled badge) next to uBlock and 1Password extensions in the browser toolbar

#### Brave (original)

![2019-07-29--14-21-27](https://user-images.githubusercontent.com/157609/62048072-3cbece00-b20c-11e9-8161-d4e241add840.png)
![2019-07-29--14-21-13](https://user-images.githubusercontent.com/157609/62048073-3cbece00-b20c-11e9-8903-fe9d154bd15d.png)

#### Brave (new)

![1-2019-07-29--13-56-50](https://user-images.githubusercontent.com/157609/62046654-c79dc980-b208-11e9-8d13-f41cac68530d.png)
![2019-07-29--13-57-08](https://user-images.githubusercontent.com/157609/62046652-c79dc980-b208-11e9-853f-cc67ed02becc.png)
![2019-07-29--14-21-13](https://user-images.githubusercontent.com/157609/62048073-3cbece00-b20c-11e9-8903-fe9d154bd15d.png)

#### Firefox (new)

![2019-07-29--13-59-35](https://user-images.githubusercontent.com/157609/62046792-2105f880-b209-11e9-8ba0-5ffa09cc78e5.png)
![2019-07-29--13-59-20](https://user-images.githubusercontent.com/157609/62046793-2105f880-b209-11e9-9b6e-555f19a0d15e.png)

![2019-07-29--14-06-43](https://user-images.githubusercontent.com/157609/62047186-2283f080-b20a-11e9-8d74-56812b04b4c0.png)
![2019-07-29--14-06-27](https://user-images.githubusercontent.com/157609/62047187-2283f080-b20a-11e9-82ef-e1a53948cbe6.png)



Mixed feelings: Not sure if those icons work in small sizes of the browser toolbar (too complex). I like the original cube in color/greyscale for "offline" and "connected" states, but would love to use those new icons for "connecting" state (below)

## Animation

I've been thinking about "connecting" animation we can build with it:

![connecting](https://user-images.githubusercontent.com/157609/62044686-d635b200-b203-11e9-9647-8ef07ec15def.gif)

(removed the dot in the middle to keep animation at the border)

It could look even better in color (if we switch between greyed out and color versions of the cube).

**Comment by hacdias** [comment]
@ericronne do we have any updates on this? I absolutely love the look of the icons on macOS, but we certainly need to see what to do on Windows and Linux. I still think that adding a white background and padding could be great on Windows and Linux, just like Keybase does:

**(Please see the icons against a colored background to see the difference)**

**macOS**

![icon-keybase-menubar-regular-black-22@3x](https://user-images.githubusercontent.com/5447088/62779776-07d43600-baac-11e9-8136-c02dadc8d569.png)

**Windows**

![icon-windows-keybase-menubar-uploading-black-16@3x](https://user-images.githubusercontent.com/5447088/62779847-2f2b0300-baac-11e9-82e6-60e859219edf.png)

**Comment by ericronne** [comment]
Hi. I'll try to pick this up again today or tomorrow.

**Comment by ericronne** [comment]
So many icon formats, yowza. Here's another take on the concept: a little beefier, and with a dashed outline for the "off" state (windows and firefox incarnations). I've approximated the sizing; it's difficult to tell from the other icons. Also the Windows icons, in particular, seem to be pixel perfect. Pixel-level crispness is not easy to achieve with this cube :/  If this seems more promising, i'll work on refining the vectors accordingly.

![1](https://user-images.githubusercontent.com/9259185/62899328-242ad980-bd1d-11e9-9d6b-384269de211a.png)
![2](https://user-images.githubusercontent.com/9259185/62899329-242ad980-bd1d-11e9-946c-c81c16b009c9.png)
![3](https://user-images.githubusercontent.com/9259185/62899330-242ad980-bd1d-11e9-8584-410ee411a503.png)

**Comment by hacdias** [comment]
@ericronne I also like these. Just one thing to note: on windows, as I said before, we **can't** detect **dark/light** mode on the taskbar. So we need an icon that works on both situations: dark and mode.

**Comment by ericronne** [comment]
Ah. So how do the other logos in the screenshots know which art to apply?

**Comment by hacdias** [comment]
@ericronne good question. Can't find any info about it, but those icons are from the Operating System itself. There might be a way to support it, but Electron doesn't support it right now (I've opened an issue about that).

**Comment by ericronne** [comment]
@hacdias i dropped four svg files onto the **[g-drive](https://drive.google.com/drive/u/0/folders/1rbAGNa6_8ToLo-FkCMYyAYUZL32rUV1S)**: 2 with white bgs ("windows") and 2 without. If you are able to give them a test implementation, we'll see how they look. Again, sorry for providing only the vectors, but i'm a little  _s  t  r   e   t   c   h  e  d_ atm 😞

**Comment by hacdias** [comment]
>  Again, sorry for providing only the vectors, but i'm a little s t r e t c h e d atm 😞

No problem, you can just update the sketch file and let me know. That way I can easily export to the right sizes.

---

On macOS they look great, as usual:

| | Light | Dark |
| ---|---|---|
| On |<img width="291" alt="Screenshot 2019-08-14 at 08 42 13" src="https://user-images.githubusercontent.com/5447088/63003438-07eb8180-be70-11e9-9de7-dc2f199cf435.png">|<img width="291" alt="Screenshot 2019-08-14 at 08 42 21" src="https://user-images.githubusercontent.com/5447088/63003439-07eb8180-be70-11e9-83f3-9910431e64ae.png">|
| Off |<img width="286" alt="Screenshot 2019-08-14 at 08 42 33" src="https://user-images.githubusercontent.com/5447088/63003441-07eb8180-be70-11e9-9334-a21032d46515.png">| <img width="308" alt="Screenshot 2019-08-14 at 08 42 27" src="https://user-images.githubusercontent.com/5447088/63003440-07eb8180-be70-11e9-9db1-69782c0e2987.png">|

On Windows:

<img width="280" alt="Screenshot 2019-08-14 at 08 51 21" src="https://user-images.githubusercontent.com/5447088/63003729-bd1e3980-be70-11e9-8ed2-17a793ef1963.png">

### My opinions

- The icon **looks good** on macOS
- The icon **does not look good** on Windows
- **I prefer** the [last iteration](https://github.com/ipfs-shipyard/ipfs-desktop/issues/956#issuecomment-515795941), which had **less** detail in such a small size.
- I'd love to ship the icons on the next version, but it's improbable.

### What I think we should do

- Rethink the icon; or
- Make the icon somehow look great on Windows; or
- Have a different icon for macOS and other platforms, using a black&white version on macOS and colored on other OSes.

**Comment by lidel** [comment]
Just noticed unfotunate https://github.com/features/package-registry/signup:

[![2019-08-14--15-40-26](https://user-images.githubusercontent.com/157609/63025646-f030ef00-bea9-11e9-9e5d-17dcd22701c9.png)](https://github.com/features/package-registry/)

:upside_down_face:

**Comment by ericronne** [comment]
Thanks so much for your patience to date @hacdias ❤️!

Yes simpler seemed wise to me, too. Files representing a less detailed take on the windows icons are   **[on the drive](https://drive.google.com/drive/u/0/folders/1rbAGNa6_8ToLo-FkCMYyAYUZL32rUV1S)**. The [sketch file](https://drive.google.com/open?id=1i0cv6IVCjiGm9dpNBYRAFdaFxNzMKlmb) is there, too.

Windows …

| | Light | Dark |
| ---|---|---|
| On |<img alt=" " src="https://user-images.githubusercontent.com/9259185/63031025-f35fb700-be78-11e9-88d6-e37ed034bd18.png">|<img alt="" src="https://user-images.githubusercontent.com/9259185/63031024-f35fb700-be78-11e9-9970-730781d748f4.png">|
| Off |<img alt=" " src="https://user-images.githubusercontent.com/9259185/63031023-f35fb700-be78-11e9-8d25-db3db5313972.png">| <img alt=" " src="https://user-images.githubusercontent.com/9259185/63031022-f2c72080-be78-11e9-8cbb-a56e7b72c886.png">|

It does lack weight / **gravitas**, primarily because the border (added since we can't detect whether the user has chosen light or dark mode) forces us to reduce the size of the icon. Alternatively, we could apply color, but to me, color makes the icon feel less professional, more "slapped on." Black and white aligns with the system-level icons, and consequently inherits some of their authority.

 I'm afraid i've invested too many hours in this project. If we think further work is needed, i can help find an outside resource. Icon design is a highly specific craft; a ton of eficianados are on [dribble](https://dribbble.com/search?q=pixel+icons), eg. We can reach out to one or two whom we like, if need be.

And re github, this is one danger of using a hexagonal logo for tech products of this type: it's going to look like someone else's logo, sigh.

Thanks, all!

**Comment by hacdias** [comment]
I'm personally annoyed by the coloured icon too and, in my opinion, even if we do not change it on other OSes, I think we should do so on macOS since that's the default and the recommended guidelines given by Apple.

On Windows in particular, users are used to see tons of colored icons on their taskbar so I don't think this would be such an issue.

@Gozala specifically about your opinions about the second version: I understand them, but I wouldn't interpret the pictures as you did haha. Also, what we need here is more of a way to distinguish between running and not running and not if we're connected to someone. At least, for now.

We've had this discussion previously but, unfortunately, we haven't came to a decision yet. Although I don't find this a priority, I would be very happy if we got nice looking icons for this.

**Comment by Gozala** [comment]
> @Gozala specifically about your opinions about the second version: I understand them, but I wouldn't interpret the pictures as you did haha.

To be clear I did not meant to suggest it was the "right way"  to interpret it, merely that some people can read those signals differently.

**Comment by Gozala** [comment]
> I'm personally annoyed by the coloured icon too and, in my opinion, even if we do not change it on other OSes, I think we should do so on macOS since that's the default and the recommended guidelines given by Apple.

I absolutely agree!! In fact that is what I was coming here to propose, before I did see all the cool visuals and got excited :) Specifically the simplest but practical change would be

To show following when node is "Running" state (current not running icon)
<img width="603" alt="Screen Shot 2019-10-23 at 12 45 28 PM" src="https://user-images.githubusercontent.com/21236/67506905-c8e16580-f642-11e9-9c46-766949f6baa5.png">

And dim that icon when "Not running", kind of like dropbox icon in the image below.
<img width="549" alt="Screen Shot 2019-10-23 at 12 45 44 PM" src="https://user-images.githubusercontent.com/21236/67506908-cbdc5600-f642-11e9-9697-f3b861ee145e.png">

I do also wish icon could be scaled up a bit to match all other icons, but even without it it would be much better IMO.

That being said, I do however find colored edges and transparent sides more visually pleasing and more distinct from others. Current version pretty much looks like dropbox icon with just box being closed.

**Comment by Gozala** [comment]
BTW I just noticed that "iCloud Drive" uses similar visual signals to one I proposed in https://github.com/ipfs-shipyard/ipfs-desktop/issues/956#issuecomment-545573908 by displaying "cloud trace" next to files that are not replicated in the cloud yet (Once it is up it disappears).  

<img width="331" alt="Screen Shot 2019-10-24 at 9 54 31 AM" src="https://user-images.githubusercontent.com/21236/67507810-92a4e580-f644-11e9-904c-6a368a474785.png">

That is to suggest that solid edge cube and traced cube edge is going to be somewhat familiar pattern that later could probably become useful once MFS mounts are further along.

**Comment by hacdias** [comment]
@Gozala honestly, I wouldn't mind and I kinda like it: simple and really easy to understand. I'd also to get more feedback from @lidel and @ericronne on this: even if we don't implement it on other OSes right now, I think it would be great to have on macOS.

**Comment by lidel** [comment]
I'm ok with OS-specific icons. This is similar to doing [translations](https://github.com/ipfs/i18n): does not need to be 1:1, a priority is to make things look and feel natural (native) in the target environment. 

Personally, I really like the simplicity of ![2019-10-26--12-50-33](https://user-images.githubusercontent.com/157609/67618393-41852500-f7ef-11e9-9574-70486dfd5946.png)  and ![2019-10-26--12-50-43](https://user-images.githubusercontent.com/157609/67618392-40ec8e80-f7ef-11e9-9b03-b121b8972844.png), and would like to see how they look like in white on dark background, especially the dotted one when dimmed :thinking:

**Comment by hacdias** [comment]
What I understood was that if we used the dotted one, we wouldn't dim it when the node is offline. Am I wrong?

And yes, I think we should make the icons for macOS. @ericronne would you be available to take a look at these?

**Comment by Gozala** [comment]
> What I understood was that if we used the dotted one, we wouldn't dim it when the node is offline. Am I wrong?

Yes I was suggesting to have dotted version for not running state and solid one for running state, so no dimming. Although that was merely a suggestion and @lidel might have something else in mind

**Comment by ericronne** [comment]
+1 for simplicity, provided the icon holds its own on the bar.

Animation to indicate "starting" would be great. I didn't know that was an option; have y'all seen others use it? If we go with that, a timeout feature of some kind might help insure that it doesn't get annoying.

If we kept the dots when the box turned solid, that might help make the "running" state look less generic

along these lines (and dots)
![image](https://user-images.githubusercontent.com/9259185/67682483-77e0b280-f95d-11e9-92c3-617fdccb76a8.png)

**Comment by hacdias** [comment]
> have y'all seen others use it? 

yas! Docker uses a pretty nice animation on the menubar while booting up! Don't know how easy it is to do with Electron though.

> If we kept the dots when the box turned solid, that might help make the "running" state look less generic

I like it!

> along these lines (and dots)

Enjoyed the pun!

**Comment by ericronne** [comment]
oh yeah, docker! 🐳

**Comment by hacdias** [comment]
This discussion has come a long way so I think we can just follow what Bluetooth logo does: gets washed off when it's offline!

<img width="68" alt="Screenshot 2019-11-21 at 12 29 16" src="https://user-images.githubusercontent.com/5447088/69365773-a1d67d80-0c5a-11ea-86e9-dfddce280070.png">
![Uploading Screenshot 2019-11-21 at 12.29.07.png…]()

We only need _one_ icon!

**Comment by hacdias** [comment]
Let's **keep it simple** now and move on this :D

**Comment by hacdias** [comment]
I think we should close this issue for now as #1256 was merged. We now have a compliant icon for macOS. Windows does not have any guidelines or way to know if we're using a dark or light theme so the icon can be used.
