### ISSUE TITLE
error at windows startup

### ISSUE THREAD

**Issue by Alexdiffff** [ipfs-shipyard/ipfs-desktop#962]
this issues ocurred everytime starting Windows 10, even restart.
![Annotation 2019-06-18 123613](https://user-images.githubusercontent.com/46273530/59663407-2cf9a600-91d9-11e9-8b23-94e850efa471.jpg)

**Comment by hacdias** [comment]
Can you click "report the error" or "Open logs" to check what the real problem was?

**Comment by hacdias** [comment]
I'm closing this since most likely it is the same as #964.
