### ISSUE TITLE
crashes on windows right after install and when i re-open it.

### ISSUE THREAD

**Issue by henrikcoll** [ipfs-shipyard/ipfs-desktop#964]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: powershell.exe -nop -exec bypass -win hidden C:\Users\Henrik Næss\AppData\Local\Programs\ipfs-desktop\resources\app.asar.unpacked\out\late\ipfs-on-path\scripts\install.ps1
C:\Users\Henrik : The term 'C:\Users\Henrik' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
  C:\Users\Henrik N�ss\AppData\Local\Programs\ipfs-desktop\resources\ap ...
  ~~~~~~~~~~~~~~~
      CategoryInfo          : ObjectNotFound: (C:\Users\Henrik:String) [], CommandNotFoundException
      FullyQualifiedErrorId : CommandNotFoundException
 

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

Seems like it can't open C:\Users\Henrik Næss\AppData\Local\Programs\ipfs-desktop\resources\app.asar.unpacked\out\late\ipfs-on-path\scripts\install.ps1 I tried opening it my self (by double clicking the file in explorer) and it seems to work now, since i don't get a error message. mabye it is caused by the space in my name or the æ

**Comment by hacdias** [comment]
I think I might now what the issue is. I'll take a look at the code. `The term 'C:\Users\Henrik' is not recognized as the name`. It seems to be breaking on the spaces, although it shouldn't.
