### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#973]
CI is failing, mostly Travis with time outs downloading Web UI or go-ipfs from the gateway.

**Comment by hacdias** [comment]
It seems IPFS Companion is moving from an hard-coded Web UI version to using the bundled version with the implementation (see https://github.com/ipfs-shipyard/ipfs-companion/issues/736). Moving on that path here would solve this CI issue.

Although, IPFS Desktop depends on IPFS Web UI even when the daemon is offline: it needs the settings page to be always available so we can't just load it from the daemon. One solution, and since all of our settings are checkboxes, would be to move them to the menubar itself.

Another solution is to keep Desktop tied to a release of Web UI and somehow fix what's going on on the CI: it's failing to download the Web UI from the gateway by timing out.

Suggestions @olizilla @lidel?

**Comment by olizilla** [comment]
The highest priority is to improve the response time from the gateway.

**Comment by hacdias** [comment]
@olizilla in the meanwhile, I'll probably update `ipfs-or-gateway` to make multiple tries (maybe 3 and configurable) because it sometimes works right after trying again, which is weird IMO, but I'll try that.

**Comment by lidel** [comment]
@hacdias it could also fallback to other trusted public gateway, eg. https://cloudflare-ipfs.com, to mitigate scenarios where only our GW is broken
