### ISSUE TITLE
Way to easily resolve ipfs/ipns paths

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#975]
So I had one idea: one of the commands I've been running most recently is `ipfs name resolve`. I think it would be a nice addition (perhaps with a shortcut even) something like this:

1. Press shortcut or option in menu
2. Paste/write path
3. OK
4. Get the resolved path and option to copy to clipboard

I don't think this should go into the Web UI itself since it should be something simple and fast for resolving names.

Opinions? /cc @ipfs-shipyard/gui

**Comment by lidel** [comment]
Note there are:
- `name resolve` –  resolves IPNS path to an immutabe IPFS path
- `resolve` – replaces any content path with direct CID

Example:

```
$ ipfs name resolve -r /ipns/tr.wikipedia-on-ipfs.org/wiki/Güneş_Sistemi.html
/ipfs/QmT5NvUtoM5nWFfrQdVrFtvGfKFmG7AHE8P34isapyhCxX/wiki/Güneş_Sistemi.html

$ ipfs resolve -r /ipns/tr.wikipedia-on-ipfs.org/wiki/Güneş_Sistemi.html
/ipfs/QmTekRfbDoSXBvguYRQx49LjaUpNYVgavjSjAq5CwW4UJd
```

Is there a good use case for having quick access to each? 
@hacdias why are you doing manual `name resolve` so often?

**Comment by hacdias** [comment]
@lidel didn't know about `resolve`. It seems the js-http-api-client doesn't support it (perhaps that's why I didn't knew it :O). Thanks!

I've been wanting to know the latest hash of `/ipns/xkcd.hacdias.com`. I've now made a simple script to pin it every day locally, but yeah, that was the reason. And I thought it might be could help more people. Not sure.

It could be a dialog with two buttons. One could get the direct/final/whatever value and the other would do the other action.

What do you think?

**Comment by lidel** [comment]
Hm..  IPFS Companion has an option to resolve & copy direct CID of the path in the current tab:

> ![2019-07-19--16-44-14](https://user-images.githubusercontent.com/157609/61543816-7ccfc500-aa44-11e9-942a-83c8debf8264.png)

Is this what you needed?

**Comment by hacdias** [comment]
@lidel yeah! I think that since Companion has it, we should not add it to Desktop then. I'll close this.

Perhaps we should add some way on IPFS Desktop to incentive the use of Companion. And if not using the default ports, a way to open something in the browser that tells Companion to use that config. We should create an issue about that!

Closing this in the meanwhile!
