### ISSUE TITLE
Prompt to set IPFS_PATH During Installation

### ISSUE THREAD

**Issue by edu-cated** [ipfs-shipyard/ipfs-desktop#988]
**Is your feature request related to a problem? Please describe.**
The .ipfs folder becomes very large and is better suited to a storage drive than the operating system's drive, where possible.  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Prompt newbies to pick their storage drive for this purpose during installation and open a GUI so they can navigate to a suitable drive's folder.

**Describe alternatives you've considered**
Manually editing the config is complex. The .ipfs folder's location is not listed in the config, so it can't easily be found or changed.

**Additional context**
Is this compatible with Open Bazzar? Will installing them both result in two large ipfs folders?

**Comment by olizilla** [comment]
We had this in a previous version of ipfs-desktop. @hacdias what are your thoughts on this?

I think it would be good to let users choose where their ipfs home directory is, but it also adds some friction to getting started. Perhaps desktop could make it easier to move your IPFS_HOME dir after you've got some use out of it.

**Comment by hacdias** [comment]
What if we added an option under Advanced to move the current IPFS repository to another location?

By adding it during installation, we could just prompt the user saying something like "ipfs repository will be created at your home directory (`path`). Do you want to put it somewhere else?" with the option "Keep it" and "Another place" (with better words for that).

It would be a bit annoying for the user, but I don't think it would actually be a bad decision.

Either way, I think we could add an option under Advanced to move the repository to another location.
