### ISSUE TITLE
electron-builder -m

### ISSUE THREAD

**Issue by jianhuaixie** [ipfs-shipyard/ipfs-desktop#992]
⨯ Application entry file "out/index.js" in the "/Users/mac/Documents/ipfs-desktop/dist/mac/IPFS Desktop.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=

**Comment by hacdias** [comment]
Hello @jianhuaixie! To build, you should run `npm run build`. What are you trying to do?

**Comment by hacdias** [comment]
Since we did not get any more information and I can't reproduce the issue, I am closing this issue for now. If you need further help, please let me know.
