### ISSUE TITLE
[ipfsd]Cannot find the IPFS executable

### ISSUE THREAD

**Issue by shareven** [ipfs-shipyard/ipfs-desktop#995]
i downloaded ipfs-desktop v0.8.0 source code , then npm i &&npm start :
![屏幕快照 2019-07-24 下午6 46 33](https://user-images.githubusercontent.com/25793040/61788083-c274ff00-ae43-11e9-87f4-8d979d93cdfb.png)
error: [ipfsd]Cannot find the IPFS executable

**Comment by hacdias** [comment]
Did `npm install` run successfully? It seems the binary wasn't downloaded during `npm i`.

**Comment by shareven** [comment]
i rm -rf node_modules  && npm i .show the error:
<img width="1119" alt="屏幕快照 2019-07-25 下午2 10 29" src="https://user-images.githubusercontent.com/25793040/61850106-fef93700-aee5-11e9-81da-527cdbabd151.png">

FetchError: request to https://dist.ipfs.io/go-ipfs/versions failed, reason: connect ETIMEDOUT 174.37.154.236:443
Download failed!

PING 174.37.154.236 is Request timeout

**Comment by shareven** [comment]
but when i use browser ,i can get the response;
![屏幕快照 2019-07-25 下午2 21 45](https://user-images.githubusercontent.com/25793040/61850723-8f844700-aee7-11e9-8332-83c6461998a5.png)

**Comment by hacdias** [comment]
That's the issue and is not directly related to IPFS Desktop. We've noticed the gateway is timing out for certain computers (something related with DNS cache) on certain circumstances - as you see the browser worked, while it didn't work on the terminal.

That's basically what's happening on CI: it works every time on AppVeyor but Travis always fails to download with time outs.

/cc @olizilla

**Comment by shareven** [comment]
now npm start is ok, but the window is blank.
<img width="721" alt="屏幕快照 2019-07-25 下午4 11 14" src="https://user-images.githubusercontent.com/25793040/61857702-3b815e80-aef7-11e9-935e-b03afc255e19.png">

**Comment by hacdias** [comment]
Yeah, that's because of the error during `npm install`. Otherwise it'd work well. For now I don't have any recommendation despite trying again. Could you try using Cloudflare's DNS? https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/

**Comment by hacdias** [comment]
The `dist.ipfs.io` website already got a fix for the timeouts causing this. I will close this issue for now. Let me know if everything works on your end!
